{
  "hash": "6f8b96a829c7e770c4c86af34b4abfee",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Part 3: SingleM/Lyrebird Diversity Analysis\"\nsubtitle: \"PC047 vCagAepitope - OTU-based多样性分析\"\nauthor:\n  - name: Gong Yuhang\ndate: today\ntoc: true\ntoc-depth: 4\nnumber-sections: true\ncode-fold: true\ncode-line-numbers: true\ncode-tools: true\nformat:\n  html:\n    embed-resources: true\n    smooth-scroll: true\n    page-layout: full\n    fig-width: 7.2\n    fig-height: 5\n    fig-dpi: 300\nexecute:\n  warning: false\n  message: false\nreference-location: section\ncitation-location: document\nparams:\n  name: \"03_singlem_diversity_analysis\"\n---\n\n# 研究问题 {#sec-question}\n\n> **核心问题**：使用独立方法（SingleM/Lyrebird）验证Part 1的发现是否可重复？\n>\n> **假说**：如果CagA确实重塑了微生物组，不同分类方法应得到一致结论。\n\n## 分析背景\n\n本文档使用SingleM（细菌/古菌）和Lyrebird（噬菌体）的OTU-based分类结果，独立验证Part 1的发现。\n\n**相比Part 1（Kraken2/Bracken）的优势**：\n\n| 特性 | Kraken2/Bracken | SingleM/Lyrebird |\n|------|----------------|------------------|\n| 系统发育 | 无 | 有（可计算UniFrac） |\n| 新物种检测 | 仅数据库已知 | 可识别新物种 |\n| 分辨率 | 物种级 | OTU级 |\n\n---\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsuppressPackageStartupMessages({\n  library(here)\n  library(conflicted)\n  library(tidyverse)\n  library(data.table)\n  library(mia)\n  library(TreeSummarizedExperiment)\n  library(readxl)\n  library(miaViz)\n  library(scuttle)\n  library(patchwork)\n  library(MatrixGenerics)\n  library(stringr)\n  library(ggpubr)\n\n  library(scater)\n  library(vegan)\n  library(ggplot2)\n  library(ANCOMBC)\n  library(ALDEx2)\n  library(ape) # 用于读取系统发育树\n  library(phyloseq) # UniFrac 计算的稳定实现\n  library(Hmisc) # Part 6: 高效相关性计算\n  library(pheatmap) # Part 6: 热图可视化\n  library(igraph) # Part 6: 网络分析\n  library(ggraph) # Part 6: 网络可视化\n  devtools::load_all()\n})\n\n# 解决命名空间冲突\nconflicts_prefer(base::setdiff)\nconflicts_prefer(dplyr::filter)\nconflicts_prefer(dplyr::select)\nconflicts_prefer(dplyr::lag)\nconflicts_prefer(dplyr::first)\nconflicts_prefer(dplyr::left_join)\nconflicts_prefer(ggplot2::annotate)\nconflicts_prefer(base::intersect)\nconflicts_prefer(igraph::degree)\nconflicts_prefer(igraph::betweenness)\nconflicts_prefer(igraph::closeness)\n\nset.seed(20261)\n```\n:::\n\n\n# Part 1: SingleM细菌/古菌分析 {#sec-part1}\n\n## 1.1 数据导入与 TSE 构建\n\n根据 SingleM Protocol，我们使用以下分析就绪文件：\n- `*_OTU_abundance.tsv`: OTU 丰度矩阵（相对丰度 %）\n- `*_OTU_taxonomy.tsv`: OTU 分类信息\n- `*_OTU_tree.nwk`: 系统发育树（用于 UniFrac 计算）\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# Step 1: 定义数据路径\n# ==============================================================================\nsinglem_data_path <- here::here(\n  \"data\", \"00-raw\", \"d03_singlem_diversity_analysis\", \"pc047-rst_singleM\"\n)\n\n# ==============================================================================\n# Step 2: 读取 OTU 丰度矩阵\n# ==============================================================================\n# SingleM 输出的是相对丰度（百分比），我们将其转换为比例（0-1）\notu_abundance <- read_tsv(\n  file.path(singlem_data_path, \"pc047-singleM_OTU_abundance.tsv\"),\n  show_col_types = FALSE\n) |>\n  column_to_rownames(\"otu_id\") |>\n  as.matrix()\n\n# 将百分比转换为比例\notu_abundance <- otu_abundance / 100\n\ncat(\"OTU 矩阵维度:\", dim(otu_abundance), \"\\n\")\n#> OTU 矩阵维度: 640 33\ncat(\"样本数:\", ncol(otu_abundance), \"\\n\")\n#> 样本数: 33\ncat(\"OTU 数:\", nrow(otu_abundance), \"\\n\")\n#> OTU 数: 640\n\n# ==============================================================================\n# Step 3: 读取 OTU 分类信息\n# ==============================================================================\notu_taxonomy <- read_tsv(\n  file.path(singlem_data_path, \"pc047-singleM_OTU_taxonomy.tsv\"),\n  show_col_types = FALSE\n) |>\n  column_to_rownames(\"otu_id\") |>\n  DataFrame()\n\n# 查看分类层级\ncat(\"分类层级:\", colnames(otu_taxonomy), \"\\n\")\n#> 分类层级: Root Domain Phylum Class Order Family Genus Species\n\n# ==============================================================================\n# Step 4: 读取系统发育树\n# ==============================================================================\notu_tree <- ape::read.tree(\n  file.path(singlem_data_path, \"pc047-singleM_OTU_tree.nwk\")\n)\n\ncat(\"系统发育树 tip 数:\", length(otu_tree$tip.label), \"\\n\")\n#> 系统发育树 tip 数: 640\n\n# ==============================================================================\n# Step 5: 构建 TreeSummarizedExperiment 对象\n# ==============================================================================\n# 确保 OTU ID 顺序一致\ncommon_otus <- base::intersect(rownames(otu_abundance), rownames(otu_taxonomy))\ncommon_otus <- base::intersect(common_otus, otu_tree$tip.label)\n\ncat(\"共同 OTU 数:\", length(common_otus), \"\\n\")\n#> 共同 OTU 数: 640\n\n# 子集化数据\notu_abundance <- otu_abundance[common_otus, ]\notu_taxonomy <- otu_taxonomy[common_otus, ]\notu_tree <- ape::keep.tip(otu_tree, common_otus)\n\n# 创建 TSE 对象\n# 注意：SingleM 输出是相对丰度，我们将其乘以 10000 作为伪计数以便后续分析\ntse_singlem <- TreeSummarizedExperiment(\n  assays = list(\n    relabundance = otu_abundance,\n    counts = round(otu_abundance * 10000) # 伪计数用于某些需要整数的分析\n  ),\n  rowData = otu_taxonomy,\n  rowTree = otu_tree\n)\n\ntse_singlem\n#> class: TreeSummarizedExperiment \n#> dim: 640 33 \n#> metadata(0):\n#> assays(2): relabundance counts\n#> rownames(640): OTU_1 OTU_2 ... OTU_639 OTU_640\n#> rowData names(8): Root Domain ... Genus Species\n#> colnames(33): ca01 ca02 ... ic03 ic04\n#> colData names(0):\n#> reducedDimNames(0):\n#> mainExpName: NULL\n#> altExpNames(0):\n#> rowLinks: a LinkDataFrame (640 rows)\n#> rowTree: 1 phylo tree(s) (640 leaves)\n#> colLinks: NULL\n#> colTree: NULL\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# Step 6: 绑定样本元数据\n# ==============================================================================\nmetadata <- readxl::read_xlsx(\n  here::here(\"data\", \"metadata\", \"pc047-metadata.xlsx\")\n) |>\n  column_to_rownames(\"sample_id\")\n\n# 匹配样本名\ncommon_samples <- base::intersect(colnames(tse_singlem), rownames(metadata))\ncat(\"匹配的样本数:\", length(common_samples), \"\\n\")\n#> 匹配的样本数: 33\n\ntse_singlem <- tse_singlem[, common_samples]\ncolData(tse_singlem) <- DataFrame(metadata[common_samples, ])\n\n# ==============================================================================\n# Step 7: 创建 Caecum 子集\n# ==============================================================================\n# 本项目主要分析 caecum（盲肠）样本\ntse_singlem_ca <- tse_singlem[, tse_singlem$source_organ == \"caecum\"]\n\ncat(\"Caecum 样本数:\", ncol(tse_singlem_ca), \"\\n\")\n#> Caecum 样本数: 29\ncat(\"各实验组样本分布:\\n\")\n#> 各实验组样本分布:\nprint(table(tse_singlem_ca$treatment_group))\n#> \n#> ApcMUT_Ctrl ApcMUT_HpKO ApcMUT_HpWT  ApcWT_Ctrl  ApcWT_HpKO  ApcWT_HpWT \n#>           5           4           5           5           5           5\n\ntse_singlem_ca\n#> class: TreeSummarizedExperiment \n#> dim: 640 29 \n#> metadata(0):\n#> assays(2): relabundance counts\n#> rownames(640): OTU_1 OTU_2 ... OTU_639 OTU_640\n#> rowData names(8): Root Domain ... Genus Species\n#> colnames(29): ca01 ca02 ... ca29 ca30\n#> colData names(11): mouse_id genotype ... path_r1 path_r2\n#> reducedDimNames(0):\n#> mainExpName: NULL\n#> altExpNames(0):\n#> rowLinks: a LinkDataFrame (640 rows)\n#> rowTree: 1 phylo tree(s) (640 leaves)\n#> colLinks: NULL\n#> colTree: NULL\n```\n:::\n\n\n## 1.2 数据探索与质量控制 (QC)\n\n### 1.2.1 第一遍清洗：数据探索\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# 1. 计算文库大小（基于伪计数）\n# ==============================================================================\ntse_singlem_ca_1 <- tse_singlem_ca\ntse_singlem_ca_1 <- addPerCellQCMetrics(tse_singlem_ca_1, assay.type = \"counts\")\n\n# 可视化文库大小分布\np1 <- plotHistogram(tse_singlem_ca_1, col.var = \"total\") +\n  labs(title = \"SingleM: Library Size Distribution\", x = \"Total Pseudo-counts\")\np1\n```\n\n::: {.cell-output-display}\n![](03_singlem_diversity_analysis_files/figure-html/singlem-qc-round1-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\n\nggsave(\n  filename = here::here(\"data\", params$name, \"01_qc_library_size_singlem.png\"),\n  plot = p1, width = 8, height = 6, dpi = 300\n)\n\n# ==============================================================================\n# 2. Prevalence 分析\n# ==============================================================================\ntse_singlem_ca_1 <- addPrevalence(\n  tse_singlem_ca_1,\n  assay.type = \"relabundance\",\n  detection = 0,\n  as.relative = FALSE # 已经是相对丰度\n)\n\nrowData(tse_singlem_ca_1)$prevalence <- as.numeric(rowData(tse_singlem_ca_1)$prevalence)\nsummary(rowData(tse_singlem_ca_1)$prevalence)\n#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n#> 0.00000 0.06897 0.27586 0.36681 0.62069 1.00000\n\np2 <- plotHistogram(tse_singlem_ca_1, row.var = \"prevalence\") +\n  labs(title = \"SingleM: OTU Prevalence Distribution\", x = \"Prevalence (Fraction of Samples)\")\np2\n```\n\n::: {.cell-output-display}\n![](03_singlem_diversity_analysis_files/figure-html/singlem-qc-round1-2.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\n\nggsave(\n  filename = here::here(\"data\", params$name, \"02_qc_prevalence_singlem.png\"),\n  plot = p2, width = 8, height = 6, dpi = 300\n)\n\n# ==============================================================================\n# 3. 查看丰度最高的 OTU\n# ==============================================================================\ntop_otus <- getTop(tse_singlem_ca_1, top = 10, assay.type = \"relabundance\")\ncat(\"Top 10 OTUs:\\n\")\n#> Top 10 OTUs:\nprint(top_otus)\n#>  [1] \"OTU_260\" \"OTU_179\" \"OTU_155\" \"OTU_183\" \"OTU_261\" \"OTU_280\" \"OTU_163\"\n#>  [8] \"OTU_285\" \"OTU_277\" \"OTU_269\"\n\n# 查看对应的分类信息\ncat(\"\\nTop 10 OTU 分类信息:\\n\")\n#> \n#> Top 10 OTU 分类信息:\nprint(rowData(tse_singlem_ca_1)[top_otus, ])\n#> DataFrame with 10 rows and 9 columns\n#>                Root      Domain       Phylum       Class          Order\n#>         <character> <character>  <character> <character>    <character>\n#> OTU_260        Root    Bacteria Bacteroidota Bacteroidia  Bacteroidales\n#> OTU_179        Root    Bacteria    Bacillota  Clostridia Lachnospirales\n#> OTU_155        Root    Bacteria    Bacillota  Clostridia Lachnospirales\n#> OTU_183        Root    Bacteria    Bacillota  Clostridia Lachnospirales\n#> OTU_261        Root    Bacteria Bacteroidota Bacteroidia  Bacteroidales\n#> OTU_280        Root    Bacteria Bacteroidota Bacteroidia  Bacteroidales\n#> OTU_163        Root    Bacteria    Bacillota  Clostridia Lachnospirales\n#> OTU_285        Root    Bacteria Bacteroidota Bacteroidia  Bacteroidales\n#> OTU_277        Root    Bacteria Bacteroidota Bacteroidia  Bacteroidales\n#> OTU_269        Root    Bacteria Bacteroidota Bacteroidia  Bacteroidales\n#>                  Family         Genus                Species prevalence\n#>             <character>   <character>            <character>  <numeric>\n#> OTU_260  Muribaculaceae       UBA7173    UBA7173 sp001689685   0.965517\n#> OTU_179 Lachnospiraceae       UBA3282    UBA3282 sp009774215   0.827586\n#> OTU_155 Lachnospiraceae Acetatifactor Acetatifactor sp9105..   0.827586\n#> OTU_183 Lachnospiraceae       UBA3282    UBA3282 sp910575775   0.931034\n#> OTU_261  Muribaculaceae     Lepagella  Lepagella sp009775375   0.965517\n#> OTU_280  Muribaculaceae       CAG-873    CAG-873 sp001689665   0.862069\n#> OTU_163 Lachnospiraceae          COE1       COE1 sp000403215   0.758621\n#> OTU_285   Rikenellaceae     Alistipes  Alistipes sp910575495   0.931034\n#> OTU_277  Muribaculaceae       CAG-873    CAG-873 sp002490635   0.965517\n#> OTU_269  Muribaculaceae   Duncaniella      Duncaniella muris   0.965517\n```\n:::\n\n\n### 1.2.2 第二遍清洗：去除异常样本\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# 1. 检查是否有异常样本（如 ca08 在 01 分析中被识别为污染）\n# ==============================================================================\ntse_singlem_ca_2 <- tse_singlem_ca\n\n# 查看 ca08 的情况\nif (\"ca08\" %in% colnames(tse_singlem_ca_2)) {\n  ca08_top <- sort(assay(tse_singlem_ca_2[, \"ca08\"], \"relabundance\"), decreasing = TRUE)[1:5]\n  cat(\"ca08 样本 Top 5 OTU 丰度:\\n\")\n  print(ca08_top)\n\n  # 根据 01 分析结果，ca08 存在 E. coli 异常高丰度，考虑移除\n  cat(\"\\n根据 01 分析结果，移除 ca08 样本\\n\")\n  tse_singlem_ca_2 <- tse_singlem_ca_2[, colnames(tse_singlem_ca_2) != \"ca08\"]\n}\n#> ca08 样本 Top 5 OTU 丰度:\n#> [1] 0.0286 0.0164 0.0164 0.0146 0.0097\n#> \n#> 根据 01 分析结果，移除 ca08 样本\n\ncat(\"清洗后样本数:\", ncol(tse_singlem_ca_2), \"\\n\")\n#> 清洗后样本数: 28\n\n# ==============================================================================\n# 2. Prevalence 过滤（保留 >10% 样本中出现的 OTU）\n# ==============================================================================\ntse_singlem_ca_2 <- addPrevalence(\n  tse_singlem_ca_2,\n  assay.type = \"relabundance\",\n  detection = 0,\n  as.relative = FALSE\n)\n\ncat(\"过滤前 OTU 数:\", nrow(tse_singlem_ca_2), \"\\n\")\n#> 过滤前 OTU 数: 640\ntse_singlem_ca_2 <- subsetByPrevalent(tse_singlem_ca_2, prevalence = 0.1)\ncat(\"过滤后 OTU 数:\", nrow(tse_singlem_ca_2), \"\\n\")\n#> 过滤后 OTU 数: 465\n\n# ==============================================================================\n# 3. 更新 QC 指标\n# ==============================================================================\ntse_singlem_ca_2 <- addPerCellQCMetrics(tse_singlem_ca_2, assay.type = \"counts\")\n\np3 <- plotHistogram(tse_singlem_ca_2, col.var = \"total\") +\n  labs(title = \"SingleM: Library Size (After Cleaning)\", x = \"Total Pseudo-counts\")\np3\n```\n\n::: {.cell-output-display}\n![](03_singlem_diversity_analysis_files/figure-html/singlem-qc-round2-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\n\nggsave(\n  filename = here::here(\"data\", params$name, \"03_qc_library_size_cleaned_singlem.png\"),\n  plot = p3, width = 8, height = 6, dpi = 300\n)\n```\n:::\n\n\n### 1.2.3 清洗后数据整理\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# 保存清洗后的 TSE 对象\n# ==============================================================================\ntse_singlem_ca_cleaned <- tse_singlem_ca_2\n\n# 查看分类层级\ncat(\"可用的分类层级:\\n\")\n#> 可用的分类层级:\nprint(taxonomyRanks(tse_singlem_ca_cleaned))\n#> [1] \"Domain\"  \"Phylum\"  \"Class\"   \"Order\"   \"Family\"  \"Genus\"   \"Species\"\n\n# 保存清洗后的数据\nsaveRDS(\n  tse_singlem_ca_cleaned,\n  file = here::here(\"data\", params$name, \"tse_singlem_ca_cleaned.rds\")\n)\n\ntse_singlem_ca_cleaned\n#> class: TreeSummarizedExperiment \n#> dim: 465 28 \n#> metadata(0):\n#> assays(2): relabundance counts\n#> rownames(465): OTU_1 OTU_2 ... OTU_595 OTU_598\n#> rowData names(9): Root Domain ... Species prevalence\n#> colnames(28): ca01 ca02 ... ca29 ca30\n#> colData names(14): mouse_id genotype ... detected total\n#> reducedDimNames(0):\n#> mainExpName: NULL\n#> altExpNames(0):\n#> rowLinks: a LinkDataFrame (465 rows)\n#> rowTree: 1 phylo tree(s) (465 leaves)\n#> colLinks: NULL\n#> colTree: NULL\n```\n:::\n\n\n## 1.3 群落组成可视化\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# 1. Top 10 OTU 组成图\n# ==============================================================================\ntop_otus_cleaned <- getTop(tse_singlem_ca_cleaned, top = 10, assay.type = \"relabundance\")\n\n# 创建用于绘图的 TSE 副本\ntse_plot <- tse_singlem_ca_cleaned\n\n# 将非 Top 10 的 OTU 标记为 \"Other\"\nrowData(tse_plot)$OTU_Top10 <- ifelse(\n  rownames(tse_plot) %in% top_otus_cleaned,\n  paste0(rownames(tse_plot), \" (\", rowData(tse_plot)$Family, \")\"),\n  \"Other\"\n)\n\n# 聚合\ntse_plot_agg <- agglomerateByVariable(tse_plot, by = \"rows\", f = \"OTU_Top10\")\n\n# 绘图\np_comp <- plotAbundance(\n  tse_plot_agg,\n  assay.type = \"relabundance\",\n  order.row.by = \"abund\",\n  order.col.by = \"Other\"\n) +\n  labs(\n    title = \"SingleM: Top 10 OTU Composition (Caecum)\",\n    subtitle = \"Non-top OTUs grouped as 'Other'\"\n  ) +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8))\n\np_comp\n```\n\n::: {.cell-output-display}\n![](03_singlem_diversity_analysis_files/figure-html/singlem-composition-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\n\nggsave(\n  filename = here::here(\"data\", params$name, \"04_composition_top10_singlem.png\"),\n  plot = p_comp, width = 14, height = 8, dpi = 300\n)\n\n# ==============================================================================\n# 2. 按 Phylum 聚合的组成图\n# ==============================================================================\n# 检查是否有 Phylum 列\nif (\"Phylum\" %in% colnames(rowData(tse_singlem_ca_cleaned))) {\n  tse_phylum <- agglomerateByRank(tse_singlem_ca_cleaned, rank = \"Phylum\")\n\n  p_phylum <- plotAbundance(\n    tse_phylum,\n    assay.type = \"relabundance\",\n    order.row.by = \"abund\"\n  ) +\n    labs(title = \"SingleM: Phylum-level Composition\") +\n    theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8))\n\n  p_phylum\n\n  ggsave(\n    filename = here::here(\"data\", params$name, \"05_composition_phylum_singlem.png\"),\n    plot = p_phylum, width = 14, height = 8, dpi = 300\n  )\n}\n```\n:::\n\n\n## 1.4 Alpha 多样性分析\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# 1. 计算 Alpha 多样性指数\n# ==============================================================================\ntse_singlem_ca_cleaned <- addAlpha(\n  tse_singlem_ca_cleaned,\n  assay.type = \"counts\",\n  index = c(\"shannon\", \"observed\"),\n  name = c(\"shannon_index\", \"observed_richness\")\n)\n\ncat(\"Alpha 多样性指数已计算\\n\")\n#> Alpha 多样性指数已计算\n\n# ==============================================================================\n# 2. 提取核心比较组 (ApcMUT_HpWT vs ApcMUT_HpKO)\n# ==============================================================================\ntse_singlem_corepair <- tse_singlem_ca_cleaned[\n  , tse_singlem_ca_cleaned$treatment_group %in% c(\"ApcMUT_HpWT\", \"ApcMUT_HpKO\")\n]\ntse_singlem_corepair$treatment_group <- factor(tse_singlem_corepair$treatment_group)\n\ncat(\"核心比较组样本数:\\n\")\n#> 核心比较组样本数:\nprint(table(tse_singlem_corepair$treatment_group))\n#> \n#> ApcMUT_HpKO ApcMUT_HpWT \n#>           4           5\n\n# ==============================================================================\n# 3. 统计检验 (Wilcoxon 秩和检验)\n# ==============================================================================\n# Shannon 指数检验\nwilcox_shannon <- wilcox.test(\n  shannon_index ~ treatment_group,\n  data = colData(tse_singlem_corepair)\n)\ncat(\"\\nShannon 指数 Wilcoxon 检验 P 值:\", round(wilcox_shannon$p.value, 4), \"\\n\")\n#> \n#> Shannon 指数 Wilcoxon 检验 P 值: 0.9048\n\n# Observed richness 检验\nwilcox_observed <- wilcox.test(\n  observed_richness ~ treatment_group,\n  data = colData(tse_singlem_corepair)\n)\ncat(\"Observed Richness Wilcoxon 检验 P 值:\", round(wilcox_observed$p.value, 4), \"\\n\")\n#> Observed Richness Wilcoxon 检验 P 值: 0.1111\n\n# ==============================================================================\n# 4. 可视化\n# ==============================================================================\nplot_alpha <- function(tse, y_var, title) {\n  plotColData(tse,\n    x = \"treatment_group\", y = y_var,\n    colour_by = \"treatment_group\",\n    show_boxplot = TRUE\n  ) +\n    stat_compare_means(\n      comparisons = list(c(\"ApcMUT_HpKO\", \"ApcMUT_HpWT\")),\n      method = \"wilcox.test\", label = \"p.format\"\n    ) +\n    labs(title = title, x = \"Group\", y = \"Index Value\") +\n    theme_bw() +\n    theme(legend.position = \"none\")\n}\n\np_shannon <- plot_alpha(tse_singlem_corepair, \"shannon_index\", \"SingleM: Shannon Diversity\")\np_observed <- plot_alpha(tse_singlem_corepair, \"observed_richness\", \"SingleM: Observed OTU Richness\")\n\np_alpha_combined <- p_shannon + p_observed +\n  plot_annotation(title = \"SingleM Alpha Diversity: ApcMUT_HpWT vs ApcMUT_HpKO\")\np_alpha_combined\n```\n\n::: {.cell-output-display}\n![](03_singlem_diversity_analysis_files/figure-html/singlem-alpha-diversity-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\n\nggsave(\n  filename = here::here(\"data\", params$name, \"06_alpha_diversity_singlem.png\"),\n  plot = p_alpha_combined, width = 12, height = 6, dpi = 300\n)\n```\n:::\n\n\n## 1.5 Beta 多样性分析\n\n### 1.5.1 Bray-Curtis 距离\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# 1. PCoA (Bray-Curtis)\n# ==============================================================================\ntse_singlem_corepair <- runMDS(\n  tse_singlem_corepair,\n  FUN = vegan::vegdist,\n  method = \"bray\",\n  assay.type = \"relabundance\",\n  name = \"PCoA_Bray\"\n)\n\n# 提取特征值\neig_bray <- attr(reducedDim(tse_singlem_corepair, \"PCoA_Bray\"), \"eig\")\nrel_eig_bray <- eig_bray / sum(eig_bray[eig_bray > 0])\n\n# 可视化\np_pcoa_bray <- plotReducedDim(\n  tse_singlem_corepair,\n  \"PCoA_Bray\",\n  colour_by = \"treatment_group\"\n) +\n  theme_bw() +\n  labs(\n    title = \"SingleM: PCoA (Bray-Curtis)\",\n    x = paste0(\"PCoA 1 (\", round(100 * rel_eig_bray[1], 1), \"%)\"),\n    y = paste0(\"PCoA 2 (\", round(100 * rel_eig_bray[2], 1), \"%)\")\n  )\np_pcoa_bray\n```\n\n::: {.cell-output-display}\n![](03_singlem_diversity_analysis_files/figure-html/singlem-beta-bray-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\n\nggsave(\n  filename = here::here(\"data\", params$name, \"07_beta_pcoa_bray_singlem.png\"),\n  plot = p_pcoa_bray, width = 8, height = 6, dpi = 300\n)\n\n# ==============================================================================\n# 2. PERMANOVA 检验 (Bray-Curtis)\n# ==============================================================================\npermanova_bray <- getPERMANOVA(\n  tse_singlem_corepair,\n  assay.type = \"relabundance\",\n  formula = x ~ treatment_group\n)\n\ncat(\"\\n=== PERMANOVA (Bray-Curtis) ===\\n\")\n#> \n#> === PERMANOVA (Bray-Curtis) ===\nprint(permanova_bray$permanova)\n#> Permutation test for adonis under reduced model\n#> Marginal effects of terms\n#> Permutation: free\n#> Number of permutations: 999\n#> \n#> adonis2(formula = formula, data = data, method = ..1, by = by, na.action = na.action)\n#>                 Df SumOfSqs      R2      F Pr(>F)  \n#> treatment_group  1  0.28247 0.23146 2.1082  0.037 *\n#> Residual         7  0.93791 0.76854                \n#> Total            8  1.22038 1.00000                \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nwrite.csv(\n  permanova_bray$permanova,\n  file = here::here(\"data\", params$name, \"08_permanova_bray_singlem.csv\"),\n  row.names = TRUE\n)\n```\n:::\n\n\n### 1.5.2 UniFrac 距离（利用系统发育树）\n\n::: {.callout-important}\n## UniFrac 分析的重要性\n\nUniFrac 是 SingleM 数据的**核心优势**：\n- **Bray-Curtis** 只比较丰度数值，忽略进化关系\n- **UniFrac** 通过系统发育树比较\"演化家谱\"，能识别**株系级遗传偏移**\n\n对于 pc047 项目，UniFrac 可以揭示 HpWT 组是否整体向特定\"致病演化支\"偏移。\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# Step 1: 诊断树和 OTU 矩阵的匹配情况\n# ==============================================================================\ncat(\"=== UniFrac 计算前诊断 ===\\n\\n\")\n#> === UniFrac 计算前诊断 ===\n\n# 获取树和 OTU 信息\ntree <- rowTree(tse_singlem_corepair)\notu_names <- rownames(tse_singlem_corepair)\ntree_tips <- tree$tip.label\n\ncat(\"OTU 矩阵中的 OTU 数量:\", length(otu_names), \"\\n\")\n#> OTU 矩阵中的 OTU 数量: 465\ncat(\"系统发育树的 tip 数量:\", length(tree_tips), \"\\n\")\n#> 系统发育树的 tip 数量: 465\n\n# 检查匹配情况\nin_both <- base::intersect(otu_names, tree_tips)\nonly_in_otu <- setdiff(otu_names, tree_tips)\nonly_in_tree <- setdiff(tree_tips, otu_names)\n\ncat(\"两者共有的 OTU:\", length(in_both), \"\\n\")\n#> 两者共有的 OTU: 465\ncat(\"仅在 OTU 矩阵中:\", length(only_in_otu), \"\\n\")\n#> 仅在 OTU 矩阵中: 0\ncat(\"仅在树中:\", length(only_in_tree), \"\\n\")\n#> 仅在树中: 0\n\nif (length(only_in_otu) > 0) {\n  cat(\"\\n警告: 以下 OTU 不在树中:\\n\")\n  print(head(only_in_otu, 10))\n}\n\n# 检查树是否有效\ncat(\"\\n树结构检查:\\n\")\n#> \n#> 树结构检查:\ncat(\"  - 是否为二叉树:\", ape::is.binary(tree), \"\\n\")\n#>   - 是否为二叉树: FALSE\ncat(\"  - 是否有根:\", ape::is.rooted(tree), \"\\n\")\n#>   - 是否有根: TRUE\n\n# 检查边长\nif (!is.null(tree$edge.length) && length(tree$edge.length) > 0) {\n  valid_edges <- tree$edge.length[is.finite(tree$edge.length)]\n  if (length(valid_edges) > 0) {\n    cat(\"  - 有效边长范围:\", range(valid_edges), \"\\n\")\n  } else {\n    cat(\"  - 有效边长范围: 无有效边长!\\n\")\n  }\n  cat(\"  - 总边数:\", length(tree$edge.length), \"\\n\")\n  cat(\"  - NA 边长数量:\", sum(is.na(tree$edge.length)), \"\\n\")\n  cat(\"  - Inf 边长数量:\", sum(is.infinite(tree$edge.length)), \"\\n\")\n  cat(\"  - 负数边长数量:\", sum(tree$edge.length < 0, na.rm = TRUE), \"\\n\")\n} else {\n  cat(\"  - 边长信息: 树没有边长信息!\\n\")\n}\n#>   - 边长信息: 树没有边长信息!\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# Step 2: 修复树的边长问题\n# ==============================================================================\ncat(\"\\n=== 修复树的边长 ===\\n\")\n#> \n#> === 修复树的边长 ===\n\n# 获取原始树\ntree_original <- rowTree(tse_singlem_corepair)\n\n# 复制树进行修复\ntree_fixed <- tree_original\n\n# 检查并修复边长\nif (is.null(tree_fixed$edge.length) || length(tree_fixed$edge.length) == 0) {\n  # 如果完全没有边长，创建默认边长（全部设为 1）\n  cat(\"树没有边长信息，创建默认边长...\\n\")\n  tree_fixed$edge.length <- rep(1, nrow(tree_fixed$edge))\n} else {\n  # 统计问题边长\n  n_na <- sum(is.na(tree_fixed$edge.length))\n  n_inf <- sum(is.infinite(tree_fixed$edge.length))\n  n_neg <- sum(tree_fixed$edge.length < 0, na.rm = TRUE)\n  n_zero <- sum(tree_fixed$edge.length == 0, na.rm = TRUE)\n\n  cat(\"发现问题边长:\\n\")\n  cat(\"  - NA:\", n_na, \"\\n\")\n  cat(\"  - Inf:\", n_inf, \"\\n\")\n  cat(\"  - 负数:\", n_neg, \"\\n\")\n  cat(\"  - 零:\", n_zero, \"\\n\")\n\n  # 修复异常值：替换为极小的正数\n  small_value <- 1e-6\n\n  # 替换 NA\n  tree_fixed$edge.length[is.na(tree_fixed$edge.length)] <- small_value\n\n  # 替换 Inf\n  tree_fixed$edge.length[is.infinite(tree_fixed$edge.length)] <- small_value\n\n  # 替换负数\n  tree_fixed$edge.length[tree_fixed$edge.length < 0] <- small_value\n\n  # 替换零（某些算法不能处理零边长）\n  tree_fixed$edge.length[tree_fixed$edge.length == 0] <- small_value\n\n  cat(\"\\n修复后边长范围:\", range(tree_fixed$edge.length), \"\\n\")\n}\n#> 树没有边长信息，创建默认边长...\n\n# 更新 TSE 对象中的树\nrowTree(tse_singlem_corepair) <- tree_fixed\n\ncat(\"树修复完成!\\n\")\n#> 树修复完成!\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# Step 3: 使用 mia 原生函数计算 UniFrac（OMA 推荐）\n# ==============================================================================\ncat(\"\\n=== 使用 mia 计算 UniFrac 距离 ===\\n\")\n#> \n#> === 使用 mia 计算 UniFrac 距离 ===\n\nunifrac_success <- FALSE\n\ntryCatch({\n  # 确保使用修复后的树\n  tree_for_unifrac <- rowTree(tse_singlem_corepair)\n\n  # 确保 OTU 和树完全匹配\n  common_taxa <- base::intersect(rownames(tse_singlem_corepair), tree_for_unifrac$tip.label)\n  cat(\"使用\", length(common_taxa), \"个共同 OTU 进行 UniFrac 计算\\n\")\n\n  # 子集化 TSE 对象以确保匹配\n  tse_for_unifrac <- tse_singlem_corepair[common_taxa, ]\n\n  # 修剪树\n  tree_pruned <- ape::keep.tip(tree_for_unifrac, common_taxa)\n  rowTree(tse_for_unifrac) <- tree_pruned\n\n  # 使用 mia::getDissimilarity 计算 UniFrac\n  cat(\"\\n计算 Weighted UniFrac...\\n\")\n  wunifrac_dist <- getDissimilarity(\n    tse_for_unifrac,\n    method = \"unifrac\",\n    weighted = TRUE,\n    assay.type = \"counts\"\n  )\n  cat(\"Weighted UniFrac 完成!\\n\")\n\n  cat(\"计算 Unweighted UniFrac...\\n\")\n  uwunifrac_dist <- getDissimilarity(\n    tse_for_unifrac,\n    method = \"unifrac\",\n    weighted = FALSE,\n    assay.type = \"counts\"\n  )\n  cat(\"Unweighted UniFrac 完成!\\n\")\n\n  unifrac_success <- TRUE\n  cat(\"\\nUniFrac 计算成功!\\n\")\n\n}, error = function(e) {\n  cat(\"\\nUniFrac 计算失败!\\n\")\n  cat(\"错误信息:\", conditionMessage(e), \"\\n\")\n  cat(\"\\n调试信息:\\n\")\n  cat(\"请检查树的边长是否已正确修复\\n\")\n})\n#> 使用 465 个共同 OTU 进行 UniFrac 计算\n#> \n#> 计算 Weighted UniFrac...\n#> Weighted UniFrac 完成!\n#> 计算 Unweighted UniFrac...\n#> Unweighted UniFrac 完成!\n#> \n#> UniFrac 计算成功!\n\n# 如果失败，创建占位变量\nif (!unifrac_success) {\n  p_pcoa_wunifrac <- NULL\n  p_pcoa_uwunifrac <- NULL\n  permanova_wunifrac <- data.frame(`Pr(>F)` = NA, check.names = FALSE)\n  permanova_uwunifrac <- data.frame(`Pr(>F)` = NA, check.names = FALSE)\n}\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# Step 3: UniFrac PCoA 可视化\n# ==============================================================================\ncat(\"\\n=== UniFrac PCoA 可视化 ===\\n\")\n#> \n#> === UniFrac PCoA 可视化 ===\n\n# Weighted UniFrac PCoA\npcoa_wuf <- cmdscale(wunifrac_dist, k = min(ncol(tse_singlem_corepair) - 1, 10), eig = TRUE)\nreducedDim(tse_singlem_corepair, \"PCoA_wUniFrac\") <- pcoa_wuf$points\n\neig_wuf <- pcoa_wuf$eig\nrel_eig_wuf <- eig_wuf / sum(eig_wuf[eig_wuf > 0])\n\np_pcoa_wunifrac <- plotReducedDim(tse_singlem_corepair, \"PCoA_wUniFrac\", colour_by = \"treatment_group\") +\n  theme_bw() +\n  labs(title = \"SingleM: PCoA (Weighted UniFrac)\",\n       subtitle = \"进化谱系加权距离 - 识别株系级遗传偏移\",\n       x = paste0(\"PCoA 1 (\", round(100 * rel_eig_wuf[1], 1), \"%)\"),\n       y = paste0(\"PCoA 2 (\", round(100 * rel_eig_wuf[2], 1), \"%)\"))\np_pcoa_wunifrac\n```\n\n::: {.cell-output-display}\n![](03_singlem_diversity_analysis_files/figure-html/singlem-beta-unifrac-viz-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\n\nggsave(here::here(\"data\", params$name, \"09_beta_pcoa_wunifrac_singlem.png\"),\n       p_pcoa_wunifrac, width = 8, height = 6, dpi = 300)\n\n# Unweighted UniFrac PCoA\npcoa_uwuf <- cmdscale(uwunifrac_dist, k = min(ncol(tse_singlem_corepair) - 1, 10), eig = TRUE)\nreducedDim(tse_singlem_corepair, \"PCoA_uwUniFrac\") <- pcoa_uwuf$points\n\neig_uwuf <- pcoa_uwuf$eig\nrel_eig_uwuf <- eig_uwuf / sum(eig_uwuf[eig_uwuf > 0])\n\np_pcoa_uwunifrac <- plotReducedDim(tse_singlem_corepair, \"PCoA_uwUniFrac\", colour_by = \"treatment_group\") +\n  theme_bw() +\n  labs(title = \"SingleM: PCoA (Unweighted UniFrac)\",\n       subtitle = \"进化谱系存在/缺失距离 - 识别稀有株系差异\",\n       x = paste0(\"PCoA 1 (\", round(100 * rel_eig_uwuf[1], 1), \"%)\"),\n       y = paste0(\"PCoA 2 (\", round(100 * rel_eig_uwuf[2], 1), \"%)\"))\np_pcoa_uwunifrac\n```\n\n::: {.cell-output-display}\n![](03_singlem_diversity_analysis_files/figure-html/singlem-beta-unifrac-viz-2.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\n\nggsave(here::here(\"data\", params$name, \"10_beta_pcoa_uwunifrac_singlem.png\"),\n       p_pcoa_uwunifrac, width = 8, height = 6, dpi = 300)\n\n# ==============================================================================\n# Step 4: PERMANOVA 检验 (UniFrac)\n# ==============================================================================\npermanova_wunifrac <- vegan::adonis2(\n  wunifrac_dist ~ treatment_group,\n  data = data.frame(colData(tse_singlem_corepair)),\n  permutations = 999\n)\n\npermanova_uwunifrac <- vegan::adonis2(\n  uwunifrac_dist ~ treatment_group,\n  data = data.frame(colData(tse_singlem_corepair)),\n  permutations = 999\n)\n\ncat(\"\\n=== PERMANOVA (Weighted UniFrac) ===\\n\")\n#> \n#> === PERMANOVA (Weighted UniFrac) ===\nprint(permanova_wunifrac)\n#> Permutation test for adonis under reduced model\n#> Permutation: free\n#> Number of permutations: 999\n#> \n#> vegan::adonis2(formula = wunifrac_dist ~ treatment_group, data = data.frame(colData(tse_singlem_corepair)), permutations = 999)\n#>          Df SumOfSqs      R2      F Pr(>F)  \n#> Model     1   8.4835 0.34596 3.7026  0.029 *\n#> Residual  7  16.0383 0.65404                \n#> Total     8  24.5218 1.00000                \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\ncat(\"\\n=== PERMANOVA (Unweighted UniFrac) ===\\n\")\n#> \n#> === PERMANOVA (Unweighted UniFrac) ===\nprint(permanova_uwunifrac)\n#> Permutation test for adonis under reduced model\n#> Permutation: free\n#> Number of permutations: 999\n#> \n#> vegan::adonis2(formula = uwunifrac_dist ~ treatment_group, data = data.frame(colData(tse_singlem_corepair)), permutations = 999)\n#>          Df SumOfSqs      R2     F Pr(>F)   \n#> Model     1  0.16273 0.20028 1.753  0.008 **\n#> Residual  7  0.64979 0.79972                \n#> Total     8  0.81252 1.00000                \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nwrite.csv(as.data.frame(permanova_wunifrac),\n          here::here(\"data\", params$name, \"11_permanova_wunifrac_singlem.csv\"), row.names = TRUE)\nwrite.csv(as.data.frame(permanova_uwunifrac),\n          here::here(\"data\", params$name, \"12_permanova_uwunifrac_singlem.csv\"), row.names = TRUE)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# Step 5: Beta 多样性结果汇总图\n# ==============================================================================\nif (unifrac_success && !is.null(p_pcoa_wunifrac)) {\n  p_beta_combined <- (p_pcoa_bray | p_pcoa_wunifrac | p_pcoa_uwunifrac) +\n    plot_annotation(\n      title = \"SingleM Beta Diversity: ApcMUT_HpWT vs ApcMUT_HpKO\",\n      subtitle = \"Bray-Curtis (丰度) vs UniFrac (进化谱系) 距离比较\"\n    )\n\n  ggsave(here::here(\"data\", params$name, \"13_beta_diversity_combined_singlem.png\"),\n         p_beta_combined, width = 18, height = 6, dpi = 300)\n} else {\n  # 仅显示 Bray-Curtis\n  p_beta_combined <- p_pcoa_bray +\n    plot_annotation(\n      title = \"SingleM Beta Diversity: ApcMUT_HpWT vs ApcMUT_HpKO\",\n      subtitle = \"Bray-Curtis distance (UniFrac 计算失败)\"\n    )\n\n  ggsave(here::here(\"data\", params$name, \"13_beta_diversity_combined_singlem.png\"),\n         p_beta_combined, width = 8, height = 6, dpi = 300)\n}\n\np_beta_combined\n```\n\n::: {.cell-output-display}\n![](03_singlem_diversity_analysis_files/figure-html/singlem-beta-combined-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n## 1.6 差异丰度分析 (DAA)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# 使用 ANCOM-BC 进行差异丰度分析\n# ==============================================================================\n# 准备数据\ntse_daa <- tse_singlem_corepair\n\n# 运行 ANCOM-BC\nancombc_result <- ancombc2(\n  data = tse_daa,\n  assay_name = \"counts\",\n  fix_formula = \"treatment_group\",\n  p_adj_method = \"BH\",\n  prv_cut = 0.1,\n  lib_cut = 0,\n  group = \"treatment_group\",\n  struc_zero = TRUE,\n  neg_lb = TRUE,\n  alpha = 0.05,\n  global = FALSE\n)\n\n# 提取结果\nancombc_res <- ancombc_result$res\n\n# 查看结果结构和列名\ncat(\"ANCOM-BC 结果列名:\\n\")\n#> ANCOM-BC 结果列名:\nprint(colnames(ancombc_res))\n#>  [1] \"taxon\"                                 \n#>  [2] \"lfc_(Intercept)\"                       \n#>  [3] \"lfc_treatment_groupApcMUT_HpWT\"        \n#>  [4] \"se_(Intercept)\"                        \n#>  [5] \"se_treatment_groupApcMUT_HpWT\"         \n#>  [6] \"W_(Intercept)\"                         \n#>  [7] \"W_treatment_groupApcMUT_HpWT\"          \n#>  [8] \"p_(Intercept)\"                         \n#>  [9] \"p_treatment_groupApcMUT_HpWT\"          \n#> [10] \"q_(Intercept)\"                         \n#> [11] \"q_treatment_groupApcMUT_HpWT\"          \n#> [12] \"diff_(Intercept)\"                      \n#> [13] \"diff_treatment_groupApcMUT_HpWT\"       \n#> [14] \"passed_ss_(Intercept)\"                 \n#> [15] \"passed_ss_treatment_groupApcMUT_HpWT\"  \n#> [16] \"diff_robust_(Intercept)\"               \n#> [17] \"diff_robust_treatment_groupApcMUT_HpWT\"\n\n# 动态识别 lfc 和 q 值列名（适应不同的因子水平）\nlfc_col <- grep(\"^lfc_treatment_group\", colnames(ancombc_res), value = TRUE)[1]\nq_col <- grep(\"^q_treatment_group\", colnames(ancombc_res), value = TRUE)[1]\n\ncat(\"使用的列名:\\n\")\n#> 使用的列名:\ncat(\"  LFC 列:\", lfc_col, \"\\n\")\n#>   LFC 列: lfc_treatment_groupApcMUT_HpWT\ncat(\"  Q 值列:\", q_col, \"\\n\")\n#>   Q 值列: q_treatment_groupApcMUT_HpWT\n\n# 添加分类信息\nancombc_res <- ancombc_res |>\n  dplyr::left_join(\n    rowData(tse_daa) |> as.data.frame() |> rownames_to_column(\"taxon\"),\n    by = \"taxon\"\n  )\n\n# 按 q 值排序并取 Top 20\nancombc_top20 <- ancombc_res |>\n  arrange(.data[[q_col]]) |>\n  head(20)\n\ncat(\"\\n=== ANCOM-BC Top 20 差异 OTU ===\\n\")\n#> \n#> === ANCOM-BC Top 20 差异 OTU ===\nprint(ancombc_top20 |> dplyr::select(taxon, Phylum, Family, all_of(c(lfc_col, q_col))))\n#>      taxon         Phylum            Family lfc_treatment_groupApcMUT_HpWT\n#> 1  OTU_233      Bacillota           UBA3700                      2.7513599\n#> 2  OTU_198      Bacillota   Lachnospiraceae                      1.4301972\n#> 3  OTU_115      Bacillota  Oscillospiraceae                      1.2553130\n#> 4  OTU_100      Bacillota  Oscillospiraceae                      1.3275608\n#> 5  OTU_285   Bacteroidota     Rikenellaceae                      1.3370584\n#> 6  OTU_544   Bacteroidota  Chitinophagaceae                      2.4980391\n#> 7  OTU_297  Chrysiogenota  Mucispirillaceae                      2.0999019\n#> 8  OTU_354 Actinomycetota Microbacteriaceae                     -1.7792945\n#> 9   OTU_87 Actinomycetota   Eggerthellaceae                     -0.9492528\n#> 10  OTU_18 Actinomycetota              <NA>                      1.1544624\n#> 11 OTU_155      Bacillota   Lachnospiraceae                      1.1654897\n#> 12 OTU_160      Bacillota   Lachnospiraceae                      1.2555437\n#> 13  OTU_43      Bacillota  Oscillospiraceae                      1.3409735\n#> 14  OTU_40      Bacillota  Oscillospiraceae                      0.7991612\n#> 15 OTU_444      Bacillota   Ruminococcaceae                      2.1235990\n#> 16   OTU_6 Actinomycetota              <NA>                     -1.1312547\n#> 17 OTU_129      Bacillota  Oscillospiraceae                      0.8999184\n#> 18 OTU_464      Bacillota   Lachnospiraceae                      1.2415679\n#> 19 OTU_169      Bacillota   Lachnospiraceae                     -0.8794668\n#> 20 OTU_164      Bacillota   Lachnospiraceae                      0.9788334\n#>    q_treatment_groupApcMUT_HpWT\n#> 1                     0.1933793\n#> 2                     0.1933793\n#> 3                     0.1933793\n#> 4                     0.1933793\n#> 5                     0.1933793\n#> 6                     0.1933793\n#> 7                     0.1933793\n#> 8                     0.2265670\n#> 9                     0.2265670\n#> 10                    0.2265670\n#> 11                    0.2265670\n#> 12                    0.2265670\n#> 13                    0.2265670\n#> 14                    0.2265670\n#> 15                    0.2265670\n#> 16                    0.2605927\n#> 17                    0.2605927\n#> 18                    0.3046710\n#> 19                    0.3296443\n#> 20                    0.3296443\n\n# 保存结果\nwrite.csv(\n  ancombc_res,\n  file = here::here(\"data\", params$name, \"14_daa_ancombc_singlem_full.csv\"),\n  row.names = FALSE\n)\n\nwrite.csv(\n  ancombc_top20,\n  file = here::here(\"data\", params$name, \"15_daa_ancombc_singlem_top20.csv\"),\n  row.names = FALSE\n)\n\n# ==============================================================================\n# 火山图\n# ==============================================================================\np_volcano <- ggplot(ancombc_res, aes(\n  x = .data[[lfc_col]],\n  y = -log10(.data[[q_col]])\n)) +\n  geom_point(aes(color = .data[[q_col]] < 0.05), alpha = 0.6) +\n  scale_color_manual(values = c(\"grey50\", \"red\"), labels = c(\"NS\", \"q < 0.05\")) +\n  geom_hline(yintercept = -log10(0.05), linetype = \"dashed\", color = \"blue\") +\n  theme_bw() +\n  labs(\n    title = \"SingleM: Differential Abundance (ANCOM-BC)\",\n    subtitle = \"ApcMUT_HpWT vs ApcMUT_HpKO\",\n    x = \"Log2 Fold Change\",\n    y = \"-log10(q-value)\",\n    color = \"Significance\"\n  )\np_volcano\n```\n\n::: {.cell-output-display}\n![](03_singlem_diversity_analysis_files/figure-html/singlem-daa-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\n\nggsave(\n  filename = here::here(\"data\", params$name, \"16_volcano_daa_singlem.png\"),\n  plot = p_volcano, width = 10, height = 8, dpi = 300\n)\n```\n:::\n\n\n\n# Part 2: Lyrebird噬菌体分析 {#sec-part2}\n\nLyrebird 是 SingleM 框架内专门用于分析 dsDNA 噬菌体（Caudoviricetes）的模块。\n\n## 2.1 Lyrebird 数据导入与 TSE 构建\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# Step 1: 定义数据路径\n# ==============================================================================\nlyrebird_data_path <- here::here(\n  \"data\", \"00-raw\", \"d03_singlem_diversity_analysis\", \"pc047-rst_lyrebird\"\n)\n\n# ==============================================================================\n# Step 2: 读取 OTU 丰度矩阵\n# ==============================================================================\nlyrebird_abundance <- read_tsv(\n  file.path(lyrebird_data_path, \"pc047-lyrebird_OTU_abundance.tsv\"),\n  show_col_types = FALSE\n) |>\n  column_to_rownames(\"otu_id\") |>\n  as.matrix()\n\n# 将百分比转换为比例\nlyrebird_abundance <- lyrebird_abundance / 100\n\ncat(\"Lyrebird OTU 矩阵维度:\", dim(lyrebird_abundance), \"\\n\")\n#> Lyrebird OTU 矩阵维度: 1443 33\n\n# ==============================================================================\n# Step 3: 读取 OTU 分类信息\n# ==============================================================================\nlyrebird_taxonomy <- read_tsv(\n  file.path(lyrebird_data_path, \"pc047-lyrebird_OTU_taxonomy.tsv\"),\n  show_col_types = FALSE\n) |>\n  column_to_rownames(\"otu_id\") |>\n  DataFrame()\n\ncat(\"Lyrebird 分类层级:\", colnames(lyrebird_taxonomy), \"\\n\")\n#> Lyrebird 分类层级: Root Domain Phylum Class Order Family Genus Species\n\n# ==============================================================================\n# Step 4: 读取系统发育树\n# ==============================================================================\nlyrebird_tree <- ape::read.tree(\n  file.path(lyrebird_data_path, \"pc047-lyrebird_OTU_tree.nwk\")\n)\n\ncat(\"Lyrebird 系统发育树 tip 数:\", length(lyrebird_tree$tip.label), \"\\n\")\n#> Lyrebird 系统发育树 tip 数: 1443\n\n# ==============================================================================\n# Step 5: 构建 TSE 对象\n# ==============================================================================\ncommon_otus_lyrebird <- base::intersect(rownames(lyrebird_abundance), rownames(lyrebird_taxonomy))\ncommon_otus_lyrebird <- base::intersect(common_otus_lyrebird, lyrebird_tree$tip.label)\n\ncat(\"Lyrebird 共同 OTU 数:\", length(common_otus_lyrebird), \"\\n\")\n#> Lyrebird 共同 OTU 数: 1443\n\nlyrebird_abundance <- lyrebird_abundance[common_otus_lyrebird, ]\nlyrebird_taxonomy <- lyrebird_taxonomy[common_otus_lyrebird, ]\nlyrebird_tree <- ape::keep.tip(lyrebird_tree, common_otus_lyrebird)\n\ntse_lyrebird <- TreeSummarizedExperiment(\n  assays = list(\n    relabundance = lyrebird_abundance,\n    counts = round(lyrebird_abundance * 10000)\n  ),\n  rowData = lyrebird_taxonomy,\n  rowTree = lyrebird_tree\n)\n\n# 绑定元数据\ncommon_samples_lyrebird <- base::intersect(colnames(tse_lyrebird), rownames(metadata))\ntse_lyrebird <- tse_lyrebird[, common_samples_lyrebird]\ncolData(tse_lyrebird) <- DataFrame(metadata[common_samples_lyrebird, ])\n\n# 创建 Caecum 子集\ntse_lyrebird_ca <- tse_lyrebird[, tse_lyrebird$source_organ == \"caecum\"]\n\ncat(\"Lyrebird Caecum 样本数:\", ncol(tse_lyrebird_ca), \"\\n\")\n#> Lyrebird Caecum 样本数: 29\n\ntse_lyrebird_ca\n#> class: TreeSummarizedExperiment \n#> dim: 1443 29 \n#> metadata(0):\n#> assays(2): relabundance counts\n#> rownames(1443): OTU_1 OTU_2 ... OTU_1442 OTU_1443\n#> rowData names(8): Root Domain ... Genus Species\n#> colnames(29): ca01 ca02 ... ca29 ca30\n#> colData names(11): mouse_id genotype ... path_r1 path_r2\n#> reducedDimNames(0):\n#> mainExpName: NULL\n#> altExpNames(0):\n#> rowLinks: a LinkDataFrame (1443 rows)\n#> rowTree: 1 phylo tree(s) (1443 leaves)\n#> colLinks: NULL\n#> colTree: NULL\n```\n:::\n\n\n## 2.2 Lyrebird 数据清洗\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# 1. 移除异常样本 (与 SingleM 保持一致)\n# ==============================================================================\nif (\"ca08\" %in% colnames(tse_lyrebird_ca)) {\n  tse_lyrebird_ca <- tse_lyrebird_ca[, colnames(tse_lyrebird_ca) != \"ca08\"]\n}\n\n# ==============================================================================\n# 2. Prevalence 过滤\n# ==============================================================================\ntse_lyrebird_ca <- addPrevalence(\n  tse_lyrebird_ca,\n  assay.type = \"relabundance\",\n  detection = 0,\n  as.relative = FALSE\n)\n\ncat(\"Lyrebird 过滤前 OTU 数:\", nrow(tse_lyrebird_ca), \"\\n\")\n#> Lyrebird 过滤前 OTU 数: 1443\ntse_lyrebird_ca <- subsetByPrevalent(tse_lyrebird_ca, prevalence = 0.1)\ncat(\"Lyrebird 过滤后 OTU 数:\", nrow(tse_lyrebird_ca), \"\\n\")\n#> Lyrebird 过滤后 OTU 数: 878\n\n# 保存清洗后的数据\ntse_lyrebird_ca_cleaned <- tse_lyrebird_ca\nsaveRDS(\n  tse_lyrebird_ca_cleaned,\n  file = here::here(\"data\", params$name, \"tse_lyrebird_ca_cleaned.rds\")\n)\n```\n:::\n\n\n## 2.3 Lyrebird 群落组成与多样性\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# 1. 噬菌体组成图\n# ==============================================================================\ntop_phages <- getTop(tse_lyrebird_ca_cleaned, top = 10, assay.type = \"relabundance\")\n\ntse_lyrebird_plot <- tse_lyrebird_ca_cleaned\nrowData(tse_lyrebird_plot)$Phage_Top10 <- ifelse(\n  rownames(tse_lyrebird_plot) %in% top_phages,\n  paste0(rownames(tse_lyrebird_plot), \" (\", rowData(tse_lyrebird_plot)$Family, \")\"),\n  \"Other\"\n)\n\ntse_lyrebird_plot_agg <- agglomerateByVariable(tse_lyrebird_plot, by = \"rows\", f = \"Phage_Top10\")\n\np_lyrebird_comp <- plotAbundance(\n  tse_lyrebird_plot_agg,\n  assay.type = \"relabundance\",\n  order.row.by = \"abund\"\n) +\n  labs(\n    title = \"Lyrebird: Top 10 Phage OTU Composition (Caecum)\",\n    subtitle = \"dsDNA Phage (Caudoviricetes) communities\"\n  ) +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8))\n\np_lyrebird_comp\n```\n\n::: {.cell-output-display}\n![](03_singlem_diversity_analysis_files/figure-html/lyrebird-diversity-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\n\nggsave(\n  filename = here::here(\"data\", params$name, \"17_composition_top10_lyrebird.png\"),\n  plot = p_lyrebird_comp, width = 14, height = 8, dpi = 300\n)\n\n# ==============================================================================\n# 2. Alpha 多样性\n# ==============================================================================\ntse_lyrebird_ca_cleaned <- addAlpha(\n  tse_lyrebird_ca_cleaned,\n  assay.type = \"counts\",\n  index = c(\"shannon\", \"observed\"),\n  name = c(\"shannon_index\", \"observed_richness\")\n)\n\n# 提取核心比较组\ntse_lyrebird_corepair <- tse_lyrebird_ca_cleaned[\n  , tse_lyrebird_ca_cleaned$treatment_group %in% c(\"ApcMUT_HpWT\", \"ApcMUT_HpKO\")\n]\ntse_lyrebird_corepair$treatment_group <- factor(tse_lyrebird_corepair$treatment_group)\n\n# Wilcoxon 检验\nwilcox_lyrebird_shannon <- wilcox.test(\n  shannon_index ~ treatment_group,\n  data = colData(tse_lyrebird_corepair)\n)\ncat(\"\\nLyrebird Shannon Wilcoxon P 值:\", round(wilcox_lyrebird_shannon$p.value, 4), \"\\n\")\n#> \n#> Lyrebird Shannon Wilcoxon P 值: 0.0317\n\n# 可视化\np_lyrebird_shannon <- plot_alpha(tse_lyrebird_corepair, \"shannon_index\", \"Lyrebird: Shannon Diversity\")\np_lyrebird_observed <- plot_alpha(tse_lyrebird_corepair, \"observed_richness\", \"Lyrebird: Observed Phage OTUs\")\n\np_lyrebird_alpha <- p_lyrebird_shannon + p_lyrebird_observed +\n  plot_annotation(title = \"Lyrebird (Phage) Alpha Diversity\")\np_lyrebird_alpha\n```\n\n::: {.cell-output-display}\n![](03_singlem_diversity_analysis_files/figure-html/lyrebird-diversity-2.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\n\nggsave(\n  filename = here::here(\"data\", params$name, \"18_alpha_diversity_lyrebird.png\"),\n  plot = p_lyrebird_alpha, width = 12, height = 6, dpi = 300\n)\n\n# ==============================================================================\n# 3. Beta 多样性 (Bray-Curtis)\n# ==============================================================================\ntse_lyrebird_corepair <- runMDS(\n  tse_lyrebird_corepair,\n  FUN = vegan::vegdist,\n  method = \"bray\",\n  assay.type = \"relabundance\",\n  name = \"PCoA_Bray\"\n)\n\neig_lyrebird_bray <- attr(reducedDim(tse_lyrebird_corepair, \"PCoA_Bray\"), \"eig\")\nrel_eig_lyrebird_bray <- eig_lyrebird_bray / sum(eig_lyrebird_bray[eig_lyrebird_bray > 0])\n\np_lyrebird_pcoa <- plotReducedDim(\n  tse_lyrebird_corepair,\n  \"PCoA_Bray\",\n  colour_by = \"treatment_group\"\n) +\n  theme_bw() +\n  labs(\n    title = \"Lyrebird: PCoA (Bray-Curtis)\",\n    subtitle = \"Phage community structure\",\n    x = paste0(\"PCoA 1 (\", round(100 * rel_eig_lyrebird_bray[1], 1), \"%)\"),\n    y = paste0(\"PCoA 2 (\", round(100 * rel_eig_lyrebird_bray[2], 1), \"%)\")\n  )\np_lyrebird_pcoa\n```\n\n::: {.cell-output-display}\n![](03_singlem_diversity_analysis_files/figure-html/lyrebird-diversity-3.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\n\nggsave(\n  filename = here::here(\"data\", params$name, \"19_beta_pcoa_bray_lyrebird.png\"),\n  plot = p_lyrebird_pcoa, width = 8, height = 6, dpi = 300\n)\n\n# PERMANOVA\npermanova_lyrebird <- getPERMANOVA(\n  tse_lyrebird_corepair,\n  assay.type = \"relabundance\",\n  formula = x ~ treatment_group\n)\n\ncat(\"\\n=== Lyrebird PERMANOVA (Bray-Curtis) ===\\n\")\n#> \n#> === Lyrebird PERMANOVA (Bray-Curtis) ===\nprint(permanova_lyrebird$permanova)\n#> Permutation test for adonis under reduced model\n#> Marginal effects of terms\n#> Permutation: free\n#> Number of permutations: 999\n#> \n#> adonis2(formula = formula, data = data, method = ..1, by = by, na.action = na.action)\n#>                 Df SumOfSqs      R2      F Pr(>F)  \n#> treatment_group  1  0.27883 0.26715 2.5518  0.057 .\n#> Residual         7  0.76488 0.73285                \n#> Total            8  1.04371 1.00000                \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nwrite.csv(\n  permanova_lyrebird$permanova,\n  file = here::here(\"data\", params$name, \"20_permanova_bray_lyrebird.csv\"),\n  row.names = TRUE\n)\n```\n:::\n\n\n## 2.4 Lyrebird UniFrac 分析\n\n借鉴 Part 1 的经验，Lyrebird 的系统发育树也可能存在边长问题，需要先诊断和修复。\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# Step 1: 诊断 Lyrebird 树和 OTU 矩阵的匹配情况\n# ==============================================================================\ncat(\"=== Lyrebird UniFrac 计算前诊断 ===\\n\\n\")\n#> === Lyrebird UniFrac 计算前诊断 ===\n\n# 获取树和 OTU 信息\ntree_lyrebird <- rowTree(tse_lyrebird_corepair)\notu_names_lyrebird <- rownames(tse_lyrebird_corepair)\ntree_tips_lyrebird <- tree_lyrebird$tip.label\n\ncat(\"OTU 矩阵中的 OTU 数量:\", length(otu_names_lyrebird), \"\\n\")\n#> OTU 矩阵中的 OTU 数量: 878\ncat(\"系统发育树的 tip 数量:\", length(tree_tips_lyrebird), \"\\n\")\n#> 系统发育树的 tip 数量: 878\n\n# 检查匹配情况\nin_both_lyrebird <- base::intersect(otu_names_lyrebird, tree_tips_lyrebird)\ncat(\"两者共有的 OTU:\", length(in_both_lyrebird), \"\\n\")\n#> 两者共有的 OTU: 878\n\n# 检查树结构\ncat(\"\\n树结构检查:\\n\")\n#> \n#> 树结构检查:\ncat(\"  - 是否为二叉树:\", ape::is.binary(tree_lyrebird), \"\\n\")\n#>   - 是否为二叉树: FALSE\ncat(\"  - 是否有根:\", ape::is.rooted(tree_lyrebird), \"\\n\")\n#>   - 是否有根: FALSE\n\n# 检查边长\nif (!is.null(tree_lyrebird$edge.length) && length(tree_lyrebird$edge.length) > 0) {\n  valid_edges_lyrebird <- tree_lyrebird$edge.length[is.finite(tree_lyrebird$edge.length)]\n  if (length(valid_edges_lyrebird) > 0) {\n    cat(\"  - 有效边长范围:\", range(valid_edges_lyrebird), \"\\n\")\n  } else {\n    cat(\"  - 有效边长范围: 无有效边长!\\n\")\n  }\n  cat(\"  - 总边数:\", length(tree_lyrebird$edge.length), \"\\n\")\n  cat(\"  - NA 边长数量:\", sum(is.na(tree_lyrebird$edge.length)), \"\\n\")\n  cat(\"  - Inf 边长数量:\", sum(is.infinite(tree_lyrebird$edge.length)), \"\\n\")\n  cat(\"  - 负数边长数量:\", sum(tree_lyrebird$edge.length < 0, na.rm = TRUE), \"\\n\")\n} else {\n  cat(\"  - 边长信息: 树没有边长信息!\\n\")\n}\n#>   - 边长信息: 树没有边长信息!\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# Step 2: 修复 Lyrebird 树的边长问题\n# ==============================================================================\ncat(\"\\n=== 修复 Lyrebird 树的边长 ===\\n\")\n#> \n#> === 修复 Lyrebird 树的边长 ===\n\ntree_lyrebird_original <- rowTree(tse_lyrebird_corepair)\ntree_lyrebird_fixed <- tree_lyrebird_original\n\nif (is.null(tree_lyrebird_fixed$edge.length) || length(tree_lyrebird_fixed$edge.length) == 0) {\n  cat(\"树没有边长信息，创建默认边长...\\n\")\n  tree_lyrebird_fixed$edge.length <- rep(1, nrow(tree_lyrebird_fixed$edge))\n} else {\n  # 统计问题边长\n  n_na <- sum(is.na(tree_lyrebird_fixed$edge.length))\n  n_inf <- sum(is.infinite(tree_lyrebird_fixed$edge.length))\n  n_neg <- sum(tree_lyrebird_fixed$edge.length < 0, na.rm = TRUE)\n  n_zero <- sum(tree_lyrebird_fixed$edge.length == 0, na.rm = TRUE)\n\n  cat(\"发现问题边长:\\n\")\n  cat(\"  - NA:\", n_na, \"\\n\")\n  cat(\"  - Inf:\", n_inf, \"\\n\")\n  cat(\"  - 负数:\", n_neg, \"\\n\")\n  cat(\"  - 零:\", n_zero, \"\\n\")\n\n  # 修复异常值\n  small_value <- 1e-6\n  tree_lyrebird_fixed$edge.length[is.na(tree_lyrebird_fixed$edge.length)] <- small_value\n  tree_lyrebird_fixed$edge.length[is.infinite(tree_lyrebird_fixed$edge.length)] <- small_value\n  tree_lyrebird_fixed$edge.length[tree_lyrebird_fixed$edge.length < 0] <- small_value\n  tree_lyrebird_fixed$edge.length[tree_lyrebird_fixed$edge.length == 0] <- small_value\n\n  cat(\"\\n修复后边长范围:\", range(tree_lyrebird_fixed$edge.length), \"\\n\")\n}\n#> 树没有边长信息，创建默认边长...\n\nrowTree(tse_lyrebird_corepair) <- tree_lyrebird_fixed\ncat(\"Lyrebird 树修复完成!\\n\")\n#> Lyrebird 树修复完成!\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# Step 3: 使用 mia 计算 Lyrebird UniFrac\n# ==============================================================================\ncat(\"\\n=== 使用 mia 计算 Lyrebird UniFrac 距离 ===\\n\")\n#> \n#> === 使用 mia 计算 Lyrebird UniFrac 距离 ===\n\nlyrebird_unifrac_success <- FALSE\n\ntryCatch({\n  tree_for_unifrac_lyrebird <- rowTree(tse_lyrebird_corepair)\n  common_taxa_lyrebird <- base::intersect(rownames(tse_lyrebird_corepair), tree_for_unifrac_lyrebird$tip.label)\n  cat(\"使用\", length(common_taxa_lyrebird), \"个共同 OTU 进行 UniFrac 计算\\n\")\n\n  tse_for_unifrac_lyrebird <- tse_lyrebird_corepair[common_taxa_lyrebird, ]\n  tree_pruned_lyrebird <- ape::keep.tip(tree_for_unifrac_lyrebird, common_taxa_lyrebird)\n  rowTree(tse_for_unifrac_lyrebird) <- tree_pruned_lyrebird\n\n  cat(\"\\n计算 Weighted UniFrac...\\n\")\n  wunifrac_dist_lyrebird <- getDissimilarity(\n    tse_for_unifrac_lyrebird,\n    method = \"unifrac\",\n    weighted = TRUE,\n    assay.type = \"counts\"\n  )\n  cat(\"Weighted UniFrac 完成!\\n\")\n\n  cat(\"计算 Unweighted UniFrac...\\n\")\n  uwunifrac_dist_lyrebird <- getDissimilarity(\n    tse_for_unifrac_lyrebird,\n    method = \"unifrac\",\n    weighted = FALSE,\n    assay.type = \"counts\"\n  )\n  cat(\"Unweighted UniFrac 完成!\\n\")\n\n  lyrebird_unifrac_success <- TRUE\n  cat(\"\\nLyrebird UniFrac 计算成功!\\n\")\n\n}, error = function(e) {\n  cat(\"\\nLyrebird UniFrac 计算失败!\\n\")\n  cat(\"错误信息:\", conditionMessage(e), \"\\n\")\n})\n#> 使用 878 个共同 OTU 进行 UniFrac 计算\n#> \n#> 计算 Weighted UniFrac...\n#> Weighted UniFrac 完成!\n#> 计算 Unweighted UniFrac...\n#> Unweighted UniFrac 完成!\n#> \n#> Lyrebird UniFrac 计算成功!\n\nif (!lyrebird_unifrac_success) {\n  p_pcoa_wunifrac_lyrebird <- NULL\n  p_pcoa_uwunifrac_lyrebird <- NULL\n  permanova_wunifrac_lyrebird <- data.frame(`Pr(>F)` = NA, check.names = FALSE)\n  permanova_uwunifrac_lyrebird <- data.frame(`Pr(>F)` = NA, check.names = FALSE)\n}\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# Step 4: Lyrebird UniFrac PCoA 可视化\n# ==============================================================================\n\n# Weighted UniFrac PCoA\npcoa_wunifrac_lyrebird <- cmdscale(wunifrac_dist_lyrebird, eig = TRUE, k = 2)\neig_wunifrac_lyrebird <- pcoa_wunifrac_lyrebird$eig\nrel_eig_wunifrac_lyrebird <- eig_wunifrac_lyrebird / sum(eig_wunifrac_lyrebird[eig_wunifrac_lyrebird > 0])\n\npcoa_df_wunifrac_lyrebird <- data.frame(\n  PCoA1 = pcoa_wunifrac_lyrebird$points[, 1],\n  PCoA2 = pcoa_wunifrac_lyrebird$points[, 2],\n  treatment_group = colData(tse_lyrebird_corepair)$treatment_group\n)\n\np_pcoa_wunifrac_lyrebird <- ggplot(pcoa_df_wunifrac_lyrebird, aes(x = PCoA1, y = PCoA2, color = treatment_group)) +\n  geom_point(size = 3) +\n  theme_bw() +\n  labs(\n    title = \"Lyrebird: PCoA (Weighted UniFrac)\",\n    x = paste0(\"PCoA 1 (\", round(100 * rel_eig_wunifrac_lyrebird[1], 1), \"%)\"),\n    y = paste0(\"PCoA 2 (\", round(100 * rel_eig_wunifrac_lyrebird[2], 1), \"%)\")\n  )\n\n# Unweighted UniFrac PCoA\npcoa_uwunifrac_lyrebird <- cmdscale(uwunifrac_dist_lyrebird, eig = TRUE, k = 2)\neig_uwunifrac_lyrebird <- pcoa_uwunifrac_lyrebird$eig\nrel_eig_uwunifrac_lyrebird <- eig_uwunifrac_lyrebird / sum(eig_uwunifrac_lyrebird[eig_uwunifrac_lyrebird > 0])\n\npcoa_df_uwunifrac_lyrebird <- data.frame(\n  PCoA1 = pcoa_uwunifrac_lyrebird$points[, 1],\n  PCoA2 = pcoa_uwunifrac_lyrebird$points[, 2],\n  treatment_group = colData(tse_lyrebird_corepair)$treatment_group\n)\n\np_pcoa_uwunifrac_lyrebird <- ggplot(pcoa_df_uwunifrac_lyrebird, aes(x = PCoA1, y = PCoA2, color = treatment_group)) +\n  geom_point(size = 3) +\n  theme_bw() +\n  labs(\n    title = \"Lyrebird: PCoA (Unweighted UniFrac)\",\n    x = paste0(\"PCoA 1 (\", round(100 * rel_eig_uwunifrac_lyrebird[1], 1), \"%)\"),\n    y = paste0(\"PCoA 2 (\", round(100 * rel_eig_uwunifrac_lyrebird[2], 1), \"%)\")\n  )\n\n# 组合图\np_lyrebird_unifrac_combined <- p_pcoa_wunifrac_lyrebird + p_pcoa_uwunifrac_lyrebird +\n  plot_annotation(title = \"Lyrebird (Phage) UniFrac Beta Diversity\")\np_lyrebird_unifrac_combined\n```\n\n::: {.cell-output-display}\n![](03_singlem_diversity_analysis_files/figure-html/lyrebird-unifrac-viz-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\n\nggsave(\n  filename = here::here(\"data\", params$name, \"21_beta_pcoa_unifrac_lyrebird.png\"),\n  plot = p_lyrebird_unifrac_combined, width = 14, height = 6, dpi = 300\n)\n\n# PERMANOVA\ncat(\"\\n=== Lyrebird PERMANOVA (Weighted UniFrac) ===\\n\")\n#> \n#> === Lyrebird PERMANOVA (Weighted UniFrac) ===\npermanova_wunifrac_lyrebird <- vegan::adonis2(\n  wunifrac_dist_lyrebird ~ treatment_group,\n  data = as.data.frame(colData(tse_lyrebird_corepair)),\n  permutations = 999\n)\nprint(permanova_wunifrac_lyrebird)\n#> Permutation test for adonis under reduced model\n#> Permutation: free\n#> Number of permutations: 999\n#> \n#> vegan::adonis2(formula = wunifrac_dist_lyrebird ~ treatment_group, data = as.data.frame(colData(tse_lyrebird_corepair)), permutations = 999)\n#>          Df SumOfSqs      R2      F Pr(>F)  \n#> Model     1   3.7073 0.26506 2.5246   0.05 *\n#> Residual  7  10.2796 0.73494                \n#> Total     8  13.9869 1.00000                \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\ncat(\"\\n=== Lyrebird PERMANOVA (Unweighted UniFrac) ===\\n\")\n#> \n#> === Lyrebird PERMANOVA (Unweighted UniFrac) ===\npermanova_uwunifrac_lyrebird <- vegan::adonis2(\n  uwunifrac_dist_lyrebird ~ treatment_group,\n  data = as.data.frame(colData(tse_lyrebird_corepair)),\n  permutations = 999\n)\nprint(permanova_uwunifrac_lyrebird)\n#> Permutation test for adonis under reduced model\n#> Permutation: free\n#> Number of permutations: 999\n#> \n#> vegan::adonis2(formula = uwunifrac_dist_lyrebird ~ treatment_group, data = as.data.frame(colData(tse_lyrebird_corepair)), permutations = 999)\n#>          Df SumOfSqs      R2      F Pr(>F)  \n#> Model     1  0.15278 0.21696 1.9395  0.043 *\n#> Residual  7  0.55143 0.78304                \n#> Total     8  0.70422 1.00000                \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nwrite.csv(\n  permanova_wunifrac_lyrebird,\n  file = here::here(\"data\", params$name, \"22_permanova_wunifrac_lyrebird.csv\"),\n  row.names = TRUE\n)\nwrite.csv(\n  permanova_uwunifrac_lyrebird,\n  file = here::here(\"data\", params$name, \"23_permanova_uwunifrac_lyrebird.csv\"),\n  row.names = TRUE\n)\n```\n:::\n\n\n## 2.5 Lyrebird 差异丰度分析 (ANCOM-BC)\n\n识别在 CagA 野生型 vs CagA 敲除组之间差异丰富的噬菌体 OTU。\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# ANCOM-BC2 差异丰度分析\n# ==============================================================================\ncat(\"=== Lyrebird ANCOM-BC2 差异丰度分析 ===\\n\")\n#> === Lyrebird ANCOM-BC2 差异丰度分析 ===\n\n# 准备数据：需要 counts assay\ntse_daa_lyrebird <- tse_lyrebird_corepair\n\n# 运行 ANCOM-BC2\nancombc_output_lyrebird <- ancombc2(\n  data = tse_daa_lyrebird,\n  assay.type = \"counts\",\n  fix_formula = \"treatment_group\",\n  p_adj_method = \"fdr\",\n  prv_cut = 0.1,\n  lib_cut = 0,\n  group = \"treatment_group\",\n  struc_zero = TRUE,\n  neg_lb = TRUE,\n  alpha = 0.05,\n  global = FALSE,\n  verbose = TRUE\n)\n\n# 提取结果\nancombc_res_lyrebird <- ancombc_output_lyrebird$res\n\n# 动态查找列名\nlfc_col_lyrebird <- grep(\"^lfc_\", colnames(ancombc_res_lyrebird), value = TRUE)[1]\nq_col_lyrebird <- grep(\"^q_\", colnames(ancombc_res_lyrebird), value = TRUE)[1]\n\ncat(\"使用的列名:\\n\")\n#> 使用的列名:\ncat(\"  LFC 列:\", lfc_col_lyrebird, \"\\n\")\n#>   LFC 列: lfc_(Intercept)\ncat(\"  Q 值列:\", q_col_lyrebird, \"\\n\")\n#>   Q 值列: q_(Intercept)\n\n# 添加分类信息\nancombc_res_lyrebird <- ancombc_res_lyrebird |>\n  dplyr::left_join(\n    rowData(tse_daa_lyrebird) |> as.data.frame() |> rownames_to_column(\"taxon\"),\n    by = \"taxon\"\n  )\n\n# 按 q 值排序并取 Top 20\nancombc_top20_lyrebird <- ancombc_res_lyrebird |>\n  arrange(.data[[q_col_lyrebird]]) |>\n  head(20)\n\ncat(\"\\n=== Lyrebird ANCOM-BC Top 20 差异噬菌体 OTU ===\\n\")\n#> \n#> === Lyrebird ANCOM-BC Top 20 差异噬菌体 OTU ===\nprint(ancombc_top20_lyrebird |> dplyr::select(taxon, Family, all_of(c(lfc_col_lyrebird, q_col_lyrebird))))\n#>      taxon                                               Family lfc_(Intercept)\n#> 1  OTU_452 novel_family_198_of_novel_order_89_of_Caudoviricetes      -1.2098370\n#> 2   OTU_32  novel_family_42_of_novel_order_89_of_Caudoviricetes       0.6556359\n#> 3  OTU_117  novel_family_42_of_novel_order_89_of_Caudoviricetes       0.6889229\n#> 4  OTU_291 novel_family_20_of_novel_order_213_of_Caudoviricetes      -0.7940812\n#> 5  OTU_344  novel_family_52_of_novel_order_86_of_Caudoviricetes      -0.7342270\n#> 6  OTU_527  novel_family_52_of_novel_order_86_of_Caudoviricetes      -0.8622626\n#> 7  OTU_590  novel_family_6_of_novel_order_141_of_Caudoviricetes       1.2776161\n#> 8  OTU_465 novel_family_199_of_novel_order_89_of_Caudoviricetes      -0.4442871\n#> 9  OTU_114 novel_family_198_of_novel_order_89_of_Caudoviricetes      -1.1017314\n#> 10 OTU_127 novel_family_131_of_novel_order_89_of_Caudoviricetes       1.1799765\n#> 11 OTU_539 novel_family_25_of_novel_order_123_of_Caudoviricetes      -0.6279100\n#> 12  OTU_82 novel_family_20_of_novel_order_205_of_Caudoviricetes       0.7187393\n#> 13 OTU_387 novel_family_25_of_novel_order_123_of_Caudoviricetes      -0.6960128\n#> 14   OTU_3                                                 <NA>       0.6224263\n#> 15 OTU_568 novel_family_11_of_novel_order_142_of_Caudoviricetes       0.5670256\n#> 16 OTU_396 novel_family_37_of_novel_order_143_of_Caudoviricetes      -0.3642664\n#> 17 OTU_392 novel_family_56_of_novel_order_143_of_Caudoviricetes       0.6293459\n#> 18 OTU_529 novel_family_20_of_novel_order_205_of_Caudoviricetes      -0.8611610\n#> 19 OTU_354 novel_family_20_of_novel_order_205_of_Caudoviricetes      -0.4861191\n#> 20 OTU_485  novel_family_81_of_novel_order_96_of_Caudoviricetes      -0.6029827\n#>    q_(Intercept)\n#> 1    0.003699226\n#> 2    0.003699226\n#> 3    0.004203810\n#> 4    0.005018931\n#> 5    0.007320107\n#> 6    0.007320107\n#> 7    0.009293767\n#> 8    0.009293767\n#> 9    0.013916633\n#> 10   0.021650988\n#> 11   0.026966574\n#> 12   0.033280198\n#> 13   0.040842413\n#> 14   0.040842413\n#> 15   0.040842413\n#> 16   0.040842413\n#> 17   0.040842413\n#> 18   0.040842413\n#> 19   0.041032731\n#> 20   0.047869818\n\n# 保存完整结果\nwrite.csv(\n  ancombc_res_lyrebird,\n  file = here::here(\"data\", params$name, \"24_ancombc_lyrebird_full.csv\"),\n  row.names = FALSE\n)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# 火山图可视化\n# ==============================================================================\n\n# 准备火山图数据\nvolcano_data_lyrebird <- ancombc_res_lyrebird |>\n  mutate(\n    sig = .data[[q_col_lyrebird]] < 0.05,\n    direction = case_when(\n      .data[[q_col_lyrebird]] < 0.05 & .data[[lfc_col_lyrebird]] > 0 ~ \"Up in HpWT\",\n      .data[[q_col_lyrebird]] < 0.05 & .data[[lfc_col_lyrebird]] < 0 ~ \"Up in HpKO\",\n      TRUE ~ \"NS\"\n    )\n  )\n\n# 统计差异 OTU 数量\nn_sig_up_lyrebird <- sum(volcano_data_lyrebird$direction == \"Up in HpWT\", na.rm = TRUE)\nn_sig_down_lyrebird <- sum(volcano_data_lyrebird$direction == \"Up in HpKO\", na.rm = TRUE)\ncat(\"\\n差异噬菌体 OTU 统计:\\n\")\n#> \n#> 差异噬菌体 OTU 统计:\ncat(\"  Up in HpWT (CagA+):\", n_sig_up_lyrebird, \"\\n\")\n#>   Up in HpWT (CagA+): 8\ncat(\"  Up in HpKO (CagA-):\", n_sig_down_lyrebird, \"\\n\")\n#>   Up in HpKO (CagA-): 12\n\np_volcano_lyrebird <- ggplot(volcano_data_lyrebird, aes(x = .data[[lfc_col_lyrebird]], y = -log10(.data[[q_col_lyrebird]]))) +\n  geom_point(aes(color = direction), alpha = 0.6, size = 2) +\n  scale_color_manual(values = c(\"Up in HpWT\" = \"#E41A1C\", \"Up in HpKO\" = \"#377EB8\", \"NS\" = \"grey60\")) +\n  geom_hline(yintercept = -log10(0.05), linetype = \"dashed\", color = \"grey40\") +\n  geom_vline(xintercept = 0, linetype = \"dashed\", color = \"grey40\") +\n  theme_bw() +\n  labs(\n    title = \"Lyrebird: Differential Phage Abundance (ANCOM-BC2)\",\n    subtitle = paste0(\"Up in HpWT: \", n_sig_up_lyrebird, \" | Up in HpKO: \", n_sig_down_lyrebird),\n    x = \"Log Fold Change (HpWT vs HpKO)\",\n    y = \"-log10(Q-value)\",\n    color = \"Direction\"\n  )\n\np_volcano_lyrebird\n```\n\n::: {.cell-output-display}\n![](03_singlem_diversity_analysis_files/figure-html/lyrebird-ancombc-volcano-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\n\nggsave(\n  filename = here::here(\"data\", params$name, \"25_volcano_ancombc_lyrebird.png\"),\n  plot = p_volcano_lyrebird, width = 10, height = 8, dpi = 300\n)\n```\n:::\n\n\n# Part 3: 结果汇总 {#sec-part3}\n\n## 3.1 完整结果汇总表\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# 创建完整结果汇总表（SingleM + Lyrebird + Bracken）\n# ==============================================================================\n\n# 安全提取 P 值的辅助函数\nget_unifrac_p <- function(permanova_result) {\n  if (is.null(permanova_result) || is.na(permanova_result$`Pr(>F)`[1])) {\n    return(NA)\n  }\n  return(round(permanova_result$`Pr(>F)`[1], 4))\n}\n\nget_lyrebird_unifrac_p <- function(permanova_result) {\n  tryCatch({\n    if (is.null(permanova_result)) return(NA)\n    return(round(permanova_result$`Pr(>F)`[1], 4))\n  }, error = function(e) NA)\n}\n\n# 完整结果汇总表\nsummary_table <- data.frame(\n  Analysis = c(\n    \"Alpha: Shannon (Wilcoxon)\",\n    \"Alpha: Observed (Wilcoxon)\",\n    \"Beta: Bray-Curtis (PERMANOVA)\",\n    \"Beta: Weighted UniFrac (PERMANOVA)\",\n    \"Beta: Unweighted UniFrac (PERMANOVA)\"\n  ),\n  SingleM = c(\n    round(wilcox_shannon$p.value, 4),\n    round(wilcox_observed$p.value, 4),\n    round(permanova_bray$permanova$`Pr(>F)`[1], 4),\n    get_unifrac_p(permanova_wunifrac),\n    get_unifrac_p(permanova_uwunifrac)\n  ),\n  Lyrebird = c(\n    round(wilcox_lyrebird_shannon$p.value, 4),\n    NA,  # Lyrebird 没有单独计算 Observed 的 Wilcoxon\n    round(permanova_lyrebird$permanova$`Pr(>F)`[1], 4),\n    get_lyrebird_unifrac_p(permanova_wunifrac_lyrebird),\n    get_lyrebird_unifrac_p(permanova_uwunifrac_lyrebird)\n  ),\n  Bracken = c(\n    0.73,\n    0.29,\n    0.012,\n    NA,\n    NA\n  )\n)\n\ncat(\"\\n=== 完整结果汇总 (P 值) ===\\n\")\n#> \n#> === 完整结果汇总 (P 值) ===\ncat(\"比较组: ApcMUT_HpWT vs ApcMUT_HpKO\\n\\n\")\n#> 比较组: ApcMUT_HpWT vs ApcMUT_HpKO\nprint(summary_table)\n#>                               Analysis SingleM Lyrebird Bracken\n#> 1            Alpha: Shannon (Wilcoxon)  0.9048   0.0317   0.730\n#> 2           Alpha: Observed (Wilcoxon)  0.1111       NA   0.290\n#> 3        Beta: Bray-Curtis (PERMANOVA)  0.0370   0.0570   0.012\n#> 4   Beta: Weighted UniFrac (PERMANOVA)  0.0290   0.0500      NA\n#> 5 Beta: Unweighted UniFrac (PERMANOVA)  0.0080   0.0430      NA\n\n# 添加显著性标记\nsummary_table_sig <- summary_table |>\n  mutate(\n    SingleM_sig = case_when(\n      SingleM < 0.001 ~ \"***\",\n      SingleM < 0.01 ~ \"**\",\n      SingleM < 0.05 ~ \"*\",\n      TRUE ~ \"\"\n    ),\n    Lyrebird_sig = case_when(\n      Lyrebird < 0.001 ~ \"***\",\n      Lyrebird < 0.01 ~ \"**\",\n      Lyrebird < 0.05 ~ \"*\",\n      is.na(Lyrebird) ~ \"-\",\n      TRUE ~ \"\"\n    ),\n    Bracken_sig = case_when(\n      Bracken < 0.001 ~ \"***\",\n      Bracken < 0.01 ~ \"**\",\n      Bracken < 0.05 ~ \"*\",\n      is.na(Bracken) ~ \"-\",\n      TRUE ~ \"\"\n    )\n  )\n\nwrite.csv(\n  summary_table,\n  file = here::here(\"data\", params$name, \"26_full_results_comparison.csv\"),\n  row.names = FALSE\n)\n```\n:::\n\n\n## 3.2 结果可视化总结\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# P 值热图\n# ==============================================================================\n\n# 准备热图数据\nheatmap_data <- summary_table |>\n  pivot_longer(cols = c(SingleM, Lyrebird, Bracken),\n               names_to = \"Method\", values_to = \"P_value\") |>\n  mutate(\n    neg_log_p = -log10(P_value),\n    neg_log_p = ifelse(is.infinite(neg_log_p), 4, neg_log_p),  # 处理极小 P 值\n    sig_label = case_when(\n      is.na(P_value) ~ \"NA\",\n      P_value < 0.001 ~ \"***\",\n      P_value < 0.01 ~ \"**\",\n      P_value < 0.05 ~ \"*\",\n      TRUE ~ \"ns\"\n    ),\n    Method = factor(Method, levels = c(\"SingleM\", \"Lyrebird\", \"Bracken\"))\n  )\n\np_heatmap <- ggplot(heatmap_data, aes(x = Method, y = Analysis, fill = neg_log_p)) +\n  geom_tile(color = \"white\", linewidth = 0.5) +\n  geom_text(aes(label = sig_label), size = 5) +\n  scale_fill_gradient2(\n    low = \"white\", mid = \"lightyellow\", high = \"red\",\n    midpoint = 1.3,  # -log10(0.05) ≈ 1.3\n    na.value = \"grey90\",\n    name = \"-log10(P)\"\n  ) +\n  theme_minimal() +\n  theme(\n    axis.text.x = element_text(size = 12, face = \"bold\"),\n    axis.text.y = element_text(size = 10),\n    panel.grid = element_blank()\n  ) +\n  labs(\n    title = \"Statistical Significance Heatmap\",\n    subtitle = \"ApcMUT_HpWT vs ApcMUT_HpKO | *P<0.05, **P<0.01, ***P<0.001\",\n    x = \"\", y = \"\"\n  )\n\n# ==============================================================================\n# P 值条形图\n# ==============================================================================\n\nbar_data <- summary_table |>\n  pivot_longer(cols = c(SingleM, Lyrebird, Bracken),\n               names_to = \"Method\", values_to = \"P_value\") |>\n  dplyr::filter(!is.na(P_value)) |>\n  mutate(\n    neg_log_p = -log10(P_value),\n    Method = factor(Method, levels = c(\"SingleM\", \"Lyrebird\", \"Bracken\")),\n    sig = P_value < 0.05\n  )\n\np_barplot <- ggplot(bar_data, aes(x = Analysis, y = neg_log_p, fill = Method)) +\n  geom_bar(stat = \"identity\", position = position_dodge(width = 0.8), width = 0.7) +\n  geom_hline(yintercept = -log10(0.05), linetype = \"dashed\", color = \"red\", linewidth = 0.8) +\n  annotate(\"text\", x = 0.5, y = -log10(0.05) + 0.15, label = \"P=0.05\", color = \"red\", hjust = 0, size = 3) +\n  scale_fill_brewer(palette = \"Set2\") +\n  coord_flip() +\n  theme_bw() +\n  labs(\n    title = \"Statistical Significance by Method\",\n    subtitle = \"Higher bars = more significant (bars above red line: P < 0.05)\",\n    x = \"\", y = \"-log10(P-value)\"\n  )\n\n# 组合图\np_summary_combined <- p_heatmap + p_barplot +\n  plot_layout(widths = c(1, 1.2)) +\n  plot_annotation(\n    title = \"Part 3: Results Summary\",\n    theme = theme(plot.title = element_text(size = 16, face = \"bold\"))\n  )\n\np_summary_combined\n```\n\n::: {.cell-output-display}\n![](03_singlem_diversity_analysis_files/figure-html/summary-visualization-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\n\nggsave(\n  filename = here::here(\"data\", params$name, \"27_results_summary_visualization.png\"),\n  plot = p_summary_combined, width = 14, height = 8, dpi = 300\n)\n```\n:::\n\n\n## 3.3 Host-Virus 关联分析\n\n探索细菌（SingleM）和噬菌体（Lyrebird）群落之间的关联，这是 SingleM/Lyrebird 框架的独特优势。\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# 1. 样本级别的多样性关联\n# ==============================================================================\ncat(\"=== Host-Virus 关联分析 ===\\n\\n\")\n#> === Host-Virus 关联分析 ===\n\n# 获取共同样本\ncommon_samples_hv <- base::intersect(\n  colnames(tse_singlem_corepair),\n  colnames(tse_lyrebird_corepair)\n)\ncat(\"共同样本数:\", length(common_samples_hv), \"\\n\")\n#> 共同样本数: 9\n\n# 提取 Alpha 多样性数据\ndiversity_data <- data.frame(\n  sample = common_samples_hv,\n  bacteria_shannon = colData(tse_singlem_corepair)[common_samples_hv, \"shannon_index\"],\n  phage_shannon = colData(tse_lyrebird_corepair)[common_samples_hv, \"shannon_index\"],\n  treatment_group = colData(tse_singlem_corepair)[common_samples_hv, \"treatment_group\"]\n)\n\n# Spearman 相关性\ncor_test <- cor.test(\n  diversity_data$bacteria_shannon,\n  diversity_data$phage_shannon,\n  method = \"spearman\"\n)\n\ncat(\"\\n细菌-噬菌体 Shannon 多样性相关性:\\n\")\n#> \n#> 细菌-噬菌体 Shannon 多样性相关性:\ncat(\"  Spearman rho:\", round(cor_test$estimate, 3), \"\\n\")\n#>   Spearman rho: 0.567\ncat(\"  P-value:\", round(cor_test$p.value, 4), \"\\n\")\n#>   P-value: 0.1206\n\n# 可视化\np_diversity_cor <- ggplot(diversity_data, aes(x = bacteria_shannon, y = phage_shannon)) +\n  geom_point(aes(color = treatment_group), size = 3) +\n  geom_smooth(method = \"lm\", se = TRUE, color = \"grey40\", linetype = \"dashed\") +\n  theme_bw() +\n  labs(\n    title = \"Host-Virus Alpha Diversity Correlation\",\n    subtitle = paste0(\"Spearman ρ = \", round(cor_test$estimate, 3),\n                     \", P = \", round(cor_test$p.value, 4)),\n    x = \"Bacteria Shannon Diversity (SingleM)\",\n    y = \"Phage Shannon Diversity (Lyrebird)\",\n    color = \"Treatment\"\n  )\n\n# ==============================================================================\n# 2. Procrustes 分析：Beta 多样性关联\n# ==============================================================================\ncat(\"\\n\\n=== Procrustes 分析 (Beta 多样性关联) ===\\n\")\n#> \n#> \n#> === Procrustes 分析 (Beta 多样性关联) ===\n\n# 获取 Bray-Curtis 距离矩阵\nbacteria_dist <- vegan::vegdist(\n  t(assay(tse_singlem_corepair[, common_samples_hv], \"relabundance\")),\n  method = \"bray\"\n)\nphage_dist <- vegan::vegdist(\n  t(assay(tse_lyrebird_corepair[, common_samples_hv], \"relabundance\")),\n  method = \"bray\"\n)\n\n# PCoA\nbacteria_pcoa <- cmdscale(bacteria_dist, k = 2)\nphage_pcoa <- cmdscale(phage_dist, k = 2)\n\n# Procrustes 分析\nprocrustes_result <- vegan::protest(bacteria_pcoa, phage_pcoa, permutations = 999)\n\ncat(\"Procrustes 相关性 (m²):\", round(procrustes_result$ss, 4), \"\\n\")\n#> Procrustes 相关性 (m²): 0.2375\ncat(\"相关系数:\", round(sqrt(1 - procrustes_result$ss), 4), \"\\n\")\n#> 相关系数: 0.8732\ncat(\"P-value:\", round(procrustes_result$signif, 4), \"\\n\")\n#> P-value: 0.002\n\n# Procrustes 可视化\nprocrustes_df <- data.frame(\n  X1_bacteria = bacteria_pcoa[, 1],\n  Y1_bacteria = bacteria_pcoa[, 2],\n  X2_phage = procrustes_result$Yrot[, 1],\n  Y2_phage = procrustes_result$Yrot[, 2],\n  sample = common_samples_hv,\n  treatment = diversity_data$treatment_group\n)\n\np_procrustes <- ggplot(procrustes_df) +\n  geom_segment(aes(x = X1_bacteria, y = Y1_bacteria,\n                   xend = X2_phage, yend = Y2_phage),\n               color = \"grey60\", alpha = 0.6) +\n  geom_point(aes(x = X1_bacteria, y = Y1_bacteria, color = treatment),\n             size = 3, shape = 16) +\n  geom_point(aes(x = X2_phage, y = Y2_phage, color = treatment),\n             size = 3, shape = 17) +\n  theme_bw() +\n  labs(\n    title = \"Procrustes Analysis: Bacteria vs Phage Communities\",\n    subtitle = paste0(\"Correlation = \", round(sqrt(1 - procrustes_result$ss), 3),\n                     \", P = \", round(procrustes_result$signif, 4),\n                     \" | ● Bacteria, ▲ Phage\"),\n    x = \"PCoA 1\", y = \"PCoA 2\",\n    color = \"Treatment\"\n  )\n\n# ==============================================================================\n# 3. Mantel 检验：距离矩阵相关性\n# ==============================================================================\ncat(\"\\n\\n=== Mantel 检验 ===\\n\")\n#> \n#> \n#> === Mantel 检验 ===\n\nmantel_result <- vegan::mantel(bacteria_dist, phage_dist, method = \"spearman\", permutations = 999)\n\ncat(\"Mantel 统计量 (r):\", round(mantel_result$statistic, 4), \"\\n\")\n#> Mantel 统计量 (r): 0.9323\ncat(\"P-value:\", round(mantel_result$signif, 4), \"\\n\")\n#> P-value: 0.001\n\n# ==============================================================================\n# 组合图\n# ==============================================================================\np_host_virus <- p_diversity_cor + p_procrustes +\n  plot_annotation(\n    title = \"Host-Virus (Bacteria-Phage) Community Associations\",\n    subtitle = paste0(\"Mantel test: r = \", round(mantel_result$statistic, 3),\n                     \", P = \", round(mantel_result$signif, 4)),\n    theme = theme(plot.title = element_text(size = 14, face = \"bold\"))\n  )\n\np_host_virus\n```\n\n::: {.cell-output-display}\n![](03_singlem_diversity_analysis_files/figure-html/host-virus-correlation-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\n\nggsave(\n  filename = here::here(\"data\", params$name, \"28_host_virus_association.png\"),\n  plot = p_host_virus, width = 14, height = 6, dpi = 300\n)\n\n# 保存关联分析结果\nhost_virus_summary <- data.frame(\n  Analysis = c(\"Alpha Diversity Correlation\", \"Procrustes Analysis\", \"Mantel Test\"),\n  Statistic = c(\n    paste0(\"Spearman ρ = \", round(cor_test$estimate, 3)),\n    paste0(\"Correlation = \", round(sqrt(1 - procrustes_result$ss), 3)),\n    paste0(\"Mantel r = \", round(mantel_result$statistic, 3))\n  ),\n  P_value = c(\n    round(cor_test$p.value, 4),\n    round(procrustes_result$signif, 4),\n    round(mantel_result$signif, 4)\n  )\n)\n\ncat(\"\\n\\n=== Host-Virus 关联分析汇总 ===\\n\")\n#> \n#> \n#> === Host-Virus 关联分析汇总 ===\nprint(host_virus_summary)\n#>                      Analysis           Statistic P_value\n#> 1 Alpha Diversity Correlation  Spearman ρ = 0.567  0.1206\n#> 2         Procrustes Analysis Correlation = 0.873  0.0020\n#> 3                 Mantel Test    Mantel r = 0.932  0.0010\n\nwrite.csv(\n  host_virus_summary,\n  file = here::here(\"data\", params$name, \"29_host_virus_association_summary.csv\"),\n  row.names = FALSE\n)\n```\n:::\n\n\n### 3.3.1 细菌-噬菌体 Beta 多样性并排对比\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# 细菌和噬菌体 PCoA 并排对比图 (更清晰的可视化)\n# ==============================================================================\n\n# 颜色设置\ngroup_colors <- c(\"ApcMUT_HpKO\" = \"#3498db\", \"ApcMUT_HpWT\" = \"#e74c3c\")\ngroup_labels <- c(\"ApcMUT_HpKO\" = \"HpKO (Control)\", \"ApcMUT_HpWT\" = \"HpWT (CagA+)\")\n\n# 准备数据框\ndf_singlem_pcoa <- data.frame(\n  PC1 = bacteria_pcoa[, 1],\n  PC2 = bacteria_pcoa[, 2],\n  sample = rownames(bacteria_pcoa),\n  treatment_group = diversity_data$treatment_group\n)\n\ndf_lyrebird_pcoa <- data.frame(\n  PC1 = phage_pcoa[, 1],\n  PC2 = phage_pcoa[, 2],\n  sample = rownames(phage_pcoa),\n  treatment_group = diversity_data$treatment_group\n)\n\n# 绘制细菌 PCoA\np_bacteria_beta <- ggplot(df_singlem_pcoa, aes(x = PC1, y = PC2, color = treatment_group)) +\n  geom_point(size = 4, alpha = 0.8) +\n  stat_ellipse(level = 0.68, linetype = \"dashed\", linewidth = 0.8) +\n  scale_color_manual(values = group_colors, labels = group_labels) +\n  labs(\n    title = \"Bacteria (SingleM)\",\n    subtitle = paste0(\"PERMANOVA P = \", round(permanova_bray$permanova$`Pr(>F)`[1], 3)),\n    x = \"PCoA 1\",\n    y = \"PCoA 2\",\n    color = \"Group\"\n  ) +\n  theme_bw(base_size = 11) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 13),\n    legend.position = \"none\"\n  ) +\n  coord_fixed()\n\n# 绘制噬菌体 PCoA\np_phage_beta <- ggplot(df_lyrebird_pcoa, aes(x = PC1, y = PC2, color = treatment_group)) +\n  geom_point(size = 4, alpha = 0.8) +\n  stat_ellipse(level = 0.68, linetype = \"dashed\", linewidth = 0.8) +\n  scale_color_manual(values = group_colors, labels = group_labels) +\n  labs(\n    title = \"Phage (Lyrebird)\",\n    subtitle = paste0(\"PERMANOVA P = \", round(permanova_lyrebird$permanova$`Pr(>F)`[1], 3)),\n    x = \"PCoA 1\",\n    y = \"PCoA 2\",\n    color = \"Group\"\n  ) +\n  theme_bw(base_size = 11) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 13),\n    legend.position = \"none\"\n  ) +\n  coord_fixed()\n\n# 合并图\np_beta_combined <- (p_bacteria_beta | p_phage_beta) +\n  plot_layout(guides = \"collect\") +\n  plot_annotation(\n    title = \"Bacteria and Phage Communities Both Shift with CagA\",\n    subtitle = paste0(\"Mantel test r = \", round(mantel_result$statistic, 3),\n                     \", P = \", round(mantel_result$signif, 4),\n                     \" | Procrustes r = \", round(sqrt(1 - procrustes_result$ss), 3),\n                     \", P = \", round(procrustes_result$signif, 4)),\n    theme = theme(\n      plot.title = element_text(face = \"bold\", size = 15),\n      plot.subtitle = element_text(size = 11, color = \"gray30\")\n    )\n  )\n\n# 添加共享图例\np_beta_combined <- p_beta_combined & theme(legend.position = \"bottom\")\n\nprint(p_beta_combined)\n```\n\n::: {.cell-output-display}\n![](03_singlem_diversity_analysis_files/figure-html/bacteria-phage-beta-combined-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\n\nggsave(\n  filename = here::here(\"data\", params$name, \"30_bacteria_phage_beta_combined.png\"),\n  plot = p_beta_combined,\n  width = 12, height = 6, dpi = 300\n)\n\ncat(\"✅ 细菌-噬菌体 Beta 多样性对比图已保存: 30_bacteria_phage_beta_combined.png\\n\")\n#> ✅ 细菌-噬菌体 Beta 多样性对比图已保存: 30_bacteria_phage_beta_combined.png\n```\n:::\n\n\n### 3.3.2 Procrustes 可视化 (箭头连接图)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# Procrustes 分析可视化 (带箭头的连接图)\n# ==============================================================================\n\n# 提取 Procrustes 旋转后的坐标\ndf_procrustes <- data.frame(\n  sample = common_samples_hv,\n  # Target (bacteria)\n  bact_x = procrustes_result$X[, 1],\n  bact_y = procrustes_result$X[, 2],\n  # Rotated (phage)\n  phage_x = procrustes_result$Yrot[, 1],\n  phage_y = procrustes_result$Yrot[, 2],\n  treatment_group = diversity_data$treatment_group\n)\n\n# 绘制 Procrustes 图\np_procrustes_arrow <- ggplot(df_procrustes) +\n  # 绘制连接线（箭头）\n  geom_segment(aes(x = bact_x, y = bact_y, xend = phage_x, yend = phage_y,\n                   color = treatment_group),\n               arrow = arrow(length = unit(0.15, \"cm\"), type = \"closed\"),\n               linewidth = 0.8, alpha = 0.7) +\n  # 细菌点（实心圆）\n  geom_point(aes(x = bact_x, y = bact_y, color = treatment_group),\n             shape = 16, size = 4, alpha = 0.9) +\n  # 噬菌体点（实心三角）\n  geom_point(aes(x = phage_x, y = phage_y, color = treatment_group),\n             shape = 17, size = 4, alpha = 0.9) +\n  scale_color_manual(values = group_colors, labels = group_labels) +\n  labs(\n    title = \"Bacteria-Phage Community Co-variation\",\n    subtitle = paste0(\"Procrustes: r = \", round(sqrt(1 - procrustes_result$ss), 3),\n                     \", P = \", round(procrustes_result$signif, 4)),\n    x = \"Procrustes Dimension 1\",\n    y = \"Procrustes Dimension 2\",\n    color = \"Group\",\n    caption = \"● Bacteria (SingleM)  ▲ Phage (Lyrebird)\\nShorter arrows = stronger correspondence\"\n  ) +\n  theme_bw(base_size = 12) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 14),\n    plot.subtitle = element_text(size = 11, color = \"gray30\"),\n    legend.position = \"bottom\",\n    aspect.ratio = 1\n  ) +\n  coord_fixed()\n\nprint(p_procrustes_arrow)\n```\n\n::: {.cell-output-display}\n![](03_singlem_diversity_analysis_files/figure-html/procrustes-arrow-plot-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\n\nggsave(\n  filename = here::here(\"data\", params$name, \"31_bacteria_phage_procrustes.png\"),\n  plot = p_procrustes_arrow,\n  width = 8, height = 8, dpi = 300\n)\n\ncat(\"✅ Procrustes 箭头图已保存: 31_bacteria_phage_procrustes.png\\n\")\n#> ✅ Procrustes 箭头图已保存: 31_bacteria_phage_procrustes.png\n```\n:::\n\n\n## 3.4 分析小结\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 构建 SingleM UniFrac 结果文本\nunifrac_text <- if (unifrac_success) {\n  paste0(\n    \"3. **Beta 多样性 (Weighted UniFrac)**: PERMANOVA P=\", get_unifrac_p(permanova_wunifrac), \"\\n\",\n    \"4. **Beta 多样性 (Unweighted UniFrac)**: PERMANOVA P=\", get_unifrac_p(permanova_uwunifrac)\n  )\n} else {\n  \"3. **Beta 多样性 (UniFrac)**: 计算未成功\"\n}\n\n# 构建 Lyrebird UniFrac 结果文本\nlyrebird_unifrac_text <- if (lyrebird_unifrac_success) {\n  paste0(\n    \"3. **Beta 多样性 (Weighted UniFrac)**: PERMANOVA P=\", round(permanova_wunifrac_lyrebird$`Pr(>F)`[1], 4), \"\\n\",\n    \"4. **Beta 多样性 (Unweighted UniFrac)**: PERMANOVA P=\", round(permanova_uwunifrac_lyrebird$`Pr(>F)`[1], 4)\n  )\n} else {\n  \"3. **Beta 多样性 (UniFrac)**: 计算未成功\"\n}\n\ncat(\"\n## SingleM/Lyrebird 分析小结\n\n### Part 1: SingleM细菌/古菌分析 {#sec-part1}\n\n**数据概况**:\n- 清洗后 OTU 数: \", nrow(tse_singlem_ca_cleaned), \"\n- 样本数: \", ncol(tse_singlem_ca_cleaned), \"\n- 核心比较组: ApcMUT_HpWT (n=\", sum(tse_singlem_corepair$treatment_group == 'ApcMUT_HpWT'), \") vs ApcMUT_HpKO (n=\", sum(tse_singlem_corepair$treatment_group == 'ApcMUT_HpKO'), \")\n\n**关键发现**:\n1. **Alpha 多样性**: Shannon P=\", round(wilcox_shannon$p.value, 4), \", Observed P=\", round(wilcox_observed$p.value, 4), \"\n2. **Beta 多样性 (Bray-Curtis)**: PERMANOVA P=\", round(permanova_bray$permanova$`Pr(>F)`[1], 4), \"\n\", unifrac_text, \"\n5. **差异丰度 (ANCOM-BC2)**: 见火山图\n\n### Part 2: Lyrebird噬菌体分析 {#sec-part2}\n\n**数据概况**:\n- 清洗后噬菌体 OTU 数: \", nrow(tse_lyrebird_ca_cleaned), \"\n- 样本数: \", ncol(tse_lyrebird_ca_cleaned), \"\n- 核心比较组样本数: \", ncol(tse_lyrebird_corepair), \"\n\n**关键发现**:\n1. **Alpha 多样性**: Shannon P=\", round(wilcox_lyrebird_shannon$p.value, 4), \"\n2. **Beta 多样性 (Bray-Curtis)**: PERMANOVA P=\", round(permanova_lyrebird$permanova$`Pr(>F)`[1], 4), \"\n\", lyrebird_unifrac_text, \"\n5. **差异丰度 (ANCOM-BC2)**: Up in HpWT=\", n_sig_up_lyrebird, \", Up in HpKO=\", n_sig_down_lyrebird, \"\n\n### Part 3: Host-Virus 关联分析\n\n**核心发现**:\n1. **Alpha 多样性关联**: 细菌与噬菌体 Shannon 多样性 Spearman ρ=\", round(cor_test$estimate, 3), \", P=\", round(cor_test$p.value, 4), \"\n2. **Beta 多样性关联 (Procrustes)**: 相关系数=\", round(sqrt(1 - procrustes_result$ss), 3), \", P=\", round(procrustes_result$signif, 4), \"\n3. **Mantel 检验**: r=\", round(mantel_result$statistic, 3), \", P=\", round(mantel_result$signif, 4), \"\n\n### SingleM/Lyrebird 相比 Bracken 的优势\n\n1. **UniFrac 距离**: 提供系统发育树，可计算考虑进化关系的 UniFrac 距离\n2. **新物种检测**: 基于标记基因 HMM，能检测数据库中未收录的物种\n3. **OTU 分辨率**: 更细粒度的群落结构分析\n4. **噬菌体分析**: Lyrebird 专门针对 dsDNA 噬菌体，Bracken 无此功能\n5. **Host-Virus 关联**: 可同时分析细菌和噬菌体，探索宿主-病毒互作\n\")\n```\n\n\n## SingleM/Lyrebird 分析小结\n\n### Part 1: SingleM细菌/古菌分析 {#sec-part1}\n\n**数据概况**:\n- 清洗后 OTU 数:  465 \n- 样本数:  28 \n- 核心比较组: ApcMUT_HpWT (n= 5 ) vs ApcMUT_HpKO (n= 4 )\n\n**关键发现**:\n1. **Alpha 多样性**: Shannon P= 0.9048 , Observed P= 0.1111 \n2. **Beta 多样性 (Bray-Curtis)**: PERMANOVA P= 0.037 \n 3. **Beta 多样性 (Weighted UniFrac)**: PERMANOVA P=0.029\n4. **Beta 多样性 (Unweighted UniFrac)**: PERMANOVA P=0.008 \n5. **差异丰度 (ANCOM-BC2)**: 见火山图\n\n### Part 2: Lyrebird噬菌体分析 {#sec-part2}\n\n**数据概况**:\n- 清洗后噬菌体 OTU 数:  878 \n- 样本数:  28 \n- 核心比较组样本数:  9 \n\n**关键发现**:\n1. **Alpha 多样性**: Shannon P= 0.0317 \n2. **Beta 多样性 (Bray-Curtis)**: PERMANOVA P= 0.057 \n 3. **Beta 多样性 (Weighted UniFrac)**: PERMANOVA P=0.05\n4. **Beta 多样性 (Unweighted UniFrac)**: PERMANOVA P=0.043 \n5. **差异丰度 (ANCOM-BC2)**: Up in HpWT= 8 , Up in HpKO= 12 \n\n### Part 3: Host-Virus 关联分析\n\n**核心发现**:\n1. **Alpha 多样性关联**: 细菌与噬菌体 Shannon 多样性 Spearman ρ= 0.567 , P= 0.1206 \n2. **Beta 多样性关联 (Procrustes)**: 相关系数= 0.873 , P= 0.002 \n3. **Mantel 检验**: r= 0.932 , P= 0.001 \n\n### SingleM/Lyrebird 相比 Bracken 的优势\n\n1. **UniFrac 距离**: 提供系统发育树，可计算考虑进化关系的 UniFrac 距离\n2. **新物种检测**: 基于标记基因 HMM，能检测数据库中未收录的物种\n3. **OTU 分辨率**: 更细粒度的群落结构分析\n4. **噬菌体分析**: Lyrebird 专门针对 dsDNA 噬菌体，Bracken 无此功能\n5. **Host-Virus 关联**: 可同时分析细菌和噬菌体，探索宿主-病毒互作\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# 保存关键数据供下游分析（如 03b_virome_function_integration）使用\n# ==============================================================================\n\ncat(\"=== 保存数据供下游分析 ===\\n\\n\")\n#> === 保存数据供下游分析 ===\n\n# 保存 Lyrebird 噬菌体 TSE 对象（核心比较组）\nsaveRDS(\n  tse_lyrebird_corepair,\n  file = here::here(\"data\", params$name, \"tse_lyrebird_corepair.rds\")\n)\ncat(\"已保存: tse_lyrebird_corepair.rds\\n\")\n#> 已保存: tse_lyrebird_corepair.rds\ncat(\"  - 样本数:\", ncol(tse_lyrebird_corepair), \"\\n\")\n#>   - 样本数: 9\ncat(\"  - 噬菌体 OTU 数:\", nrow(tse_lyrebird_corepair), \"\\n\")\n#>   - 噬菌体 OTU 数: 878\n\n# 保存 SingleM 细菌 TSE 对象（核心比较组）\nsaveRDS(\n  tse_singlem_corepair,\n  file = here::here(\"data\", params$name, \"tse_singlem_corepair.rds\")\n)\ncat(\"\\n已保存: tse_singlem_corepair.rds\\n\")\n#> \n#> 已保存: tse_singlem_corepair.rds\ncat(\"  - 样本数:\", ncol(tse_singlem_corepair), \"\\n\")\n#>   - 样本数: 9\ncat(\"  - 细菌 OTU 数:\", nrow(tse_singlem_corepair), \"\\n\")\n#>   - 细菌 OTU 数: 465\n```\n:::\n\n\n---\n\n## Files written\n\nThese files have been written to the target directory, data/03_singlem_diversity_analysis:\n\n\n\n# Part 4: 扩展组间比较分析 {#sec-part4}\n\n::: {.callout-note}\n## 分析目的\n\n此前的分析仅比较了核心组 **ApcMUT_HpWT vs ApcMUT_HpKO**。本部分将扩展分析范围：\n\n1. **多组可视化**：展示所有实验组的群落结构\n2. **新增两两比较**：探究不同因素组合下的差异\n3. **双因素交互作用**：分析 Apc状态 × Hp感染 的交互效应\n\n这些分析可以回答：**CagA的菌群重塑效应是否依赖于Apc突变背景？**\n:::\n\n## 4.1 数据准备：全组分析\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# 1. 准备包含所有组的 TSE 对象\n# ==============================================================================\ncat(\"=== Part 4: 扩展组间比较分析 ===\\n\\n\")\n#> === Part 4: 扩展组间比较分析 ===\n\n# 使用已清洗的全部 Caecum 样本\ntse_singlem_all <- tse_singlem_ca_cleaned\ntse_lyrebird_all <- tse_lyrebird_ca_cleaned\n\n# 检查各组样本分布\ncat(\"SingleM 各组样本分布:\\n\")\n#> SingleM 各组样本分布:\nprint(table(tse_singlem_all$treatment_group))\n#> \n#> ApcMUT_Ctrl ApcMUT_HpKO ApcMUT_HpWT  ApcWT_Ctrl  ApcWT_HpKO  ApcWT_HpWT \n#>           4           4           5           5           5           5\n\ncat(\"\\nLyrebird 各组样本分布:\\n\")\n#> \n#> Lyrebird 各组样本分布:\nprint(table(tse_lyrebird_all$treatment_group))\n#> \n#> ApcMUT_Ctrl ApcMUT_HpKO ApcMUT_HpWT  ApcWT_Ctrl  ApcWT_HpKO  ApcWT_HpWT \n#>           4           4           5           5           5           5\n\n# ==============================================================================\n# 2. 创建分析所需的因子变量\n# ==============================================================================\n# 提取 Apc 状态和 Hp 感染状态（从 treatment_group 解析）\nparse_treatment <- function(tse) {\n  colData(tse)$Apc_status <- ifelse(\n    grepl(\"ApcMUT\", colData(tse)$treatment_group),\n    \"ApcMUT\", \"ApcWT\"\n  )\n  colData(tse)$Hp_status <- case_when(\n    grepl(\"HpWT\", colData(tse)$treatment_group) ~ \"HpWT\",\n    grepl(\"HpKO\", colData(tse)$treatment_group) ~ \"HpKO\",\n    grepl(\"Ctrl\", colData(tse)$treatment_group) ~ \"Ctrl\",\n    TRUE ~ \"Unknown\"\n  )\n  return(tse)\n}\n\ntse_singlem_all <- parse_treatment(tse_singlem_all)\ntse_lyrebird_all <- parse_treatment(tse_lyrebird_all)\n\n# 确认解析结果\ncat(\"\\nApc 状态分布:\\n\")\n#> \n#> Apc 状态分布:\nprint(table(tse_singlem_all$Apc_status))\n#> \n#> ApcMUT  ApcWT \n#>     13     15\n\ncat(\"\\nHp 感染状态分布:\\n\")\n#> \n#> Hp 感染状态分布:\nprint(table(tse_singlem_all$Hp_status))\n#> \n#> Ctrl HpKO HpWT \n#>    9    9   10\n\n# ==============================================================================\n# 3. 创建排除 Ctrl 组的 2×2 设计子集（用于交互作用分析）\n# ==============================================================================\ntse_singlem_2x2 <- tse_singlem_all[\n  , tse_singlem_all$Hp_status %in% c(\"HpWT\", \"HpKO\")\n]\ntse_singlem_2x2$Apc_status <- factor(tse_singlem_2x2$Apc_status, levels = c(\"ApcWT\", \"ApcMUT\"))\ntse_singlem_2x2$Hp_status <- factor(tse_singlem_2x2$Hp_status, levels = c(\"HpKO\", \"HpWT\"))\n\ntse_lyrebird_2x2 <- tse_lyrebird_all[\n  , tse_lyrebird_all$Hp_status %in% c(\"HpWT\", \"HpKO\")\n]\ntse_lyrebird_2x2$Apc_status <- factor(tse_lyrebird_2x2$Apc_status, levels = c(\"ApcWT\", \"ApcMUT\"))\ntse_lyrebird_2x2$Hp_status <- factor(tse_lyrebird_2x2$Hp_status, levels = c(\"HpKO\", \"HpWT\"))\n\ncat(\"\\n2×2 设计样本分布 (SingleM):\\n\")\n#> \n#> 2×2 设计样本分布 (SingleM):\nprint(table(tse_singlem_2x2$Apc_status, tse_singlem_2x2$Hp_status))\n#>         \n#>          HpKO HpWT\n#>   ApcWT     5    5\n#>   ApcMUT    4    5\n```\n:::\n\n\n## 4.2 全组 Beta 多样性可视化\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# 1. SingleM 全组 PCoA (Bray-Curtis)\n# ==============================================================================\ntse_singlem_all <- runMDS(\n  tse_singlem_all,\n  FUN = vegan::vegdist,\n  method = \"bray\",\n  assay.type = \"relabundance\",\n  name = \"PCoA_Bray_All\"\n)\n\neig_all <- attr(reducedDim(tse_singlem_all, \"PCoA_Bray_All\"), \"eig\")\nrel_eig_all <- eig_all / sum(eig_all[eig_all > 0])\n\n# 定义颜色方案（区分6组）\ngroup_colors <- c(\n  \"ApcWT_HpKO\" = \"#4DAF4A\",   # 绿色 - WT基线\n  \"ApcWT_HpWT\" = \"#377EB8\",   # 蓝色 - WT感染\n  \"ApcMUT_HpKO\" = \"#FF7F00\",  # 橙色 - MUT基线\n  \"ApcMUT_HpWT\" = \"#E41A1C\",  # 红色 - MUT感染（核心组）\n  \"ApcMUT_Ctrl\" = \"#984EA3\",  # 紫色 - MUT对照\n  \"ApcWT_Ctrl\" = \"#A65628\"    # 棕色 - WT对照\n)\n\np_pcoa_all <- plotReducedDim(\n  tse_singlem_all,\n  \"PCoA_Bray_All\",\n  colour_by = \"treatment_group\"\n) +\n  scale_color_manual(values = group_colors) +\n  theme_bw() +\n  labs(\n    title = \"SingleM: All Groups PCoA (Bray-Curtis)\",\n    subtitle = \"全部6个实验组的群落结构比较\",\n    x = paste0(\"PCoA 1 (\", round(100 * rel_eig_all[1], 1), \"%)\"),\n    y = paste0(\"PCoA 2 (\", round(100 * rel_eig_all[2], 1), \"%)\"),\n    color = \"Treatment Group\"\n  )\n\n# ==============================================================================\n# 2. Lyrebird 全组 PCoA\n# ==============================================================================\ntse_lyrebird_all <- runMDS(\n  tse_lyrebird_all,\n  FUN = vegan::vegdist,\n  method = \"bray\",\n  assay.type = \"relabundance\",\n  name = \"PCoA_Bray_All\"\n)\n\neig_lyrebird_all <- attr(reducedDim(tse_lyrebird_all, \"PCoA_Bray_All\"), \"eig\")\nrel_eig_lyrebird_all <- eig_lyrebird_all / sum(eig_lyrebird_all[eig_lyrebird_all > 0])\n\np_pcoa_lyrebird_all <- plotReducedDim(\n  tse_lyrebird_all,\n  \"PCoA_Bray_All\",\n  colour_by = \"treatment_group\"\n) +\n  scale_color_manual(values = group_colors) +\n  theme_bw() +\n  labs(\n    title = \"Lyrebird: All Groups PCoA (Bray-Curtis)\",\n    subtitle = \"噬菌体群落结构 - 全部实验组\",\n    x = paste0(\"PCoA 1 (\", round(100 * rel_eig_lyrebird_all[1], 1), \"%)\"),\n    y = paste0(\"PCoA 2 (\", round(100 * rel_eig_lyrebird_all[2], 1), \"%)\"),\n    color = \"Treatment Group\"\n  )\n\n# ==============================================================================\n# 3. 按因子分面的 PCoA\n# ==============================================================================\n# 提取 PCoA 坐标并显式命名列\npcoa_coords <- reducedDim(tse_singlem_all, \"PCoA_Bray_All\")\npcoa_df_singlem <- data.frame(\n  PCoA1 = pcoa_coords[, 1],\n  PCoA2 = pcoa_coords[, 2],\n  treatment_group = colData(tse_singlem_all)$treatment_group,\n  Apc_status = colData(tse_singlem_all)$Apc_status,\n  Hp_status = colData(tse_singlem_all)$Hp_status\n)\n\np_pcoa_facet <- ggplot(pcoa_df_singlem, aes(x = PCoA1, y = PCoA2)) +\n  geom_point(aes(color = Hp_status, shape = Apc_status), size = 3) +\n  facet_wrap(~Apc_status) +\n  theme_bw() +\n  labs(\n    title = \"SingleM: PCoA by Apc Status\",\n    subtitle = \"Hp感染效应在不同Apc背景下的表现\",\n    x = paste0(\"PCoA 1 (\", round(100 * rel_eig_all[1], 1), \"%)\"),\n    y = paste0(\"PCoA 2 (\", round(100 * rel_eig_all[2], 1), \"%)\"),\n    color = \"Hp Status\",\n    shape = \"Apc Status\"\n  )\n\n# 组合图\np_all_groups <- (p_pcoa_all | p_pcoa_lyrebird_all) / p_pcoa_facet +\n  plot_annotation(\n    title = \"Part 4: Extended Group Comparisons - All Groups Visualization\",\n    theme = theme(plot.title = element_text(size = 16, face = \"bold\"))\n  )\n\np_all_groups\n```\n\n::: {.cell-output-display}\n![](03_singlem_diversity_analysis_files/figure-html/extended-all-groups-pcoa-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\n\nggsave(\n  filename = here::here(\"data\", params$name, \"30_extended_all_groups_pcoa.png\"),\n  plot = p_all_groups, width = 16, height = 12, dpi = 300\n)\n```\n:::\n\n\n## 4.3 新增两两比较\n\n### 4.3.1 定义比较对\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# 定义新增的比较对\n# ==============================================================================\ncat(\"=== 新增两两比较 ===\\n\\n\")\n#> === 新增两两比较 ===\n\ncomparison_pairs <- list(\n  # 已完成的核心比较\n  \"Core\" = c(\"ApcMUT_HpWT\", \"ApcMUT_HpKO\"),\n\n  # 新增比较 1: WT背景下的CagA效应\n  \"WT_CagA_Effect\" = c(\"ApcWT_HpWT\", \"ApcWT_HpKO\"),\n\n  # 新增比较 2: CagA感染下的Apc突变效应\n  \"Infected_Apc_Effect\" = c(\"ApcMUT_HpWT\", \"ApcWT_HpWT\"),\n\n  # 新增比较 3: 未感染时的Apc突变效应\n  \"Uninfected_Apc_Effect\" = c(\"ApcMUT_HpKO\", \"ApcWT_HpKO\")\n)\n\n# 为每个比较创建描述\ncomparison_desc <- c(\n  \"Core\" = \"核心比较: CagA效应 (Apc突变背景)\",\n  \"WT_CagA_Effect\" = \"WT背景下CagA感染效应\",\n  \"Infected_Apc_Effect\" = \"CagA感染下Apc突变效应\",\n  \"Uninfected_Apc_Effect\" = \"未感染时Apc突变效应\"\n)\n\ncat(\"将进行以下比较:\\n\")\n#> 将进行以下比较:\nfor (i in seq_along(comparison_pairs)) {\n  cat(sprintf(\"  %d. %s: %s vs %s\\n\",\n              i, names(comparison_pairs)[i],\n              comparison_pairs[[i]][1], comparison_pairs[[i]][2]))\n}\n#>   1. Core: ApcMUT_HpWT vs ApcMUT_HpKO\n#>   2. WT_CagA_Effect: ApcWT_HpWT vs ApcWT_HpKO\n#>   3. Infected_Apc_Effect: ApcMUT_HpWT vs ApcWT_HpWT\n#>   4. Uninfected_Apc_Effect: ApcMUT_HpKO vs ApcWT_HpKO\n```\n:::\n\n\n### 4.3.2 批量进行 PERMANOVA 检验\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# 批量 PERMANOVA 函数\n# ==============================================================================\nrun_pairwise_permanova <- function(tse, pair_name, groups, method = \"bray\") {\n  # 提取子集\n  tse_sub <- tse[, tse$treatment_group %in% groups]\n  tse_sub$treatment_group <- factor(tse_sub$treatment_group, levels = groups)\n\n  # 计算距离\n  dist_mat <- vegan::vegdist(\n    t(assay(tse_sub, \"relabundance\")),\n    method = method\n  )\n\n  # PERMANOVA\n  permanova_res <- vegan::adonis2(\n    dist_mat ~ treatment_group,\n    data = data.frame(colData(tse_sub)),\n    permutations = 999\n  )\n\n  # 提取结果\n  data.frame(\n    Comparison = pair_name,\n    Group1 = groups[1],\n    Group2 = groups[2],\n    n1 = sum(tse_sub$treatment_group == groups[1]),\n    n2 = sum(tse_sub$treatment_group == groups[2]),\n    R2 = round(permanova_res$R2[1], 4),\n    F_statistic = round(permanova_res$F[1], 2),\n    P_value = permanova_res$`Pr(>F)`[1]\n  )\n}\n\n# ==============================================================================\n# 运行 SingleM 两两比较\n# ==============================================================================\ncat(\"\\n=== SingleM 两两比较 (Bray-Curtis PERMANOVA) ===\\n\\n\")\n#> \n#> === SingleM 两两比较 (Bray-Curtis PERMANOVA) ===\n\nsinglem_pairwise_results <- bind_rows(lapply(\n  names(comparison_pairs),\n  function(name) {\n    run_pairwise_permanova(tse_singlem_all, name, comparison_pairs[[name]])\n  }\n))\n\n# 添加 FDR 校正\nsinglem_pairwise_results$P_adj <- p.adjust(singlem_pairwise_results$P_value, method = \"BH\")\nsinglem_pairwise_results$Significance <- case_when(\n  singlem_pairwise_results$P_adj < 0.001 ~ \"***\",\n  singlem_pairwise_results$P_adj < 0.01 ~ \"**\",\n  singlem_pairwise_results$P_adj < 0.05 ~ \"*\",\n  singlem_pairwise_results$P_adj < 0.1 ~ \".\",\n  TRUE ~ \"ns\"\n)\n\nprint(singlem_pairwise_results)\n#>              Comparison      Group1      Group2 n1 n2     R2 F_statistic\n#> 1                  Core ApcMUT_HpWT ApcMUT_HpKO  5  4 0.2315        2.11\n#> 2        WT_CagA_Effect  ApcWT_HpWT  ApcWT_HpKO  5  5 0.1682        1.62\n#> 3   Infected_Apc_Effect ApcMUT_HpWT  ApcWT_HpWT  5  5 0.1075        0.96\n#> 4 Uninfected_Apc_Effect ApcMUT_HpKO  ApcWT_HpKO  4  5 0.4657        6.10\n#>   P_value     P_adj Significance\n#> 1   0.042 0.0840000            .\n#> 2   0.098 0.1306667           ns\n#> 3   0.518 0.5180000           ns\n#> 4   0.009 0.0360000            *\n\n# ==============================================================================\n# 运行 Lyrebird 两两比较\n# ==============================================================================\ncat(\"\\n=== Lyrebird 两两比较 (Bray-Curtis PERMANOVA) ===\\n\\n\")\n#> \n#> === Lyrebird 两两比较 (Bray-Curtis PERMANOVA) ===\n\nlyrebird_pairwise_results <- bind_rows(lapply(\n  names(comparison_pairs),\n  function(name) {\n    run_pairwise_permanova(tse_lyrebird_all, name, comparison_pairs[[name]])\n  }\n))\n\nlyrebird_pairwise_results$P_adj <- p.adjust(lyrebird_pairwise_results$P_value, method = \"BH\")\nlyrebird_pairwise_results$Significance <- case_when(\n  lyrebird_pairwise_results$P_adj < 0.001 ~ \"***\",\n  lyrebird_pairwise_results$P_adj < 0.01 ~ \"**\",\n  lyrebird_pairwise_results$P_adj < 0.05 ~ \"*\",\n  lyrebird_pairwise_results$P_adj < 0.1 ~ \".\",\n  TRUE ~ \"ns\"\n)\n\nprint(lyrebird_pairwise_results)\n#>              Comparison      Group1      Group2 n1 n2     R2 F_statistic\n#> 1                  Core ApcMUT_HpWT ApcMUT_HpKO  5  4 0.2672        2.55\n#> 2        WT_CagA_Effect  ApcWT_HpWT  ApcWT_HpKO  5  5 0.2052        2.07\n#> 3   Infected_Apc_Effect ApcMUT_HpWT  ApcWT_HpWT  5  5 0.0923        0.81\n#> 4 Uninfected_Apc_Effect ApcMUT_HpKO  ApcWT_HpKO  4  5 0.5175        7.51\n#>   P_value     P_adj Significance\n#> 1   0.069 0.1013333           ns\n#> 2   0.076 0.1013333           ns\n#> 3   0.513 0.5130000           ns\n#> 4   0.006 0.0240000            *\n\n# 保存结果\nwrite.csv(\n  singlem_pairwise_results,\n  file = here::here(\"data\", params$name, \"31_extended_pairwise_singlem.csv\"),\n  row.names = FALSE\n)\n\nwrite.csv(\n  lyrebird_pairwise_results,\n  file = here::here(\"data\", params$name, \"32_extended_pairwise_lyrebird.csv\"),\n  row.names = FALSE\n)\n```\n:::\n\n\n### 4.3.3 两两比较结果可视化\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# 两两比较结果条形图\n# ==============================================================================\n\n# 准备绘图数据\nplot_pairwise <- function(results, title) {\n  results$Comparison <- factor(results$Comparison, levels = rev(names(comparison_pairs)))\n\n  ggplot(results, aes(x = Comparison, y = -log10(P_value))) +\n    geom_bar(stat = \"identity\", aes(fill = P_value < 0.05), width = 0.7) +\n    geom_hline(yintercept = -log10(0.05), linetype = \"dashed\", color = \"red\") +\n    geom_text(aes(label = Significance), hjust = -0.3, size = 5) +\n    scale_fill_manual(values = c(\"TRUE\" = \"#E41A1C\", \"FALSE\" = \"grey60\"),\n                     labels = c(\"TRUE\" = \"P < 0.05\", \"FALSE\" = \"P ≥ 0.05\")) +\n    coord_flip() +\n    theme_bw() +\n    labs(\n      title = title,\n      x = \"\",\n      y = \"-log10(P-value)\",\n      fill = \"Significance\"\n    ) +\n    theme(\n      axis.text.y = element_text(size = 10),\n      legend.position = \"bottom\"\n    )\n}\n\np_singlem_pairwise <- plot_pairwise(singlem_pairwise_results, \"SingleM: Pairwise PERMANOVA\")\np_lyrebird_pairwise <- plot_pairwise(lyrebird_pairwise_results, \"Lyrebird: Pairwise PERMANOVA\")\n\n# ==============================================================================\n# R² 效应量热图\n# ==============================================================================\ncombined_results <- bind_rows(\n  singlem_pairwise_results |> mutate(Data = \"SingleM\"),\n  lyrebird_pairwise_results |> mutate(Data = \"Lyrebird\")\n)\n\np_r2_heatmap <- ggplot(combined_results, aes(x = Data, y = Comparison, fill = R2)) +\n  geom_tile(color = \"white\", linewidth = 0.5) +\n  geom_text(aes(label = paste0(round(R2 * 100, 1), \"%\\n\", Significance)), size = 3) +\n  scale_fill_gradient(low = \"white\", high = \"#2166AC\", name = \"R²\") +\n  theme_minimal() +\n  labs(\n    title = \"Effect Size (R²) Heatmap\",\n    subtitle = \"PERMANOVA R² represents variance explained by group\",\n    x = \"\", y = \"\"\n  )\n\n# 组合图\np_pairwise_combined <- (p_singlem_pairwise | p_lyrebird_pairwise) / p_r2_heatmap +\n  plot_layout(heights = c(1, 0.8)) +\n  plot_annotation(\n    title = \"Extended Pairwise Comparisons\",\n    theme = theme(plot.title = element_text(size = 16, face = \"bold\"))\n  )\n\np_pairwise_combined\n```\n\n::: {.cell-output-display}\n![](03_singlem_diversity_analysis_files/figure-html/extended-pairwise-viz-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\n\nggsave(\n  filename = here::here(\"data\", params$name, \"33_extended_pairwise_visualization.png\"),\n  plot = p_pairwise_combined, width = 14, height = 10, dpi = 300\n)\n```\n:::\n\n\n## 4.4 双因素交互作用分析\n\n::: {.callout-important}\n## 核心问题\n\n**CagA 对菌群的重塑效应是否依赖于 Apc 突变背景？**\n\n如果存在显著的 **Apc × Hp 交互作用**，说明 CagA 感染的效应在 Apc 突变小鼠中与野生型小鼠中不同——这对理解 CagA 的致癌机制至关重要。\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# 1. 双因素 PERMANOVA（2×2 设计）\n# ==============================================================================\ncat(\"=== 双因素 PERMANOVA 交互作用分析 ===\\n\\n\")\n#> === 双因素 PERMANOVA 交互作用分析 ===\n\n# SingleM 距离矩阵\nsinglem_dist_2x2 <- vegan::vegdist(\n  t(assay(tse_singlem_2x2, \"relabundance\")),\n  method = \"bray\"\n)\n\n# 双因素 PERMANOVA\nsinglem_two_way <- vegan::adonis2(\n  singlem_dist_2x2 ~ Apc_status * Hp_status,\n  data = data.frame(colData(tse_singlem_2x2)),\n  permutations = 999\n)\n\ncat(\"=== SingleM 双因素 PERMANOVA ===\\n\")\n#> === SingleM 双因素 PERMANOVA ===\nprint(singlem_two_way)\n#> Permutation test for adonis under reduced model\n#> Permutation: free\n#> Number of permutations: 999\n#> \n#> vegan::adonis2(formula = singlem_dist_2x2 ~ Apc_status * Hp_status, data = data.frame(colData(tse_singlem_2x2)), permutations = 999)\n#>          Df SumOfSqs      R2      F Pr(>F)   \n#> Model     3  0.88052 0.31269 2.2748  0.005 **\n#> Residual 15  1.93540 0.68731                 \n#> Total    18  2.81592 1.00000                 \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n# Lyrebird 距离矩阵\nlyrebird_dist_2x2 <- vegan::vegdist(\n  t(assay(tse_lyrebird_2x2, \"relabundance\")),\n  method = \"bray\"\n)\n\n# 双因素 PERMANOVA\nlyrebird_two_way <- vegan::adonis2(\n  lyrebird_dist_2x2 ~ Apc_status * Hp_status,\n  data = data.frame(colData(tse_lyrebird_2x2)),\n  permutations = 999\n)\n\ncat(\"\\n=== Lyrebird 双因素 PERMANOVA ===\\n\")\n#> \n#> === Lyrebird 双因素 PERMANOVA ===\nprint(lyrebird_two_way)\n#> Permutation test for adonis under reduced model\n#> Permutation: free\n#> Number of permutations: 999\n#> \n#> vegan::adonis2(formula = lyrebird_dist_2x2 ~ Apc_status * Hp_status, data = data.frame(colData(tse_lyrebird_2x2)), permutations = 999)\n#>          Df SumOfSqs      R2      F Pr(>F)  \n#> Model     3  0.73322 0.31741 2.3251  0.027 *\n#> Residual 15  1.57677 0.68259                \n#> Total    18  2.30999 1.00000                \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n# ==============================================================================\n# 2. 整理交互作用结果\n# ==============================================================================\nextract_twoway_results <- function(res, data_name) {\n  df <- as.data.frame(res)\n  df$Term <- rownames(df)\n  df$Data <- data_name\n  df <- df[df$Term != \"Total\" & df$Term != \"Residual\", ]\n  df$Term <- gsub(\":\", \" × \", df$Term)\n  df\n}\n\ntwoway_singlem <- extract_twoway_results(singlem_two_way, \"SingleM\")\ntwoway_lyrebird <- extract_twoway_results(lyrebird_two_way, \"Lyrebird\")\n\ntwoway_combined <- bind_rows(twoway_singlem, twoway_lyrebird)\ntwoway_combined$Significance <- case_when(\n  twoway_combined$`Pr(>F)` < 0.001 ~ \"***\",\n  twoway_combined$`Pr(>F)` < 0.01 ~ \"**\",\n  twoway_combined$`Pr(>F)` < 0.05 ~ \"*\",\n  twoway_combined$`Pr(>F)` < 0.1 ~ \".\",\n  TRUE ~ \"ns\"\n)\n\ncat(\"\\n=== 双因素 PERMANOVA 结果汇总 ===\\n\")\n#> \n#> === 双因素 PERMANOVA 结果汇总 ===\nprint(twoway_combined |> dplyr::select(Data, Term, R2, F, `Pr(>F)`, Significance))\n#>               Data  Term        R2        F Pr(>F) Significance\n#> Model...1  SingleM Model 0.3126935 2.274775  0.005           **\n#> Model...2 Lyrebird Model 0.3174122 2.325065  0.027            *\n\nwrite.csv(\n  twoway_combined,\n  file = here::here(\"data\", params$name, \"34_extended_twoway_permanova.csv\"),\n  row.names = FALSE\n)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# 3. 交互作用可视化\n# ==============================================================================\n\n# 交互效应条形图\np_interaction_bar <- ggplot(twoway_combined, aes(x = Term, y = -log10(`Pr(>F)`), fill = Data)) +\n  geom_bar(stat = \"identity\", position = position_dodge(width = 0.8), width = 0.7) +\n  geom_hline(yintercept = -log10(0.05), linetype = \"dashed\", color = \"red\") +\n  geom_text(\n    aes(label = Significance, group = Data),\n    position = position_dodge(width = 0.8),\n    vjust = -0.3, size = 4\n  ) +\n  scale_fill_brewer(palette = \"Set1\") +\n  theme_bw() +\n  labs(\n    title = \"Two-Way PERMANOVA: Main Effects and Interaction\",\n    subtitle = \"Red dashed line = P = 0.05\",\n    x = \"\", y = \"-log10(P-value)\"\n  ) +\n  theme(axis.text.x = element_text(size = 11, face = \"bold\"))\n\n# R² 效应量堆叠条形图\np_r2_stacked <- ggplot(twoway_combined, aes(x = Data, y = R2, fill = Term)) +\n  geom_bar(stat = \"identity\", position = \"stack\", width = 0.6) +\n  scale_fill_brewer(palette = \"Set2\") +\n  theme_bw() +\n  labs(\n    title = \"Variance Explained by Each Factor\",\n    subtitle = \"Stacked R² from two-way PERMANOVA\",\n    x = \"\", y = \"R² (Variance Explained)\",\n    fill = \"Factor\"\n  ) +\n  coord_flip()\n\n# ==============================================================================\n# 4. 交互作用效应图 (Interaction Plot)\n# ==============================================================================\n# 计算每组的平均 Alpha 多样性用于交互图\n\n# 确保 Alpha 已计算\nif (!\"shannon_index\" %in% colnames(colData(tse_singlem_2x2))) {\n  tse_singlem_2x2 <- addAlpha(\n    tse_singlem_2x2,\n    assay.type = \"counts\",\n    index = \"shannon\",\n    name = \"shannon_index\"\n  )\n}\n\ninteraction_df <- data.frame(colData(tse_singlem_2x2)) |>\n  group_by(Apc_status, Hp_status) |>\n  summarise(\n    mean_shannon = mean(shannon_index, na.rm = TRUE),\n    se_shannon = sd(shannon_index, na.rm = TRUE) / sqrt(n()),\n    n = n(),\n    .groups = \"drop\"\n  )\n\np_interaction_plot <- ggplot(interaction_df, aes(x = Hp_status, y = mean_shannon,\n                                                  color = Apc_status, group = Apc_status)) +\n  geom_line(linewidth = 1.2) +\n  geom_point(size = 4) +\n  geom_errorbar(aes(ymin = mean_shannon - se_shannon, ymax = mean_shannon + se_shannon),\n                width = 0.1, linewidth = 0.8) +\n  scale_color_manual(values = c(\"ApcWT\" = \"#377EB8\", \"ApcMUT\" = \"#E41A1C\")) +\n  theme_bw() +\n  labs(\n    title = \"Interaction Plot: Shannon Diversity\",\n    subtitle = \"Non-parallel lines suggest interaction\",\n    x = \"Hp Infection Status\",\n    y = \"Mean Shannon Index\",\n    color = \"Apc Status\"\n  )\n\n# ==============================================================================\n# 5. 组合图\n# ==============================================================================\np_interaction_combined <- (p_interaction_bar | p_r2_stacked) / p_interaction_plot +\n  plot_layout(heights = c(1, 0.8)) +\n  plot_annotation(\n    title = \"Two-Way Factorial Analysis: Apc × Hp Interaction\",\n    theme = theme(plot.title = element_text(size = 16, face = \"bold\"))\n  )\n\np_interaction_combined\n```\n\n::: {.cell-output-display}\n![](03_singlem_diversity_analysis_files/figure-html/extended-interaction-viz-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\n\nggsave(\n  filename = here::here(\"data\", params$name, \"35_extended_interaction_analysis.png\"),\n  plot = p_interaction_combined, width = 14, height = 10, dpi = 300\n)\n```\n:::\n\n\n## 4.5 扩展分析结果汇总\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# 汇总所有扩展分析结果\n# ==============================================================================\ncat(\"\n## 4.6 扩展分析结果汇总\n\n### 4.6.1 两两比较结果 (Bray-Curtis PERMANOVA)\n\n#### SingleM 细菌群落\n\")\n```\n\n\n## 4.6 扩展分析结果汇总\n\n### 4.6.1 两两比较结果 (Bray-Curtis PERMANOVA)\n\n#### SingleM 细菌群落\n\n```{.r .cell-code}\n\nsinglem_pairwise_results |>\n  mutate(Description = comparison_desc[Comparison]) |>\n  dplyr::select(Description, Group1, Group2, n1, n2, R2, P_value, P_adj, Significance) |>\n  knitr::kable(digits = 4, caption = \"SingleM 两两比较 PERMANOVA 结果\")\n```\n\n\n\nTable: SingleM 两两比较 PERMANOVA 结果\n\n|Description                      |Group1      |Group2      | n1| n2|     R2| P_value|  P_adj|Significance |\n|:--------------------------------|:-----------|:-----------|--:|--:|------:|-------:|------:|:------------|\n|核心比较: CagA效应 (Apc突变背景) |ApcMUT_HpWT |ApcMUT_HpKO |  5|  4| 0.2315|   0.042| 0.0840|.            |\n|WT背景下CagA感染效应             |ApcWT_HpWT  |ApcWT_HpKO  |  5|  5| 0.1682|   0.098| 0.1307|ns           |\n|CagA感染下Apc突变效应            |ApcMUT_HpWT |ApcWT_HpWT  |  5|  5| 0.1075|   0.518| 0.5180|ns           |\n|未感染时Apc突变效应              |ApcMUT_HpKO |ApcWT_HpKO  |  4|  5| 0.4657|   0.009| 0.0360|*            |\n\n```{.r .cell-code}\n\ncat(\"\n\n#### Lyrebird 噬菌体群落\n\")\n```\n\n\n\n#### Lyrebird 噬菌体群落\n\n```{.r .cell-code}\n\nlyrebird_pairwise_results |>\n  mutate(Description = comparison_desc[Comparison]) |>\n  dplyr::select(Description, Group1, Group2, n1, n2, R2, P_value, P_adj, Significance) |>\n  knitr::kable(digits = 4, caption = \"Lyrebird 两两比较 PERMANOVA 结果\")\n```\n\n\n\nTable: Lyrebird 两两比较 PERMANOVA 结果\n\n|Description                      |Group1      |Group2      | n1| n2|     R2| P_value|  P_adj|Significance |\n|:--------------------------------|:-----------|:-----------|--:|--:|------:|-------:|------:|:------------|\n|核心比较: CagA效应 (Apc突变背景) |ApcMUT_HpWT |ApcMUT_HpKO |  5|  4| 0.2672|   0.069| 0.1013|ns           |\n|WT背景下CagA感染效应             |ApcWT_HpWT  |ApcWT_HpKO  |  5|  5| 0.2052|   0.076| 0.1013|ns           |\n|CagA感染下Apc突变效应            |ApcMUT_HpWT |ApcWT_HpWT  |  5|  5| 0.0923|   0.513| 0.5130|ns           |\n|未感染时Apc突变效应              |ApcMUT_HpKO |ApcWT_HpKO  |  4|  5| 0.5175|   0.006| 0.0240|*            |\n\n```{.r .cell-code}\n\ncat(\"\n\n### 4.6.2 双因素交互作用分析\n\n\")\n```\n\n\n\n### 4.6.2 双因素交互作用分析\n\n```{.r .cell-code}\n\ntwoway_combined |>\n  dplyr::select(Data, Term, R2, F, `Pr(>F)`, Significance) |>\n  knitr::kable(digits = 4, caption = \"双因素 PERMANOVA 结果 (Apc × Hp)\")\n```\n\n\n\nTable: 双因素 PERMANOVA 结果 (Apc × Hp)\n\n|          |Data     |Term  |     R2|      F| Pr(>F)|Significance |\n|:---------|:--------|:-----|------:|------:|------:|:------------|\n|Model...1 |SingleM  |Model | 0.3127| 2.2748|  0.005|**           |\n|Model...2 |Lyrebird |Model | 0.3174| 2.3251|  0.027|*            |\n\n```{.r .cell-code}\n\n# ==============================================================================\n# 生物学解读\n# ==============================================================================\n# 检查交互作用是否显著\nsinglem_interaction_p <- twoway_combined |>\n  dplyr::filter(Data == \"SingleM\", grepl(\"×\", Term)) |>\n  pull(`Pr(>F)`)\n\nlyrebird_interaction_p <- twoway_combined |>\n  dplyr::filter(Data == \"Lyrebird\", grepl(\"×\", Term)) |>\n  pull(`Pr(>F)`)\n\n# 处理空值或 NA\nif (length(singlem_interaction_p) == 0) singlem_interaction_p <- NA\nif (length(lyrebird_interaction_p) == 0) lyrebird_interaction_p <- NA\n\ncat(\"\n\n### 4.6.3 生物学解读\n\n#### 交互作用分析结果\n\n- **SingleM (细菌)**: Apc × Hp 交互作用 P = \",\n    ifelse(is.na(singlem_interaction_p), \"NA\", round(singlem_interaction_p, 4)), \"\n- **Lyrebird (噬菌体)**: Apc × Hp 交互作用 P = \",\n    ifelse(is.na(lyrebird_interaction_p), \"NA\", round(lyrebird_interaction_p, 4)), \"\n\n\")\n```\n\n\n\n### 4.6.3 生物学解读\n\n#### 交互作用分析结果\n\n- **SingleM (细菌)**: Apc × Hp 交互作用 P =  NA \n- **Lyrebird (噬菌体)**: Apc × Hp 交互作用 P =  NA \n\n```{.r .cell-code}\n\n# 安全检查交互作用显著性\nsinglem_sig <- !is.na(singlem_interaction_p) && singlem_interaction_p < 0.05\nlyrebird_sig <- !is.na(lyrebird_interaction_p) && lyrebird_interaction_p < 0.05\n\nif (singlem_sig || lyrebird_sig) {\n  cat(\"\n::: {.callout-important}\n## 关键发现：存在显著交互作用\n\n检测到 **Apc状态 × Hp感染状态** 的显著交互效应，表明：\n\n**CagA 对肠道菌群的重塑效应依赖于 Apc 突变背景！**\n\n这意味着：\n- 在 Apc 野生型小鼠中，CagA 感染对菌群的影响可能不同\n- Apc 突变可能增强或改变了 CagA 的菌群重塑能力\n- 这支持了 CagA 通过改变肿瘤微环境来促进肿瘤发生的假说\n:::\n\")\n} else {\n  cat(\"\n::: {.callout-note}\n## 交互作用不显著\n\n未检测到显著的 Apc × Hp 交互效应，表明：\n\n**CagA 对菌群的重塑效应在 Apc 野生型和突变型背景下相似**\n\n主效应分析可能更有意义——请参考各因素的独立效应。\n:::\n\")\n}\n```\n\n\n::: {.callout-note}\n## 交互作用不显著\n\n未检测到显著的 Apc × Hp 交互效应，表明：\n\n**CagA 对菌群的重塑效应在 Apc 野生型和突变型背景下相似**\n\n主效应分析可能更有意义——请参考各因素的独立效应。\n:::\n\n```{.r .cell-code}\n\ncat(\"\n\n#### 各比较对的关键发现\n\n| 比较 | 问题 | SingleM P | Lyrebird P | 解读 |\n|------|------|-----------|------------|------|\n| Core | Apc突变背景下CagA效应 | \", singlem_pairwise_results$P_value[1], \" | \", lyrebird_pairwise_results$P_value[1], \" | 核心比较 |\n| WT_CagA_Effect | WT背景下CagA效应 | \", singlem_pairwise_results$P_value[2], \" | \", lyrebird_pairwise_results$P_value[2], \" | CagA独立效应 |\n| Infected_Apc_Effect | 感染下Apc效应 | \", singlem_pairwise_results$P_value[3], \" | \", lyrebird_pairwise_results$P_value[3], \" | 肿瘤背景效应 |\n| Uninfected_Apc_Effect | 未感染时Apc效应 | \", singlem_pairwise_results$P_value[4], \" | \", lyrebird_pairwise_results$P_value[4], \" | 基线差异 |\n\n\")\n```\n\n\n\n#### 各比较对的关键发现\n\n| 比较 | 问题 | SingleM P | Lyrebird P | 解读 |\n|------|------|-----------|------------|------|\n| Core | Apc突变背景下CagA效应 |  0.042  |  0.069  | 核心比较 |\n| WT_CagA_Effect | WT背景下CagA效应 |  0.098  |  0.076  | CagA独立效应 |\n| Infected_Apc_Effect | 感染下Apc效应 |  0.518  |  0.513  | 肿瘤背景效应 |\n| Uninfected_Apc_Effect | 未感染时Apc效应 |  0.009  |  0.006  | 基线差异 |\n\n```{.r .cell-code}\n\n# ==============================================================================\n# 保存汇总数据\n# ==============================================================================\nextended_summary <- list(\n  pairwise_singlem = singlem_pairwise_results,\n  pairwise_lyrebird = lyrebird_pairwise_results,\n  twoway_results = twoway_combined,\n  comparison_descriptions = comparison_desc\n)\n\nsaveRDS(\n  extended_summary,\n  file = here::here(\"data\", params$name, \"36_extended_analysis_summary.rds\")\n)\n\ncat(\"\\n\\n**分析结果已保存至** `data/\", params$name, \"/` 目录下。\\n\")\n```\n\n\n\n**分析结果已保存至** `data/ 03_singlem_diversity_analysis /` 目录下。\n:::\n\n\n# Part 5: 系统性成对比较扩展分析 {#sec-part5}\n\n本部分在Part 4的2×3析因分析基础上，进行更详细的9个成对比较，系统性检验不同实验组之间的菌群差异。\n\n## 5.1 系统性成对比较框架 {#sec-part5-framework}\n\n\n::: {.cell layout-align=\"center\"}\n\n```\n#> \n#> ### 9个系统性成对比较设计\n#> \n#> 本分析扩展Part 4的整体分析，对6个实验组进行9个系统性成对比较：\n#> \n#> **类别1: 不同感染状态下的Apc效应 (3个比较)**\n#> \n#> | 编号 | 比较 | 问题 |\n#> |------|------|------|\n#> | 1 | ApcMUT_Ctrl vs ApcWT_Ctrl | 未感染时，Apc突变的基线效应 |\n#> | 2 | ApcMUT_HpKO vs ApcWT_HpKO | HpKO感染下，Apc突变的效应 |\n#> | 3 | ApcMUT_HpWT vs ApcWT_HpWT | CagA+感染下，Apc突变的效应 |\n#> \n#> **类别2: ApcMUT背景下的感染效应 (3个比较)**\n#> \n#> | 编号 | 比较 | 问题 |\n#> |------|------|------|\n#> | 4 | ApcMUT_HpWT vs ApcMUT_Ctrl | ApcMUT中，CagA+感染 vs 未感染 |\n#> | 5 | ApcMUT_HpKO vs ApcMUT_Ctrl | ApcMUT中，CagA-感染 vs 未感染 |\n#> | 6 | ApcMUT_HpWT vs ApcMUT_HpKO | **核心比较**: ApcMUT中CagA效应 |\n#> \n#> **类别3: ApcWT背景下的感染效应 (3个比较)**\n#> \n#> | 编号 | 比较 | 问题 |\n#> |------|------|------|\n#> | 7 | ApcWT_HpWT vs ApcWT_Ctrl | ApcWT中，CagA+感染 vs 未感染 |\n#> | 8 | ApcWT_HpKO vs ApcWT_Ctrl | ApcWT中，CagA-感染 vs 未感染 |\n#> | 9 | ApcWT_HpWT vs ApcWT_HpKO | ApcWT中CagA效应 |\n```\n:::\n\n\n## 5.2 SingleM Beta多样性9个成对比较 {#sec-part5-singlem-pairwise}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 定义9个比较对\ncomparisons_9 <- list(\n  # 类别1: 不同感染状态下的Apc效应\n  list(g1 = \"ApcMUT_Ctrl\", g2 = \"ApcWT_Ctrl\", cat = \"Apc_Effect\", desc = \"Ctrl下Apc效应\"),\n  list(g1 = \"ApcMUT_HpKO\", g2 = \"ApcWT_HpKO\", cat = \"Apc_Effect\", desc = \"HpKO下Apc效应\"),\n  list(g1 = \"ApcMUT_HpWT\", g2 = \"ApcWT_HpWT\", cat = \"Apc_Effect\", desc = \"HpWT下Apc效应\"),\n  # 类别2: ApcMUT背景下的感染效应\n  list(g1 = \"ApcMUT_HpWT\", g2 = \"ApcMUT_Ctrl\", cat = \"Infection_MUT\", desc = \"ApcMUT: HpWT vs Ctrl\"),\n  list(g1 = \"ApcMUT_HpKO\", g2 = \"ApcMUT_Ctrl\", cat = \"Infection_MUT\", desc = \"ApcMUT: HpKO vs Ctrl\"),\n  list(g1 = \"ApcMUT_HpWT\", g2 = \"ApcMUT_HpKO\", cat = \"Infection_MUT\", desc = \"ApcMUT: CagA效应\"),\n  # 类别3: ApcWT背景下的感染效应\n  list(g1 = \"ApcWT_HpWT\", g2 = \"ApcWT_Ctrl\", cat = \"Infection_WT\", desc = \"ApcWT: HpWT vs Ctrl\"),\n  list(g1 = \"ApcWT_HpKO\", g2 = \"ApcWT_Ctrl\", cat = \"Infection_WT\", desc = \"ApcWT: HpKO vs Ctrl\"),\n  list(g1 = \"ApcWT_HpWT\", g2 = \"ApcWT_HpKO\", cat = \"Infection_WT\", desc = \"ApcWT: CagA效应\")\n)\n\n# 计算SingleM距离矩阵\nsinglem_counts <- assay(tse_singlem_all, \"counts\")\nsinglem_rel <- t(t(singlem_counts) / colSums(singlem_counts))\nsinglem_bray <- vegan::vegdist(t(singlem_rel), method = \"bray\")\nsinglem_meta <- as.data.frame(colData(tse_singlem_all))\n\n# 执行9个PERMANOVA比较\nsinglem_9comp_results <- lapply(seq_along(comparisons_9), function(i) {\n  comp <- comparisons_9[[i]]\n\n  # 筛选样本\n  idx <- singlem_meta$treatment_group %in% c(comp$g1, comp$g2)\n  if (sum(idx) < 4) {\n    return(data.frame(\n      Comparison = paste(comp$g1, \"vs\", comp$g2),\n      Category = comp$cat,\n      Description = comp$desc,\n      n_g1 = sum(singlem_meta$treatment_group == comp$g1),\n      n_g2 = sum(singlem_meta$treatment_group == comp$g2),\n      R2 = NA, F_value = NA, P_value = NA\n    ))\n  }\n\n  sub_meta <- singlem_meta[idx, ]\n  sub_dist <- as.dist(as.matrix(singlem_bray)[idx, idx])\n\n  # PERMANOVA\n  result <- tryCatch({\n    perm <- vegan::adonis2(sub_dist ~ treatment_group, data = sub_meta, permutations = 999)\n    data.frame(\n      Comparison = paste(comp$g1, \"vs\", comp$g2),\n      Category = comp$cat,\n      Description = comp$desc,\n      n_g1 = sum(sub_meta$treatment_group == comp$g1),\n      n_g2 = sum(sub_meta$treatment_group == comp$g2),\n      R2 = round(perm$R2[1], 4),\n      F_value = round(perm$F[1], 3),\n      P_value = perm$`Pr(>F)`[1]\n    )\n  }, error = function(e) {\n    data.frame(\n      Comparison = paste(comp$g1, \"vs\", comp$g2),\n      Category = comp$cat, Description = comp$desc,\n      n_g1 = NA, n_g2 = NA, R2 = NA, F_value = NA, P_value = NA\n    )\n  })\n\n  return(result)\n})\n\nsinglem_9comp_df <- do.call(rbind, singlem_9comp_results)\nsinglem_9comp_df$P_adj <- p.adjust(singlem_9comp_df$P_value, method = \"BH\")\nsinglem_9comp_df$Sig <- ifelse(singlem_9comp_df$P_adj < 0.05, \"***\",\n                               ifelse(singlem_9comp_df$P_value < 0.05, \"*\", \"\"))\n\nknitr::kable(singlem_9comp_df, caption = \"SingleM Beta多样性9个成对PERMANOVA比较\")\n```\n\n::: {.cell-output-display}\n\n\nTable: SingleM Beta多样性9个成对PERMANOVA比较\n\n|Comparison                 |Category      |Description          | n_g1| n_g2|     R2| F_value| P_value|     P_adj|Sig |\n|:--------------------------|:-------------|:--------------------|----:|----:|------:|-------:|-------:|---------:|:---|\n|ApcMUT_Ctrl vs ApcWT_Ctrl  |Apc_Effect    |Ctrl下Apc效应        |    4|    5| 0.1536|   1.270|   0.224| 0.2240000|    |\n|ApcMUT_HpKO vs ApcWT_HpKO  |Apc_Effect    |HpKO下Apc效应        |    4|    5| 0.2682|   2.565|   0.022| 0.0450000|*** |\n|ApcMUT_HpWT vs ApcWT_HpWT  |Apc_Effect    |HpWT下Apc效应        |    5|    5| 0.1841|   1.805|   0.025| 0.0450000|*** |\n|ApcMUT_HpWT vs ApcMUT_Ctrl |Infection_MUT |ApcMUT: HpWT vs Ctrl |    5|    4| 0.1536|   1.270|   0.153| 0.1721250|    |\n|ApcMUT_HpKO vs ApcMUT_Ctrl |Infection_MUT |ApcMUT: HpKO vs Ctrl |    4|    4| 0.2163|   1.656|   0.030| 0.0450000|*** |\n|ApcMUT_HpWT vs ApcMUT_HpKO |Infection_MUT |ApcMUT: CagA效应     |    5|    4| 0.2219|   1.996|   0.017| 0.0450000|*** |\n|ApcWT_HpWT vs ApcWT_Ctrl   |Infection_WT  |ApcWT: HpWT vs Ctrl  |    5|    5| 0.3359|   4.046|   0.013| 0.0450000|*** |\n|ApcWT_HpKO vs ApcWT_Ctrl   |Infection_WT  |ApcWT: HpKO vs Ctrl  |    5|    5| 0.2857|   3.199|   0.007| 0.0450000|*** |\n|ApcWT_HpWT vs ApcWT_HpKO   |Infection_WT  |ApcWT: CagA效应      |    5|    5| 0.1557|   1.475|   0.085| 0.1092857|    |\n\n\n:::\n:::\n\n\n## 5.3 Lyrebird Beta多样性9个成对比较 {#sec-part5-lyrebird-pairwise}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 计算Lyrebird距离矩阵\nlyrebird_counts <- assay(tse_lyrebird_all, \"counts\")\nlyrebird_rel <- t(t(lyrebird_counts) / colSums(lyrebird_counts))\nlyrebird_bray <- vegan::vegdist(t(lyrebird_rel), method = \"bray\")\nlyrebird_meta <- as.data.frame(colData(tse_lyrebird_all))\n\n# 执行9个PERMANOVA比较\nlyrebird_9comp_results <- lapply(seq_along(comparisons_9), function(i) {\n  comp <- comparisons_9[[i]]\n\n  # 筛选样本\n  idx <- lyrebird_meta$treatment_group %in% c(comp$g1, comp$g2)\n  if (sum(idx) < 4) {\n    return(data.frame(\n      Comparison = paste(comp$g1, \"vs\", comp$g2),\n      Category = comp$cat,\n      Description = comp$desc,\n      n_g1 = sum(lyrebird_meta$treatment_group == comp$g1),\n      n_g2 = sum(lyrebird_meta$treatment_group == comp$g2),\n      R2 = NA, F_value = NA, P_value = NA\n    ))\n  }\n\n  sub_meta <- lyrebird_meta[idx, ]\n  sub_dist <- as.dist(as.matrix(lyrebird_bray)[idx, idx])\n\n  # PERMANOVA\n  result <- tryCatch({\n    perm <- vegan::adonis2(sub_dist ~ treatment_group, data = sub_meta, permutations = 999)\n    data.frame(\n      Comparison = paste(comp$g1, \"vs\", comp$g2),\n      Category = comp$cat,\n      Description = comp$desc,\n      n_g1 = sum(sub_meta$treatment_group == comp$g1),\n      n_g2 = sum(sub_meta$treatment_group == comp$g2),\n      R2 = round(perm$R2[1], 4),\n      F_value = round(perm$F[1], 3),\n      P_value = perm$`Pr(>F)`[1]\n    )\n  }, error = function(e) {\n    data.frame(\n      Comparison = paste(comp$g1, \"vs\", comp$g2),\n      Category = comp$cat, Description = comp$desc,\n      n_g1 = NA, n_g2 = NA, R2 = NA, F_value = NA, P_value = NA\n    )\n  })\n\n  return(result)\n})\n\nlyrebird_9comp_df <- do.call(rbind, lyrebird_9comp_results)\nlyrebird_9comp_df$P_adj <- p.adjust(lyrebird_9comp_df$P_value, method = \"BH\")\nlyrebird_9comp_df$Sig <- ifelse(lyrebird_9comp_df$P_adj < 0.05, \"***\",\n                                ifelse(lyrebird_9comp_df$P_value < 0.05, \"*\", \"\"))\n\nknitr::kable(lyrebird_9comp_df, caption = \"Lyrebird Beta多样性9个成对PERMANOVA比较\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Lyrebird Beta多样性9个成对PERMANOVA比较\n\n|Comparison                 |Category      |Description          | n_g1| n_g2|     R2| F_value| P_value|    P_adj|Sig |\n|:--------------------------|:-------------|:--------------------|----:|----:|------:|-------:|-------:|--------:|:---|\n|ApcMUT_Ctrl vs ApcWT_Ctrl  |Apc_Effect    |Ctrl下Apc效应        |    4|    5| 0.1400|   1.139|   0.297| 0.334125|    |\n|ApcMUT_HpKO vs ApcWT_HpKO  |Apc_Effect    |HpKO下Apc效应        |    4|    5| 0.2390|   2.198|   0.029| 0.097500|*   |\n|ApcMUT_HpWT vs ApcWT_HpWT  |Apc_Effect    |HpWT下Apc效应        |    5|    5| 0.1922|   1.903|   0.065| 0.097500|    |\n|ApcMUT_HpWT vs ApcMUT_Ctrl |Infection_MUT |ApcMUT: HpWT vs Ctrl |    5|    4| 0.1248|   0.998|   0.425| 0.425000|    |\n|ApcMUT_HpKO vs ApcMUT_Ctrl |Infection_MUT |ApcMUT: HpKO vs Ctrl |    4|    4| 0.1966|   1.468|   0.098| 0.126000|    |\n|ApcMUT_HpWT vs ApcMUT_HpKO |Infection_MUT |ApcMUT: CagA效应     |    5|    4| 0.2304|   2.096|   0.034| 0.097500|*   |\n|ApcWT_HpWT vs ApcWT_Ctrl   |Infection_WT  |ApcWT: HpWT vs Ctrl  |    5|    5| 0.2322|   2.419|   0.007| 0.063000|*   |\n|ApcWT_HpKO vs ApcWT_Ctrl   |Infection_WT  |ApcWT: HpKO vs Ctrl  |    5|    5| 0.1903|   1.881|   0.046| 0.097500|*   |\n|ApcWT_HpWT vs ApcWT_HpKO   |Infection_WT  |ApcWT: CagA效应      |    5|    5| 0.1699|   1.637|   0.062| 0.097500|    |\n\n\n:::\n:::\n\n\n## 5.4 SingleM与Lyrebird结果对比 {#sec-part5-comparison}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 合并两个数据框\nsinglem_9comp_df$DataType <- \"SingleM (细菌)\"\nlyrebird_9comp_df$DataType <- \"Lyrebird (噬菌体)\"\n\ncombined_9comp <- rbind(singlem_9comp_df, lyrebird_9comp_df)\n\n# 可视化：并排比较\nlibrary(ggplot2)\n\n# 为可视化准备数据\nplot_data <- combined_9comp[!is.na(combined_9comp$P_value), ]\nplot_data$Comparison_short <- sapply(strsplit(plot_data$Comparison, \" vs \"), function(x) {\n  paste0(gsub(\"Apc\", \"\", x[1]), \"\\nvs\\n\", gsub(\"Apc\", \"\", x[2]))\n})\n\np_comparison <- ggplot(plot_data, aes(x = reorder(Comparison_short, -P_value), y = -log10(P_value), fill = DataType)) +\n  geom_bar(stat = \"identity\", position = position_dodge(width = 0.8), width = 0.7) +\n  geom_hline(yintercept = -log10(0.05), linetype = \"dashed\", color = \"red\", linewidth = 0.8) +\n  facet_wrap(~Category, scales = \"free_x\", ncol = 3,\n             labeller = labeller(Category = c(\n               \"Apc_Effect\" = \"Apc效应 (不同感染状态)\",\n               \"Infection_MUT\" = \"感染效应 (ApcMUT背景)\",\n               \"Infection_WT\" = \"感染效应 (ApcWT背景)\"\n             ))) +\n  scale_fill_manual(values = c(\"SingleM (细菌)\" = \"#4DBBD5\", \"Lyrebird (噬菌体)\" = \"#E64B35\")) +\n  labs(\n    title = \"SingleM与Lyrebird 9个成对比较结果\",\n    subtitle = \"红色虚线: P = 0.05\",\n    x = \"比较对\",\n    y = \"-log10(P value)\",\n    fill = \"数据类型\"\n  ) +\n  theme_bw(base_size = 11) +\n  theme(\n    axis.text.x = element_text(size = 7, angle = 0),\n    legend.position = \"bottom\",\n    strip.background = element_rect(fill = \"#f0f0f0\")\n  )\n\nprint(p_comparison)\n```\n\n::: {.cell-output-display}\n![](03_singlem_diversity_analysis_files/figure-html/part5-combined-comparison-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n## 5.5 CagA效应：细菌与噬菌体协同分析 {#sec-part5-caga-effect}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 提取CagA效应比较 (比较6和9)\ncaga_comparisons <- combined_9comp[grepl(\"CagA效应\", combined_9comp$Description), ]\n\nif (nrow(caga_comparisons) > 0) {\n  cat(\"### CagA效应在不同Apc背景下的比较\\n\\n\")\n\n  knitr::kable(\n    caga_comparisons[, c(\"DataType\", \"Comparison\", \"R2\", \"F_value\", \"P_value\", \"P_adj\", \"Sig\")],\n    caption = \"CagA效应比较 (HpWT vs HpKO)\"\n  )\n\n  # 可视化CagA效应\n  p_caga <- ggplot(caga_comparisons, aes(x = DataType, y = R2, fill = gsub(\" vs .*\", \"\", Comparison))) +\n    geom_bar(stat = \"identity\", position = position_dodge(width = 0.7), width = 0.6) +\n    geom_text(aes(label = paste0(\"P=\", round(P_value, 3))),\n              position = position_dodge(width = 0.7), vjust = -0.5, size = 3) +\n    scale_fill_manual(values = c(\"ApcMUT_HpWT\" = \"#E64B35\", \"ApcWT_HpWT\" = \"#4DBBD5\")) +\n    labs(\n      title = \"CagA效应：ApcMUT vs ApcWT背景比较\",\n      subtitle = \"R² 表示CagA感染解释的菌群变异比例\",\n      x = \"数据类型\",\n      y = \"R² (方差解释比例)\",\n      fill = \"Apc背景\"\n    ) +\n    theme_bw(base_size = 12) +\n    theme(legend.position = \"bottom\")\n\n  print(p_caga)\n}\n#> ### CagA效应在不同Apc背景下的比较\n```\n\n::: {.cell-output-display}\n![](03_singlem_diversity_analysis_files/figure-html/part5-caga-effect-analysis-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n## 5.6 Part 5 结论汇总 {#sec-part5-summary}\n\n\n::: {.cell layout-align=\"center\"}\n\n### 9个成对比较结果汇总\n\n| 数据类型 | 名义显著 (P<0.05) | FDR显著 (q<0.05) |\n|----------|-------------------|------------------|\n| SingleM (细菌) |  6 /9 |  6 /9 |\n| Lyrebird (噬菌体) |  4 /9 |  0 /9 |\n\n### 核心发现\n\n**核心比较 (ApcMUT背景下CagA效应):**\n\n- SingleM (细菌): R² = 0.2219 , P = 0.017 \n- Lyrebird (噬菌体): R² = 0.2304 , P = 0.034 \n\n\n**Part 5分析结果已保存至** `data/ 03_singlem_diversity_analysis /50_part5_9comparisons.rds`\n:::\n\n\n::: {.callout-tip}\n## Part 5 分析总结\n\n本部分完成了9个系统性成对PERMANOVA比较，与01和02分析文件的扩展分析保持一致。\n\n**分析框架**:\n- 类别1: 不同感染状态下的Apc突变效应\n- 类别2: ApcMUT背景下的感染效应\n- 类别3: ApcWT背景下的感染效应\n\n**结果解读**:\n- 通过比较细菌(SingleM)和噬菌体(Lyrebird)在同一比较对中的响应，可以评估细菌-噬菌体协同变化模式\n- 核心比较6(ApcMUT: HpWT vs HpKO)直接检验CagA蛋白对微生物组的效应\n:::\n\n\n\n# Part 6: 噬菌体-功能整合分析 {#sec-part6}\n\n::: {.callout-note}\n## 分析目的\n\n整合 03 分析（SingleM/Lyrebird）和 02 分析（HUMAnN功能）的结果，探索：\n\n1. **噬菌体-功能关联**：噬菌体OTU丰度与KO/Pathway丰度的相关性\n2. **三角互作网络**：细菌-噬菌体-功能的联合分析\n\n**科学意义**：噬菌体通过裂解/溶原影响细菌群落，可能间接调控菌群的代谢功能。\n:::\n\n## 6.1 辅助函数定义\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ==============================================================================\n# OMA风格辅助函数：跨矩阵Spearman相关性计算\n# ==============================================================================\n\n#' 计算两个矩阵之间的Spearman相关性（向量化）\n#'\n#' @param mat_x 矩阵X (样本×特征A)\n#' @param mat_y 矩阵Y (样本×特征B)，样本数需与mat_x一致\n#' @return 列表包含：r (相关系数矩阵), P (p值矩阵), n (样本数)\ncross_rcorr <- function(mat_x, mat_y) {\n  stopifnot(nrow(mat_x) == nrow(mat_y))\n\n  n <- nrow(mat_x)\n  nx <- ncol(mat_x)\n  ny <- ncol(mat_y)\n\n  # 合并矩阵后使用Hmisc::rcorr\n  combined <- cbind(mat_x, mat_y)\n  rcorr_result <- Hmisc::rcorr(as.matrix(combined), type = \"spearman\")\n\n  # 提取跨矩阵部分\n  r_matrix <- rcorr_result$r[1:nx, (nx+1):(nx+ny)]\n  p_matrix <- rcorr_result$P[1:nx, (nx+1):(nx+ny)]\n\n  # 恢复行列名\n  rownames(r_matrix) <- colnames(mat_x)\n  colnames(r_matrix) <- colnames(mat_y)\n  rownames(p_matrix) <- colnames(mat_x)\n  colnames(p_matrix) <- colnames(mat_y)\n\n  list(r = r_matrix, P = p_matrix, n = n)\n}\n\n#' 将相关性结果转换为长格式数据框\ncorr_to_df <- function(cor_result, name_x = \"feature_x\", name_y = \"feature_y\") {\n  df <- expand.grid(\n    feature_x = rownames(cor_result$r),\n    feature_y = colnames(cor_result$r),\n    stringsAsFactors = FALSE\n  )\n  names(df)[1:2] <- c(name_x, name_y)\n\n  df$correlation <- as.vector(cor_result$r)\n  df$pvalue <- as.vector(cor_result$P)\n  df$qvalue <- p.adjust(df$pvalue, method = \"BH\")\n  df$abs_cor <- abs(df$correlation)\n\n  df\n}\n\n#' 从相关性结果创建网络边\ncorr_to_edges <- function(cor_result, cor_threshold = 0.5, fdr_threshold = 0.25, edge_type = \"Association\") {\n  df <- corr_to_df(cor_result)\n\n  df |>\n    dplyr::filter(abs_cor > cor_threshold, qvalue < fdr_threshold) |>\n    transmute(\n      from = .data[[names(df)[1]]],\n      to = .data[[names(df)[2]]],\n      weight = correlation,\n      type = edge_type\n    )\n}\n```\n:::\n\n\n## 6.2 数据导入\n\n从 02 和 03 分析的产出读取预处理好的数据。\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncat(\"=== Part 6: 噬菌体-功能整合分析 ===\\n\\n\")\n#> === Part 6: 噬菌体-功能整合分析 ===\n\n# ------------------------------------------------------------------------------\n# 从 02 分析导入功能数据\n# ------------------------------------------------------------------------------\ntse_ko <- readRDS(here::here(\"data\", \"02_functional_profiling\", \"tse_ko_corepair.rds\"))\ntse_pathway <- readRDS(here::here(\"data\", \"02_functional_profiling\", \"tse_humann_pathway_corepair.rds\"))\n\ncat(\"02 分析数据:\\n\")\n#> 02 分析数据:\ncat(\"  KO TSE: \", ncol(tse_ko), \" 样本, \", nrow(tse_ko), \" KOs\\n\")\n#>   KO TSE:  9  样本,  3947  KOs\ncat(\"  Pathway TSE: \", ncol(tse_pathway), \" 样本, \", nrow(tse_pathway), \" Pathways\\n\")\n#>   Pathway TSE:  9  样本,  640  Pathways\n\n# ------------------------------------------------------------------------------\n# 从 03 分析使用已加载的数据\n# ------------------------------------------------------------------------------\ncat(\"\\n03 分析数据:\\n\")\n#> \n#> 03 分析数据:\ncat(\"  Lyrebird (噬菌体) TSE: \", ncol(tse_lyrebird_corepair), \" 样本, \", nrow(tse_lyrebird_corepair), \" OTUs\\n\")\n#>   Lyrebird (噬菌体) TSE:  9  样本,  878  OTUs\ncat(\"  SingleM (细菌) TSE: \", ncol(tse_singlem_corepair), \" 样本, \", nrow(tse_singlem_corepair), \" OTUs\\n\")\n#>   SingleM (细菌) TSE:  9  样本,  465  OTUs\n\n# ------------------------------------------------------------------------------\n# 找到共同样本\n# ------------------------------------------------------------------------------\ncommon_samples_p6 <- Reduce(base::intersect, list(\n  colnames(tse_ko),\n  colnames(tse_pathway),\n  colnames(tse_lyrebird_corepair),\n  colnames(tse_singlem_corepair)\n))\n\ncat(\"\\n共同样本数: \", length(common_samples_p6), \"\\n\")\n#> \n#> 共同样本数:  9\ncat(\"样本列表: \", paste(common_samples_p6, collapse = \", \"), \"\\n\")\n#> 样本列表:  ca16, ca17, ca18, ca19, ca20, ca26, ca28, ca29, ca30\n\n# 子集化到共同样本\ntse_ko_p6 <- tse_ko[, common_samples_p6]\ntse_pathway_p6 <- tse_pathway[, common_samples_p6]\ntse_lyrebird_p6 <- tse_lyrebird_corepair[, common_samples_p6]\ntse_singlem_p6 <- tse_singlem_corepair[, common_samples_p6]\n```\n:::\n\n\n## 6.3 噬菌体-KO 关联分析\n\n计算噬菌体OTU丰度与KO丰度的Spearman相关性。\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ------------------------------------------------------------------------------\n# 提取噬菌体丰度矩阵\n# ------------------------------------------------------------------------------\nif (\"relabundance\" %in% assayNames(tse_lyrebird_p6)) {\n  phage_abundance <- as.matrix(assay(tse_lyrebird_p6, \"relabundance\"))\n} else {\n  phage_counts <- as.matrix(assay(tse_lyrebird_p6, \"counts\"))\n  phage_abundance <- sweep(phage_counts, 2, colSums(phage_counts), \"/\")\n}\n\n# 过滤低丰度噬菌体（至少在20%样本中存在）\nphage_prevalence <- rowSums(phage_abundance > 0) / ncol(phage_abundance)\nphage_abundant <- phage_prevalence >= 0.2\nphage_abundance_filtered <- phage_abundance[phage_abundant, ]\n\ncat(\"噬菌体过滤:\\n\")\n#> 噬菌体过滤:\ncat(\"  原始 OTU 数:\", nrow(phage_abundance), \"\\n\")\n#>   原始 OTU 数: 878\ncat(\"  过滤后 OTU 数 (prevalence >= 20%):\", nrow(phage_abundance_filtered), \"\\n\")\n#>   过滤后 OTU 数 (prevalence >= 20%): 571\n\n# ------------------------------------------------------------------------------\n# 提取 KO 丰度矩阵\n# ------------------------------------------------------------------------------\nif (\"cpm\" %in% assayNames(tse_ko_p6)) {\n  ko_abundance <- as.matrix(assay(tse_ko_p6, \"cpm\"))\n} else {\n  ko_counts <- as.matrix(assay(tse_ko_p6, \"counts\"))\n  ko_abundance <- sweep(ko_counts, 2, colSums(ko_counts), \"/\") * 1e6\n}\n\n# 过滤低丰度 KO\nko_prevalence <- rowSums(ko_abundance > 0) / ncol(ko_abundance)\nko_abundant <- ko_prevalence >= 0.2\nko_abundance_filtered <- ko_abundance[ko_abundant, ]\n\ncat(\"\\nKO 过滤:\\n\")\n#> \n#> KO 过滤:\ncat(\"  原始 KO 数:\", nrow(ko_abundance), \"\\n\")\n#>   原始 KO 数: 3947\ncat(\"  过滤后 KO 数 (prevalence >= 20%):\", nrow(ko_abundance_filtered), \"\\n\")\n#>   过滤后 KO 数 (prevalence >= 20%): 3947\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncat(\"=== 计算噬菌体-KO Spearman 相关性 ===\\n\")\n#> === 计算噬菌体-KO Spearman 相关性 ===\n\n# 转置矩阵（样本为行）\nphage_t <- t(phage_abundance_filtered)\nko_t <- t(ko_abundance_filtered)\n\nn_phage <- ncol(phage_t)\nn_ko <- ncol(ko_t)\n\ncat(\"矩阵大小:\", n_phage, \"噬菌体 ×\", n_ko, \"KOs\\n\")\n#> 矩阵大小: 571 噬菌体 × 3947 KOs\n\n# 使用cross_rcorr计算所有相关性\ncor_phage_ko <- cross_rcorr(phage_t, ko_t)\n\n# 转换为长格式数据框\nphage_ko_pairs <- corr_to_df(cor_phage_ko, \"phage\", \"ko\")\n\n# 统计显著关联\nn_sig_005 <- sum(phage_ko_pairs$qvalue < 0.05, na.rm = TRUE)\nn_sig_010 <- sum(phage_ko_pairs$qvalue < 0.10, na.rm = TRUE)\nn_sig_025 <- sum(phage_ko_pairs$qvalue < 0.25, na.rm = TRUE)\n\ncat(\"\\n=== 噬菌体-KO 关联统计 ===\\n\")\n#> \n#> === 噬菌体-KO 关联统计 ===\ncat(\"显著关联数 (FDR < 0.05):\", n_sig_005, \"\\n\")\n#> 显著关联数 (FDR < 0.05): 2877\ncat(\"显著关联数 (FDR < 0.10):\", n_sig_010, \"\\n\")\n#> 显著关联数 (FDR < 0.10): 3349\ncat(\"显著关联数 (FDR < 0.25):\", n_sig_025, \"\\n\")\n#> 显著关联数 (FDR < 0.25): 6604\n\n# Top 20\ncat(\"\\n=== Top 20 噬菌体-KO 关联对 ===\\n\")\n#> \n#> === Top 20 噬菌体-KO 关联对 ===\ntop_pairs <- phage_ko_pairs |> arrange(qvalue, desc(abs_cor)) |> head(20)\nprint(top_pairs |> dplyr::select(phage, ko, correlation, qvalue))\n#>       phage     ko correlation qvalue\n#> 1   OTU_983 K00060           1      0\n#> 2   OTU_792 K00109           1      0\n#> 3  OTU_1330 K00163           1      0\n#> 4   OTU_257 K00236           1      0\n#> 5   OTU_983 K00289           1      0\n#> 6    OTU_60 K00366           1      0\n#> 7   OTU_443 K00366           1      0\n#> 8  OTU_1030 K00366           1      0\n#> 9    OTU_60 K00371           1      0\n#> 10  OTU_443 K00371           1      0\n#> 11 OTU_1030 K00371           1      0\n#> 12   OTU_60 K00375           1      0\n#> 13  OTU_443 K00375           1      0\n#> 14 OTU_1030 K00375           1      0\n#> 15  OTU_378 K00478           1      0\n#> 16  OTU_892 K00478           1      0\n#> 17  OTU_906 K00478           1      0\n#> 18 OTU_1016 K00478           1      0\n#> 19 OTU_1176 K00478           1      0\n#> 20  OTU_378 K00586           1      0\n\n# 保存结果\nwrite.csv(phage_ko_pairs |> arrange(qvalue),\n          file = here::here(\"data\", params$name, \"60_phage_ko_correlation_all.csv\"), row.names = FALSE)\n\nsig_pairs <- phage_ko_pairs |> dplyr::filter(qvalue < 0.25)\nif (nrow(sig_pairs) > 0) {\n  write.csv(sig_pairs |> arrange(qvalue),\n            file = here::here(\"data\", params$name, \"61_phage_ko_correlation_significant.csv\"), row.names = FALSE)\n}\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 从相关性结果提取矩阵\ncor_matrix_phage_ko <- cor_phage_ko$r\n\n# 创建qvalue矩阵用于显著性标记\nqval_matrix_phage_ko <- matrix(\n  phage_ko_pairs$qvalue,\n  nrow = n_phage, ncol = n_ko,\n  dimnames = list(rownames(cor_matrix_phage_ko), colnames(cor_matrix_phage_ko))\n)\n\n# 选择Top特征\nphage_max_cor <- apply(abs(cor_matrix_phage_ko), 1, max, na.rm = TRUE)\ntop_phage <- names(sort(phage_max_cor, decreasing = TRUE))[1:min(30, n_phage)]\n\nko_max_cor <- apply(abs(cor_matrix_phage_ko), 2, max, na.rm = TRUE)\ntop_ko <- names(sort(ko_max_cor, decreasing = TRUE))[1:min(40, n_ko)]\n\n# 子集化并简化名称\ncor_subset <- cor_matrix_phage_ko[top_phage, top_ko]\nqval_subset <- qval_matrix_phage_ko[top_phage, top_ko]\n\nrownames(cor_subset) <- stringr::str_trunc(rownames(cor_subset), 35)\ncolnames(cor_subset) <- stringr::str_trunc(colnames(cor_subset), 15)\n\n# 显著性标记\nsig_marks <- ifelse(qval_subset < 0.05, \"**\",\n                    ifelse(qval_subset < 0.10, \"*\",\n                           ifelse(qval_subset < 0.25, \".\", \"\")))\n\n# 热图\np_heatmap_phage_ko <- pheatmap(\n  cor_subset,\n  color = colorRampPalette(c(\"#2166AC\", \"#F7F7F7\", \"#B2182B\"))(100),\n  breaks = seq(-1, 1, length.out = 101),\n  cluster_rows = TRUE, cluster_cols = TRUE,\n  fontsize_row = 7, fontsize_col = 8, angle_col = 45,\n  main = \"Phage-KO Correlation Heatmap (Spearman)\",\n  display_numbers = sig_marks, number_color = \"black\", fontsize_number = 6,\n  silent = TRUE\n)\n\nprint(p_heatmap_phage_ko)\n```\n\n::: {.cell-output-display}\n![](03_singlem_diversity_analysis_files/figure-html/part6-phage-ko-heatmap-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\n\npng(here::here(\"data\", params$name, \"62_phage_ko_correlation_heatmap.png\"),\n    width = 14, height = 10, units = \"in\", res = 300)\nprint(p_heatmap_phage_ko)\ndev.off()\n#> png \n#>   2\n\ncat(\"\\n** = FDR < 0.05, * = FDR < 0.10, . = FDR < 0.25\\n\")\n#> \n#> ** = FDR < 0.05, * = FDR < 0.10, . = FDR < 0.25\n```\n:::\n\n\n## 6.4 噬菌体-Pathway 关联分析\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 提取 Pathway 丰度矩阵\nif (\"relabundance\" %in% assayNames(tse_pathway_p6)) {\n  pathway_abundance <- as.matrix(assay(tse_pathway_p6, \"relabundance\"))\n} else {\n  pathway_counts <- as.matrix(assay(tse_pathway_p6, \"abundance\"))\n  pathway_abundance <- sweep(pathway_counts, 2, colSums(pathway_counts), \"/\")\n}\n\n# 过滤低丰度通路\npathway_prevalence <- rowSums(pathway_abundance > 0) / ncol(pathway_abundance)\npathway_abundance_filtered <- pathway_abundance[pathway_prevalence >= 0.2, ]\npathway_t <- t(pathway_abundance_filtered)\nn_pathway <- ncol(pathway_t)\n\ncat(\"Pathway 过滤:\\n\")\n#> Pathway 过滤:\ncat(\"  原始通路数:\", nrow(pathway_abundance), \"\\n\")\n#>   原始通路数: 640\ncat(\"  过滤后通路数 (prevalence >= 20%):\", n_pathway, \"\\n\")\n#>   过滤后通路数 (prevalence >= 20%): 567\n\n# 使用cross_rcorr计算相关性\ncor_phage_pathway <- cross_rcorr(phage_t, pathway_t)\nphage_pathway_pairs <- corr_to_df(cor_phage_pathway, \"phage\", \"pathway\")\n\n# 统计\nn_sig_pathway_005 <- sum(phage_pathway_pairs$qvalue < 0.05, na.rm = TRUE)\nn_sig_pathway_010 <- sum(phage_pathway_pairs$qvalue < 0.10, na.rm = TRUE)\nn_sig_pathway_025 <- sum(phage_pathway_pairs$qvalue < 0.25, na.rm = TRUE)\n\ncat(\"\\n=== 噬菌体-Pathway 关联统计 ===\\n\")\n#> \n#> === 噬菌体-Pathway 关联统计 ===\ncat(\"显著关联数 (FDR < 0.05):\", n_sig_pathway_005, \"\\n\")\n#> 显著关联数 (FDR < 0.05): 337\ncat(\"显著关联数 (FDR < 0.10):\", n_sig_pathway_010, \"\\n\")\n#> 显著关联数 (FDR < 0.10): 978\ncat(\"显著关联数 (FDR < 0.25):\", n_sig_pathway_025, \"\\n\")\n#> 显著关联数 (FDR < 0.25): 5338\n\n# 保存结果\nwrite.csv(phage_pathway_pairs |> arrange(qvalue),\n          file = here::here(\"data\", params$name, \"63_phage_pathway_correlation_all.csv\"), row.names = FALSE)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncor_matrix_phage_pathway <- cor_phage_pathway$r\nqval_matrix_phage_pathway <- matrix(\n  phage_pathway_pairs$qvalue,\n  nrow = n_phage, ncol = n_pathway,\n  dimnames = list(rownames(cor_matrix_phage_pathway), colnames(cor_matrix_phage_pathway))\n)\n\n# 选择Top特征\nphage_max_cor_pw <- apply(abs(cor_matrix_phage_pathway), 1, max, na.rm = TRUE)\ntop_phage_pw <- names(sort(phage_max_cor_pw, decreasing = TRUE))[1:min(25, n_phage)]\n\npathway_max_cor <- apply(abs(cor_matrix_phage_pathway), 2, max, na.rm = TRUE)\ntop_pathway <- names(sort(pathway_max_cor, decreasing = TRUE))[1:min(30, n_pathway)]\n\ncor_pw_subset <- cor_matrix_phage_pathway[top_phage_pw, top_pathway]\nqval_pw_subset <- qval_matrix_phage_pathway[top_phage_pw, top_pathway]\n\n# 简化名称\nrownames(cor_pw_subset) <- stringr::str_trunc(rownames(cor_pw_subset), 35)\ncolnames(cor_pw_subset) <- stringr::str_replace(colnames(cor_pw_subset), \".*: \", \"\") |>\n  stringr::str_trunc(40)\n\nsig_marks_pw <- ifelse(qval_pw_subset < 0.05, \"**\",\n                       ifelse(qval_pw_subset < 0.10, \"*\",\n                              ifelse(qval_pw_subset < 0.25, \".\", \"\")))\n\np_heatmap_phage_pathway <- pheatmap(\n  cor_pw_subset,\n  color = colorRampPalette(c(\"#2166AC\", \"#F7F7F7\", \"#B2182B\"))(100),\n  breaks = seq(-1, 1, length.out = 101),\n  cluster_rows = TRUE, cluster_cols = TRUE,\n  fontsize_row = 7, fontsize_col = 7, angle_col = 45,\n  main = \"Phage-Pathway Correlation Heatmap (Spearman)\",\n  display_numbers = sig_marks_pw, number_color = \"black\", fontsize_number = 5,\n  silent = TRUE\n)\n\nprint(p_heatmap_phage_pathway)\n```\n\n::: {.cell-output-display}\n![](03_singlem_diversity_analysis_files/figure-html/part6-phage-pathway-heatmap-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\n\npng(here::here(\"data\", params$name, \"64_phage_pathway_correlation_heatmap.png\"),\n    width = 14, height = 10, units = \"in\", res = 300)\nprint(p_heatmap_phage_pathway)\ndev.off()\n#> png \n#>   2\n```\n:::\n\n\n## 6.5 三角互作网络分析\n\n整合细菌-噬菌体、细菌-KO、噬菌体-KO三种关联，构建三角互作网络。\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncat(\"=== 计算细菌(SingleM) 关联 ===\\n\")\n#> === 计算细菌(SingleM) 关联 ===\n\n# 提取细菌丰度\nif (\"relabundance\" %in% assayNames(tse_singlem_p6)) {\n  bacteria_abundance <- as.matrix(assay(tse_singlem_p6, \"relabundance\"))\n} else {\n  bacteria_counts <- as.matrix(assay(tse_singlem_p6, \"counts\"))\n  bacteria_abundance <- sweep(bacteria_counts, 2, colSums(bacteria_counts), \"/\")\n}\n\n# 过滤\nbacteria_prevalence <- rowSums(bacteria_abundance > 0) / ncol(bacteria_abundance)\nbacteria_abundance_filtered <- bacteria_abundance[bacteria_prevalence >= 0.2, ]\nbacteria_t <- t(bacteria_abundance_filtered)\nn_bacteria <- ncol(bacteria_t)\n\ncat(\"细菌过滤:\\n\")\n#> 细菌过滤:\ncat(\"  原始 OTU 数:\", nrow(bacteria_abundance), \"\\n\")\n#>   原始 OTU 数: 465\ncat(\"  过滤后 OTU 数:\", n_bacteria, \"\\n\")\n#>   过滤后 OTU 数: 323\n\n# 计算细菌-KO和细菌-噬菌体相关性\ncor_bacteria_ko <- cross_rcorr(bacteria_t, ko_t)\ncor_bacteria_phage <- cross_rcorr(bacteria_t, phage_t)\n\nbacteria_ko_pairs <- corr_to_df(cor_bacteria_ko, \"bacteria\", \"ko\")\nbacteria_phage_pairs <- corr_to_df(cor_bacteria_phage, \"bacteria\", \"phage\")\n\nn_sig_bac_ko <- sum(bacteria_ko_pairs$qvalue < 0.25, na.rm = TRUE)\nn_sig_bac_phage <- sum(bacteria_phage_pairs$qvalue < 0.25, na.rm = TRUE)\n\ncat(\"\\n细菌-KO 显著关联数 (FDR < 0.25):\", n_sig_bac_ko, \"\\n\")\n#> \n#> 细菌-KO 显著关联数 (FDR < 0.25): 3700\ncat(\"细菌-噬菌体 显著关联数 (FDR < 0.25):\", n_sig_bac_phage, \"\\n\")\n#> 细菌-噬菌体 显著关联数 (FDR < 0.25): 7544\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncat(\"\\n=== 构建三角互作网络 ===\\n\")\n#> \n#> === 构建三角互作网络 ===\n\n# 阈值设置\ncor_threshold <- 0.5\nfdr_threshold <- 0.25\n\n# 使用corr_to_edges创建边列表\nedges_bacteria_ko <- corr_to_edges(cor_bacteria_ko, cor_threshold, fdr_threshold, \"Bacteria-KO\")\nedges_bacteria_phage <- corr_to_edges(cor_bacteria_phage, cor_threshold, fdr_threshold, \"Bacteria-Phage\")\nedges_phage_ko <- corr_to_edges(cor_phage_ko, cor_threshold, fdr_threshold, \"Phage-KO\")\n\n# 合并所有边\nedges_df <- bind_rows(edges_bacteria_ko, edges_bacteria_phage, edges_phage_ko)\n\nif (nrow(edges_df) > 0) {\n  cat(\"网络边数:\\n\")\n  cat(\"  细菌-KO:\", nrow(edges_bacteria_ko), \"\\n\")\n  cat(\"  细菌-噬菌体:\", nrow(edges_bacteria_phage), \"\\n\")\n  cat(\"  噬菌体-KO:\", nrow(edges_phage_ko), \"\\n\")\n  cat(\"  总计:\", nrow(edges_df), \"\\n\")\n\n  write.csv(edges_df, here::here(\"data\", params$name, \"65_tripartite_network_edges.csv\"), row.names = FALSE)\n\n  # 创建节点列表并确定类型\n  all_nodes <- unique(c(edges_df$from, edges_df$to))\n\n  bacteria_names <- rownames(cor_bacteria_ko$r)\n  phage_names <- rownames(cor_phage_ko$r)\n  ko_names <- colnames(cor_bacteria_ko$r)\n\n  node_type <- dplyr::case_when(\n    all_nodes %in% bacteria_names ~ \"Bacteria\",\n    all_nodes %in% phage_names ~ \"Phage\",\n    all_nodes %in% ko_names ~ \"KO\",\n    TRUE ~ \"Unknown\"\n  )\n\n  nodes_df <- data.frame(\n    name = all_nodes,\n    type = node_type,\n    label = stringr::str_trunc(all_nodes, 20),\n    stringsAsFactors = FALSE\n  )\n\n  # 创建igraph对象\n  g <- igraph::graph_from_data_frame(edges_df, directed = FALSE, vertices = nodes_df)\n  igraph::E(g)$layout_weight <- abs(igraph::E(g)$weight)\n\n  # 绘制网络\n  p_network <- ggraph(g, layout = \"fr\", weights = igraph::E(g)$layout_weight) +\n    geom_edge_link(\n      aes(color = type, width = abs(weight),\n          linetype = ifelse(weight > 0, \"positive\", \"negative\")),\n      alpha = 0.6\n    ) +\n    geom_node_point(aes(color = type), size = 5) +\n    geom_node_text(aes(label = label), repel = TRUE, size = 2.5) +\n    scale_edge_color_manual(\n      values = c(\"Bacteria-KO\" = \"#1B9E77\",\n                 \"Bacteria-Phage\" = \"#D95F02\",\n                 \"Phage-KO\" = \"#7570B3\")\n    ) +\n    scale_edge_linetype_manual(\n      values = c(\"positive\" = \"solid\", \"negative\" = \"dashed\"),\n      name = \"Correlation\"\n    ) +\n    scale_color_manual(\n      values = c(\"Bacteria\" = \"#66C2A5\", \"Phage\" = \"#FC8D62\", \"KO\" = \"#8DA0CB\")\n    ) +\n    theme_void() +\n    labs(\n      title = \"Tripartite Interaction Network\",\n      subtitle = \"Bacteria - Phage - KO associations (|r| > 0.5, FDR < 0.25)\\nSolid = positive, Dashed = negative\",\n      edge_color = \"Edge Type\", color = \"Node Type\"\n    ) +\n    theme(plot.title = element_text(size = 14, face = \"bold\"), legend.position = \"right\")\n\n  print(p_network)\n\n  ggsave(here::here(\"data\", params$name, \"66_tripartite_network.png\"), p_network, width = 14, height = 12, dpi = 300)\n\n} else {\n  cat(\"当前阈值下没有足够的边\\n\")\n}\n#> 网络边数:\n#>   细菌-KO: 3700 \n#>   细菌-噬菌体: 7544 \n#>   噬菌体-KO: 6604 \n#>   总计: 17848\n```\n\n::: {.cell-output-display}\n![](03_singlem_diversity_analysis_files/figure-html/part6-tripartite-network-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n## 6.6 Part 6 结果汇总\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncat(\"\n================================================================================\n                    Part 6: 噬菌体-功能整合分析 结果汇总\n================================================================================\n\n【数据概况】\n- 共同样本数: \", length(common_samples_p6), \"\n- 噬菌体 OTU 数 (过滤后): \", nrow(phage_abundance_filtered), \"\n- 细菌 OTU 数 (过滤后): \", nrow(bacteria_abundance_filtered), \"\n- KO 数 (过滤后): \", nrow(ko_abundance_filtered), \"\n- Pathway 数 (过滤后): \", nrow(pathway_abundance_filtered), \"\n\n【噬菌体-KO 关联分析】\n- 显著关联数 (FDR < 0.05): \", n_sig_005, \"\n- 显著关联数 (FDR < 0.10): \", n_sig_010, \"\n- 显著关联数 (FDR < 0.25): \", n_sig_025, \"\n\n【噬菌体-Pathway 关联分析】\n- 显著关联数 (FDR < 0.05): \", n_sig_pathway_005, \"\n- 显著关联数 (FDR < 0.10): \", n_sig_pathway_010, \"\n- 显著关联数 (FDR < 0.25): \", n_sig_pathway_025, \"\n\n【三角互作网络】\n- 细菌-KO 显著关联: \", n_sig_bac_ko, \" (FDR < 0.25)\n- 细菌-噬菌体 显著关联: \", n_sig_bac_phage, \" (FDR < 0.25)\n- 噬菌体-KO 显著关联: \", n_sig_025, \" (FDR < 0.25)\n\n【科学意义】\n1. 噬菌体-功能关联揭示了噬菌体可能通过影响细菌群落间接调控代谢功能\n2. 三角互作网络展示了 CagA 感染环境下细菌-噬菌体-功能的协同变化模式\n3. 这些发现补充了 02 分析中的物种-功能关联，提供了病毒组视角\n\n================================================================================\n\")\n```\n\n\n================================================================================\n                    Part 6: 噬菌体-功能整合分析 结果汇总\n================================================================================\n\n【数据概况】\n- 共同样本数:  9 \n- 噬菌体 OTU 数 (过滤后):  571 \n- 细菌 OTU 数 (过滤后):  323 \n- KO 数 (过滤后):  3947 \n- Pathway 数 (过滤后):  567 \n\n【噬菌体-KO 关联分析】\n- 显著关联数 (FDR < 0.05):  2877 \n- 显著关联数 (FDR < 0.10):  3349 \n- 显著关联数 (FDR < 0.25):  6604 \n\n【噬菌体-Pathway 关联分析】\n- 显著关联数 (FDR < 0.05):  337 \n- 显著关联数 (FDR < 0.10):  978 \n- 显著关联数 (FDR < 0.25):  5338 \n\n【三角互作网络】\n- 细菌-KO 显著关联:  3700  (FDR < 0.25)\n- 细菌-噬菌体 显著关联:  7544  (FDR < 0.25)\n- 噬菌体-KO 显著关联:  6604  (FDR < 0.25)\n\n【科学意义】\n1. 噬菌体-功能关联揭示了噬菌体可能通过影响细菌群落间接调控代谢功能\n2. 三角互作网络展示了 CagA 感染环境下细菌-噬菌体-功能的协同变化模式\n3. 这些发现补充了 02 分析中的物种-功能关联，提供了病毒组视角\n\n================================================================================\n\n```{.r .cell-code}\n\n# 保存汇总数据\npart6_summary <- list(\n  phage_ko_pairs = phage_ko_pairs,\n  phage_pathway_pairs = phage_pathway_pairs,\n  bacteria_ko_pairs = bacteria_ko_pairs,\n  bacteria_phage_pairs = bacteria_phage_pairs,\n  network_edges = if (exists(\"edges_df\")) edges_df else NULL\n)\n\nsaveRDS(part6_summary,\n        file = here::here(\"data\", params$name, \"67_part6_phage_function_integration.rds\"))\n\ncat(\"\\n**Part 6 分析结果已保存至** `data/\", params$name, \"/67_part6_phage_function_integration.rds`\\n\")\n```\n\n\n**Part 6 分析结果已保存至** `data/ 03_singlem_diversity_analysis /67_part6_phage_function_integration.rds`\n:::\n\n\n::: {.callout-tip}\n## Part 6 分析总结\n\n本部分整合了病毒组（Lyrebird噬菌体）与功能组（HUMAnN KO/Pathway）数据，构建了细菌-噬菌体-功能的三角互作网络。\n\n**核心发现**:\n\n1. **噬菌体-功能关联广泛存在** - 噬菌体与KO之间存在大量显著相关，表明噬菌体丰度变化与宿主菌群的代谢功能密切相关\n\n2. **细菌-噬菌体协同模式** - 正相关可能代表溶原状态下的共存关系，负相关可能反映裂解周期的捕食关系\n\n3. **三角互作网络** - 网络高度连通，显示CagA感染环境下微生物组各层次之间的紧密联系\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}